import os
import json

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GRIDS_PATH = os.path.join(ROOT, "tools", "pending_grids.json")

DESCRIPTIONS = {
    'accreditation': 'a certificate scroll tied with a red ribbon and a gold wax seal',
    'accurately': 'a dart hitting the exact dead center of a target board',
    'acre': 'a green square plot of farmland seen from above',
    'adaptation': 'a green chameleon blending in with a green branch',
    'adaptive': 'a smart robotic arm adjusting its tool head',
    'affiliation': 'two puzzle pieces joining together with a logo',
    'afterwards': 'a clock showing a later time with a forward arrow',
    'align': 'three colored blocks neatly arranged in a straight vertical line',
    'alike': 'two identical twins cartoon characters standing side-by-side',
    'allergy': 'a cartoon character sneezing next to a flower',
    'allowance': 'a hand giving pocket money coins to a child',
    'ambassador': 'a diplomat in a suit shaking hands in front of flags',
    'ambient': 'soft glowing lights radiating from a central bulb',
    'antibody': 'a shield protecting a cell from a small virus',
    'arbitrary': 'a hand randomly picking a card from a deck',
    'citizenship': 'a passport icon next to a globe outline',
    'competent': 'a thumbs-up icon with a certificate badge',
    'complement': 'two interlocking pieces that complete a circle shape',
    'condo': 'a modern multistory apartment building with balconies',
    'confidentiality': 'a key locking a folder document icon',
    'consecutive': 'a calendar showing three consecutive days marked in red',
    'consequently': 'a falling domino causing the next domino to fall',
    'consistency': 'three identical jars filled to the exact same level',
    'conspiracy': 'two mysterious figures in trench coats whispering in the dark',
    'constraint': 'a locked padlock with chains wrapped around a box',
    'continually': 'a circular arrow indicating a continuous loop',
    'continuity': 'a smooth continuous line bridge crossing over a gap',
    'contributor': 'a hand dropping a coin into a charity donation box',
    'conviction': 'a judges gavel hitting the sound block',
    'convinced': 'a cartoon character pointing to a lightbulb idea',
    'cop': 'a police officer badge icon',
    'cove': 'a small quiet bay surrounded by cliffs and sea water',
    'cradle': 'a wooden baby crib rocking gently',
    'crude': 'a barrel leaking black oil drops',
    'cult': 'a group of robed figures standing around a campfire',
    'cumulative': 'a pile of coins building up higher and higher',
    'cursor': 'a white arrow mouse cursor icon pointing up-left',
    'daisy': 'a single white daisy flower with a yellow center',
    'defensive': 'a warrior holding a large shield to block arrows',
    'delegation': 'a boss hand giving a task document to a subordinate hand',
    'delight': 'a cartoon character smiling with stars in their eyes',
    'demographic': 'a chart dividing groups of people by colors',
    'denial': 'a large red cross mark next to a hand indicating stop',
    'dependence': 'a puppy leaning against its owner leg',
    'derby': 'a classic bowler hat icon',
    'desirable': 'a shiny gold star inside a glass display case',
    'detective': 'a magnifying glass highlighting a footprint',
    'deviation': 'a straight arrow line branching off into a curve',
    'dice': 'two red game dice showing the numbers five and six',
    'dip': 'a chip dipping into a bowl of green guacamole',
    'disappointed': 'a sad crying face cartoon icon',
    'disclose': 'a hand opening an envelope to reveal a letter',
    'discrete': 'three separate individual dots clearly spaced apart',
    'dispatch': 'a delivery truck speeding away with motion lines',
    'disposition': 'a scale balancing a heart and a brain',
    'dividend': 'a coin splitting into two smaller coins',
    'dock': 'a wooden pier extending into blue lake water',
    'doctrine': 'an old open book showing scrolls and symbols',
    'dosage': 'a medicine bottle next to a measuring spoon with syrup',
    'drain': 'water swirling down a circular metal drain hole',
    'drainage': 'a metal pipe water drainage system outlet',
    'dramatically': 'a line graph shooting straight upwards rapidly',
    'dressed': 'a coat hanger holding a smart suit jacket',
    'dryer': 'a laundry washing machine dryer with a tumbling shirt inside',
    'dumb': 'a cartoon character looking confused with question marks',
    'earthquake': 'a ground crack splitting a cartoon house in two',
    'educated': 'a graduation cap resting on a stack of books',
    'efficiently': 'a clock icon merged with a green checkmark',
    'electoral': 'a hand dropping a voting ballot paper into a ballot box',
    'elevation': 'a mountain peak showing height contour lines',
    'elimination': 'a red eraser erasing a pencil line drawing',
    'emperor': 'a royal emperor crown sitting on a golden pillow',
    'empirical': 'a scientist looking through a microscope at a slide',
    'endangered': 'a cute giant panda sitting on bamboo',
    'endless': 'an infinity loop symbol icon',
    'endorsement': 'a document stamped with a green APPROVED stamp',
    'engaging': 'a book with colorful magic dust rising from it',
    'ensemble': 'a group of musical instruments playing together',
    'entertaining': 'a theater stage showing red curtains open',
    'exclusion': 'one red circle standing outside a fence enclosing blue circles',
    'exemption': 'a badge showing a free pass or ticket',
    'fare': 'a train ticket next to a coin',
    'heater': 'a small portable space heater radiating warm orange air waves',
    'humanitarian': 'two hands holding a green planet earth icon',
    'hygiene': 'a bar of soap and bubbles next to a toothbrush',
    'hypothesis': 'a blackboard showing math formulas and a question mark',
    'hypothetical': 'a thought bubble containing a cloud and a lightning bolt',
    'impaired': 'broken eyeglasses next to a bandage',
    'impressed': 'a face looking up with wide eyes and open mouth',
    'incidence': 'a chart showing points of events occurring',
    'infectious': 'a cartoon germ character with spikes',
    'informative': 'a clean open book showing colorful charts and maps',
    'insertion': 'a hand inserting a key into a keyhole',
    'instrumental': 'a wrench fixing a complex gear system',
    'insulation': 'a wall showing thick insulation foam layers',
    'insulin': 'a small medical syringe next to an insulin vial',
    'interference': 'static electricity waves blocking a signal line',
    'intersection': 'a four-way road junction crossing seen from above',
    'interstate': 'a highway road sign showing number ninety-five',
    'interventions': 'a life preserver ring thrown into water',
    'intimate': 'two hands holding each other gently',
    'invisible': 'a ghost outline shape fading into the background',
    'karma': 'a circular arrow showing cause and effect',
    'keen': 'an eagle eye looking sharply',
    'kilometers': 'a highway speed sign showing one hundred km',
    'knit': 'two wooden knitting needles with a ball of wool yarn',
    'ladder': 'a tall wooden ladder leaning forward',
    'lasting': 'a green tree with deep thick roots',
    'lately': 'a calendar page showing today marked in red',
    'lazy': 'a cute cartoon cat sleeping on a pillow',
    'legendary': 'a golden sword stuck in a stone boulder',
    'lesser': 'a small star next to a giant star',
    'levy': 'a bag of tax money with a government seal',
    'likelihood': 'a weather forecast showing a high chance of rain',
    'likewise': 'a mirror reflecting a cartoon character waving back',
    'lobby': 'a spacious hotel lobby desk with a reception bell',
    'longitude': 'a globe showing vertical longitude grid lines',
    'magical': 'a magic wand casting sparkling stars',
    'magnificent': 'a majestic castle standing on top of a mountain',
    'magnitude': 'an earthquake seismograph line chart spiking',
    'mandate': 'an official scroll document stamped with a wax seal',
    'marathon': 'a runner crossing the finish line tape',
    'marsh': 'a swampy green marsh wetland with cattail plants',
    'mattress': 'a comfortable bouncy white bed mattress',
    'maximize': 'a window screen with a maximize button icon',
    'meaningful': 'a heart glowing inside a lightbulb',
    'meditation': 'a cartoon character sitting in lotus meditation pose',
    'mentor': 'an old wise guide pointing a pathway to a young person',
    'mesa': 'a flat-topped table mountain mesa desert plateau',
    'microphone': 'a classic retro vocal microphone on a stand',
    'mild': 'a sun peaking behind a friendly cloud',
    'mixer': 'an electric kitchen stand mixer bowl',
    'momentum': 'a heavy bowling ball rolling fast towards pins',
    'moss': 'soft green moss growing over a forest tree branch',
    'motherboard': 'a green computer motherboard circuit board with chips',
    'mud': 'a muddy puddle with brown boots stepping in it',
    'municipality': 'a town hall building with a clock tower',
    'mysterious': 'a keyhole showing a glowing key inside a dark room',
    'navigator': 'a hand holding a classic magnetic compass',
    'necessity': 'a glass of water and a loaf of bread',
    'norm': 'a bell curve graph showing the standard average',
    'obesity': 'a cartoon character trying to buckle a tight belt',
    'optimize': 'a gear merged with a rocket taking off',
    'organizer': 'a desktop calendar with colored sticky notes',
    'ours': 'a group of children pointing to their shared sandbox castle',
    'parcel': 'a brown cardboard delivery package box wrapped in string',
    'parental': 'a parent bird feeding its baby bird in a nest',
    'parliamentary': 'a government assembly hall with debating seats',
    'passive': 'a cartoon character relaxing in a hammock',
    'pastor': 'a pastor in robes standing at a church pulpit',
    'patrol': 'a police car with flashing blue and red lights',
    'pavilion': 'an open garden pavilion gazebo structure surrounded by flowers',
    'peaceful': 'a white dove holding an olive branch in its beak',
    'pencil': 'a classic yellow wooden pencil with a pink eraser',
    'peninsula': 'a narrow strip of land surrounded by water on three sides',
    'performs': 'a singer performing on a stage under a spotlight',
    'peripheral': 'a computer keyboard and mouse next to a monitor',
    'persistent': 'a small green sprout growing through a crack in concrete',
    'picnic': 'a red checkered picnic blanket with a basket and fruit',
    'pillow': 'a soft fluffy white bed pillow',
    'planners': 'a detailed binder notebook showing schedules',
    'pledge': 'a hand placed over a heart making a promise',
    'poison': 'a glass bottle marked with a skull and crossbones symbol',
    'polyester': 'a spool of colorful synthetic clothing thread',
    'pork': 'a slice of raw pork chop meat on a cutting board',
    'positioning': 'a map pin marker showing the exact GPS location',
    'postcard': 'a postcard showing a beach scene with a stamp',
    'practitioner': 'a doctor wearing a stethoscope holding a clipboard',
    'preceding': 'an arrow pointing to the page before',
    'prerequisite': 'a key required to open a locked door',
    'presently': 'a digital clock showing the current time',
    'privilege': 'a shiny silver ticket key card granting special access',
    'promising': 'a small green sprout with gold sparkles rising from the soil',
    'promptly': 'a stopwatch showing a zero second countdown',
    'proposition': 'two hands holding a new idea lightbulb to discuss',
    'prototype': 'a 3D printer printing a plastic toy model',
    'publicity': 'a camera flashing at a celebrity red carpet entrance',
    'punch': 'a cartoon boxing glove punching forward',
    'puppy': 'a cute little brown puppy dog wagging its tail',
    'purse': 'a small elegant leather coin purse bag',
    'pursuit': 'a police car chasing a speeding red car',
    'qualification': 'a verified checkmark next to a diploma certificate',
    'quantitative': 'a calculator showing numbers and mathematical symbols',
    'questionnaire': 'a clipboard showing a multiple choice survey list',
    'raises': 'a hand lifting a heavy barbell weights bar',
    'ratios': 'a pie chart showing different proportion slices',
    'readily': 'a box opening to reveal tools ready to use',
    'realm': 'a magical fantasy castle floating on a cloud',
    'realtor': 'a real estate agent holding a sign saying SOLD',
    'reasoning': 'a brain icon with gears turning inside',
    'rebel': 'a fist raised high holding a flag',
    'reductions': 'a price tag showing a fifty percent discount sign',
    'reef': 'a colorful coral reef underwater scene with small fish',
    'refresh': 'a circular refresh arrow button icon',
    'refrigerator': 'a modern silver kitchen refrigerator appliance',
    'regression': 'a line graph dropping downwards with a backward arrow',
    'remainder': 'one puzzle piece left over next to a completed puzzle',
    'remark': 'a speech bubble icon with three dots',
    'remedy': 'a bottle of cough syrup next to a spoon',
    'removable': 'a USB flash drive being unplugged from a port',
    'render': 'a computer generating a realistic 3D sphere object',
    'rendering': 'a computer screen showing a draft sketch turning into color',
    'renew': 'a recycle symbol made of green leaves',
    'renewable': 'a wind turbine next to solar panels and a sun',
    'replication': 'a printer duplicating a document sheet',
    'reproduce': 'a seedling dropping seeds to grow new seedlings',
    'reproductive': 'a DNA double helix strand icon',
    'restructuring': 'blocks being rearranged to form a new tower structure',
    'resumes': 'a play button arrow resuming music playback',
    'retreat': 'a hiking backpack outside a cozy wooden cabin',
    'retrieve': 'a dog fetching a red ball back to its owner',
    'revelation': 'a curtain opening to reveal a bright glowing chest',
    'revenge': 'a target board with a dart hitting the bullseye',
    'revolutionary': 'a futuristic flying car cartoon icon',
    'roommate': 'two cartoon characters sharing a bunk bed',
    'rug': 'a cozy woven carpet rug with patterns lying on a floor',
    'runtime': 'a progress bar showing an app running',
    'sacrifice': 'a chess king piece being traded to win a game',
    'sandwich': 'a double decker sandwich with ham cheese and lettuce',
    'satin': 'a smooth folded roll of shiny red satin fabric silk',
    'scary': 'a friendly cartoon ghost booing in the dark',
    'scenic': 'a beautiful mountain range landscape view seen from a window',
    'schema': 'a structured database tree diagram flowchart',
    'selective': 'a hand choosing the best red apple from a basket of green apples',
    'serum': 'a dropper bottle dropping a liquid drop',
    'sexuality': 'interlocking male and female gender symbols',
    'shame': 'a cartoon character covering their red face in embarrassment',
    'shed': 'a small wooden storage tool shed in a backyard garden',
    'sheer': 'a light translucent curtain blowing in the breeze',
    'signatures': 'a pen signing a signature on a document line',
    'slope': 'a steep snowy mountain slope with a skier silhouette',
    'sphere': 'a perfect blue shiny three-dimensional sphere ball',
    'spine': 'a spine column diagram showing vertebrae bones',
    'stationery': 'a set of colorful envelopes pens and notebooks',
    'sticky': 'a yellow post-it note sticking to a board',
    'strand': 'a single twisted strand of colorful rope thread',
    'striking': 'a bolt of lightning striking a tree trunk',
    'subdivision': 'a residential map showing separate home plots',
    'subjective': 'a cloud thought bubble showing a personal opinion icon',
    'subtle': 'a delicate faint gradient line fading out gently',
    'suburban': 'neat suburban houses with green lawns and white fences',
    'sufficiently': 'a bowl overflowing with fresh delicious soup',
    'sunrise': 'a yellow sun rising over the ocean horizon',
    'superintendent': 'a manager wearing a hard hat inspecting a site',
    'surge': 'a sudden powerful ocean wave breaking forward',
    'surgeon': 'a surgeon wearing green scrubs holding a scalpel instrument',
    'surname': 'a classic nametag saying HELLO MY SURNAME IS',
    'sustainability': 'a green leaf growing out of a lightbulb',
    'swift': 'a fast flying swallow bird flying through the air',
    'sympathy': 'a cartoon hand holding a crying face shoulder to comfort',
    'sync': 'two circular arrows syncing file folders together',
    'systematic': 'folders sorted neatly in numerical order',
    'tackle': 'a cartoon helmet and American football ball icon',
    'talented': 'a paint palette with a brush and a golden award star',
    'tariff': 'a customs document stamp showing import tax fee',
    'temporal': 'a clock symbol merged with a hourglass'
}

def main():
    if not os.path.exists(GRIDS_PATH):
        print(f"Error: {GRIDS_PATH} not found!")
        return

    with open(GRIDS_PATH, "r", encoding="utf-8") as f:
        grids = json.load(f)

    updated_count = 0
    for grid_num, words_info in grids.items():
        for item in words_info:
            word = item["word"].lower().strip()
            # If word has special description, add it
            if word in DESCRIPTIONS:
                item["visual_description"] = DESCRIPTIONS[word]
                updated_count += 1
            else:
                # Placeholder or words not in map
                item["visual_description"] = f"a cartoon sticker icon representing the meaning of {word}"
                updated_count += 1

    with open(GRIDS_PATH, "w", encoding="utf-8") as f:
        json.dump(grids, f, ensure_ascii=False, indent=2)

    print(f"Successfully enriched {updated_count} words with visual descriptions in pending_grids.json.")

if __name__ == "__main__":
    main()
