# -*- coding: utf-8 -*-
"""
Generate 1200 high-frequency, authentic colloquial spoken English sentences
aimed at real-life daily communication, with minimal rigid prepositions,
natural spoken idioms/chunks, and daily life expressions.
12 categories x 100 sentences = 1200 total sentences.
"""

import json
import os

categories_data = {
    "日常問候與道別": [
        ("What's up?", "嗨！最近如何？"),
        ("How's it going?", "最近過得怎麼樣？"),
        ("What's new?", "有什麼新鮮事嗎？"),
        ("How are things?", "近況如何？"),
        ("How've you been?", "最近好嗎？"),
        ("Good to see you!", "很高興見到你！"),
        ("Great seeing you again!", "太高興又碰見你了！"),
        ("Long time no see!", "好久不見！"),
        ("Look who it is!", "看看這是誰啊！"),
        ("Morning!", "早啊！"),
        ("Afternoon!", "午安！"),
        ("Evening!", "晚上好！"),
        ("How's your day going?", "你今天過得如何？"),
        ("How was your day?", "你今天過得好嗎？"),
        ("How was your weekend?", "你週末過得怎麼樣？"),
        ("Sleep well?", "昨晚睡得好嗎？"),
        ("Did you sleep okay?", "有睡好嗎？"),
        ("Catch you later!", "待會兒聊！／回頭見！"),
        ("See you around!", "隨時再見！"),
        ("See ya!", "先走囉！掰掰！"),
        ("Talk soon!", "晚點再聊！"),
        ("I gotta run.", "我得先走了。"),
        ("I gotta bounce.", "我該動身閃人囉。"),
        ("I'm outta here.", "我先撤了。"),
        ("I gotta head out.", "我得準備出發了。"),
        ("I should get going.", "我想我差不多該走了。"),
        ("Time for me to go.", "我該出門了。"),
        ("Take care!", "保重喔！／多加小心！"),
        ("Take it easy!", "放輕鬆點！／別太累喔！"),
        ("Have a good one!", "祝你今天愉快！"),
        ("Have a great day!", "祝你有個美好的一天！"),
        ("Have a good night!", "祝你有個美好的夜晚！"),
        ("Have a safe trip!", "路上小心喔！"),
        ("Get home safe!", "安全到家喔！"),
        ("Sleep tight!", "睡個好覺！"),
        ("Sweet dreams!", "祝你好夢！"),
        ("Stay in touch!", "保持聯絡喔！"),
        ("Keep me posted!", "隨時讓我知道後續情況！"),
        ("Let me know when you're free.", "你有空時跟我說一聲。"),
        ("Text me later.", "晚點傳訊息給我。"),
        ("Call me anytime.", "隨時打給我。"),
        ("Welcome!", "歡迎！"),
        ("Welcome back!", "歡迎回來！"),
        ("Make yourself comfortable.", "別客氣，放輕鬆當自己家。"),
        ("Come on in!", "快請進！"),
        ("Thanks for coming over.", "謝謝你特地過來。"),
        ("Thanks for dropping by.", "謝謝你順道過來坐坐。"),
        ("Nice chatting with you.", "跟你聊天很愉快。"),
        ("So glad we ran into each other.", "真高興今天巧遇你。"),
        ("Until next time!", "下次見囉！"),
        ("Peace out!", "走囉！再會！"),
        ("See you tomorrow morning.", "明天一早見。"),
        ("See you next week.", "下週見。"),
        ("Enjoy your weekend!", "週末好好享受！"),
        ("Enjoy your trip!", "旅行玩得開心！"),
        ("Have fun today!", "今天玩得盡興點！"),
        ("Best of luck!", "祝你好運！"),
        ("Fingers crossed!", "為你祈求好運！"),
        ("Say hi to your family.", "幫我向你家人問好。"),
        ("Give everyone my love.", "代我向大家問好。"),
        ("What bring you here?", "是什麼風把你吹來的？"),
        ("Fancy meeting you here!", "真巧，居然在這裡遇到你！"),
        ("What a nice surprise!", "真是個大驚喜！"),
        ("How's your morning been?", "你今天早上一早還好嗎？"),
        ("How's your week going?", "你這週過得怎麼樣？"),
        ("Same as always.", "跟平常一樣老樣子。"),
        ("Can't complain.", "還不錯啦，沒什麼好挑剔的。"),
        ("Pretty good, thanks!", "滿好的，謝謝！"),
        ("Never better!", "好得不能再好了！"),
        ("Just busy as usual.", "就跟平常一樣忙。"),
        ("Hanging in there.", "還撐得住／還過得去。"),
        ("Not bad at all.", "挺不賴的。"),
        ("Could be better.", "還可以更好／普普通通。"),
        ("Could be worse.", "至少還不算太糟。"),
        ("Just the usual stuff.", "就平常那些瑣事。"),
        ("Living the dream!", "過得爽歪歪！／日子充實極了！"),
        ("Surviving!", "還活著／在硬撐！"),
        ("Busy day today.", "今天真是忙碌的一天。"),
        ("Long time, friend!", "老朋友，好久不見！"),
        ("Good seeing your face!", "很高興看到你！"),
        ("Catch up soon, okay?", "我們近期敘舊一下，好嗎？"),
        ("Let's do this again soon.", "我們改天再來約。"),
        ("Don't be a stranger!", "別斷了聯絡喔！／常來玩喔！"),
        ("Look after yourself.", "好好照顧自己。"),
        ("Drive safe!", "開車小心！"),
        ("Fly safe!", "飛行平安！"),
        ("Have a blast!", "玩得痛快點！"),
        ("Take care of business!", "好好處理正事！"),
        ("Catch you in a bit.", "待會兒見。"),
        ("See you in five minutes.", "五分鐘後見。"),
        ("I'm on my way out.", "我正準備出門。"),
        ("Heading out now.", "現在出發囉。"),
        ("Just stepped out.", "剛踏出門。"),
        ("Back in a minute.", "馬上回來。"),
        ("Be right back.", "馬上回來喔。"),
        ("Hold that thought.", "先打住一下，等等繼續聊。"),
        ("Ready to roll?", "準備好出發了嗎？"),
        ("Let's hit the road.", "我們動身出發吧。"),
        ("Time to take off.", "該走人囉。"),
        ("Catch you on the flip side.", "回頭見囉！")
    ],

    "社交閒聊與即時反應": [
        ("Totally!", "完全同意！太贊成了！"),
        ("Exactly!", "沒錯！完全就是這樣！"),
        ("Definitely!", "絕對是這樣！肯定沒錯！"),
        ("Absolutely!", "毫無疑問！完全同意！"),
        ("Fair enough.", "有道理，我可以接受。"),
        ("Makes sense.", "說得通／滿有道理的。"),
        ("That explains it.", "原來是這樣啊，難怪！"),
        ("I hear you.", "我懂你的感受／我明白。"),
        ("Tell me about it!", "這還用說嗎！我太懂了！"),
        ("You can say that again!", "你說得太對了！"),
        ("No way!", "不會吧！怎麼可能！"),
        ("Are you serious?", "你是認真的嗎？"),
        ("You're kidding!", "你在開玩笑吧！"),
        ("For real?", "真的假的啦？"),
        ("I bet!", "我想也是！肯定是這樣！"),
        ("No wonder!", "難怪會這樣！"),
        ("My bad!", "我的錯！抱歉抱歉！"),
        ("No worries!", "別擔心！沒關係啦！"),
        ("No big deal.", "沒什麼大不了的。"),
        ("No biggie!", "小事一樁！別放在心上！"),
        ("Don't sweat it.", "別太緊張啦／小事啦。"),
        ("It happens.", "難免會這樣啦。"),
        ("You're good.", "你沒事啦／沒問題的。"),
        ("All good!", "一切都好／沒問題！"),
        ("I'm down!", "算我一個！我很想去！"),
        ("I'm in!", "我加入！我也要！"),
        ("Count me in!", "算我一份！"),
        ("Same here!", "我也是這樣！"),
        ("Me neither.", "我也沒有／我也不覺得。"),
        ("Good call!", "好決定！你選得好！"),
        ("Nice one!", "幹得好！這招厲害！"),
        ("Way to go!", "做得很棒！太讚了！"),
        ("Good for you!", "真替你高興！"),
        ("Lucky you!", "你真幸運！好羨慕！"),
        ("Must be nice!", "那一定很爽吧！真好！"),
        ("I feel you.", "我能體會你的心情。"),
        ("Go for it!", "放手去做吧！衝了！"),
        ("Why not?", "有何不可呢？試試看啊！"),
        ("Let's do it!", "就這麼辦吧！上吧！"),
        ("Sounds great!", "聽起來太棒了！"),
        ("Sounds like a plan!", "就照這個計畫進行！"),
        ("You nailed it!", "你完全抓到精髓了！做得漂亮！"),
        ("Spot on!", "一針見血！完全正確！"),
        ("Big deal!", "有什麼了不起！"),
        ("Whatever you say.", "隨你怎麼說囉。"),
        ("If you say so.", "既然你都這麼說了。"),
        ("Never mind.", "算了，當我沒說。"),
        ("Forget about it.", "別提了／算了吧。"),
        ("Let it go.", "看開點吧，別糾結了。"),
        ("Keep it up!", "繼續保持喔！"),
        ("Hang on a second.", "等等，稍等一下。"),
        ("Guess what?", "你猜怎麼著？"),
        ("You know what?", "你知道嗎？跟跟你說喔。"),
        ("Here's the thing.", "事情是這樣的。"),
        ("Long story short.", "長話短說。"),
        ("To be honest.", "老實說啦。"),
        ("Frankly speaking.", "坦白說。"),
        ("Not really.", "其實沒有耶／不大算。"),
        ("Not quite.", "不太算／還差一點。"),
        ("Kind of.", "有一點啦／算是吧。"),
        ("Sort of.", "稍微有一點點。"),
        ("Pretty much.", "基本上差不多就是這樣。"),
        ("More or less.", "大概差不多吧。"),
        ("Not a chance!", "門都沒有！絕對不可能！"),
        ("Over my dead body!", "門都沒有！除非我死了！"),
        ("Deal!", "成交！一言為定！"),
        ("You bet!", "那當然！沒問題！"),
        ("Anytime!", "隨時為您效勞！不客氣！"),
        ("My pleasure!", "我的榮幸／很樂意幫忙！"),
        ("Don't mention it.", "別客氣，小事啦。"),
        ("Glad I could help.", "很高興能幫上忙。"),
        ("You're a lifesaver!", "你真是我的救命恩人！"),
        ("I owe you one.", "我欠你一次人情。"),
        ("Much appreciated!", "非常感謝！銘記在心！"),
        ("Thanks a ton!", "超級感謝你！"),
        ("Cheers!", "謝啦！／乾杯！"),
        ("Bummer!", "真可惜！太掃興了！"),
        ("What a pity!", "太可惜了吧！"),
        ("Too bad!", "真遺憾／太糟糕了！"),
        ("That sucks!", "那真的太爛了／真倒楣！"),
        ("What a mess!", "真是一團糟！"),
        ("How weird!", "太奇怪了吧！"),
        ("How funny!", "真搞笑！太逗了！"),
        ("That's hilarious!", "那超好笑的！笑死！"),
        ("That's awesome!", "那太屌了！太酷了！"),
        ("That's wicked!", "那太厲害了吧！"),
        ("That's epic!", "那太傳奇了！超狂！"),
        ("Sweet!", "讚啦！太棒了！"),
        ("Nice job!", "做得好！"),
        ("Proud of you!", "為你感到驕傲！"),
        ("You rock!", "你太強了！太棒了！"),
        ("Keep dreaming!", "慢慢做夢吧你！"),
        ("Don't get smart with me.", "別跟我耍嘴皮子。"),
        ("Cut it out!", "少來這套！別鬧了！"),
        ("Give me a break!", "饒了我吧！別鬧了！"),
        ("Come off it!", "少吹牛了／別胡扯了！"),
        ("Get real!", "清醒點吧！面對現實！"),
        ("Suit yourself.", "隨便你，高興就好。"),
        ("Who cares?", "誰在乎啊？"),
        ("Whatever.", "隨便啦／隨你便。")
    ],

    "餐廳點餐與外帶": [
        ("Table for two, please.", "兩位，謝謝。"),
        ("Can we sit by the window?", "我們可以坐靠窗的位置嗎？"),
        ("Can we sit outside?", "我們可以坐戶外區嗎？"),
        ("Do we seat ourselves?", "是自己找位子坐嗎？"),
        ("Can I see the menu, please?", "可以給我看一下菜單嗎？"),
        ("What do you recommend?", "你們有推薦什麼招牌嗎？"),
        ("What's the special today?", "今天的特餐是什麼？"),
        ("What's your most popular dish?", "你們最受歡迎的餐點是什麼？"),
        ("Is this spicy?", "這個會辣嗎？"),
        ("How spicy is this?", "這道菜有多辣？"),
        ("Make it mild, please.", "請幫我做微辣就好。"),
        ("Not too spicy, please.", "請不要做得太辣。"),
        ("No onions, please.", "不要放洋蔥，謝謝。"),
        ("Hold the ice, please.", "請幫我去冰。"),
        ("Easy ice, please.", "請幫我微冰。"),
        ("No sugar, please.", "請幫我無糖。"),
        ("Extra cheese, please.", "請幫我多加點起司。"),
        ("Dressing on the side, please.", "沙拉醬請另外放旁邊。"),
        ("Sauce on the side, please.", "沾醬請分開裝。"),
        ("Can I get a coffee, please?", "可以給我一杯咖啡嗎？"),
        ("I'll have a latte.", "我要一杯拿鐵。"),
        ("Make that an iced latte.", "幫我改成冰拿鐵。"),
        ("I'll take the burger combo.", "我要漢堡套餐。"),
        ("I'll have the same thing.", "我和他點一樣的。"),
        ("Make that two, please.", "一樣的再來一份／請算兩份。"),
        ("Just water for now, thanks.", "先給我水就好，謝謝。"),
        ("Tap water is fine.", "一般飲用水（自來水）就可以。"),
        ("Sparkling or still?", "氣泡水還是一般水？"),
        ("For here or to go?", "內用還是外帶？"),
        ("To go, please.", "外帶，謝謝。"),
        ("For here, please.", "內用，謝謝。"),
        ("Can I get this wrapped up?", "可以幫我把這個打包嗎？"),
        ("Could we get a to-go box?", "可以給我們一個外帶打包盒嗎？"),
        ("Can I get another fork?", "可以再給我一支叉子嗎？"),
        ("More napkins, please.", "請多給我幾張紙巾。"),
        ("Can I get a refill?", "可以幫我續杯嗎？"),
        ("Is the refill free?", "續杯是免費的嗎？"),
        ("We're ready to order.", "我們準備好可以點餐了。"),
        ("Give us a few more minutes.", "再給我們幾分鐘看一下。"),
        ("Still deciding, thanks.", "我們還在考慮，謝謝。"),
        ("I'll have the steak.", "我要一份牛排。"),
        ("Medium rare, please.", "三分熟／五分熟，謝謝。"),
        ("Well done, please.", "全熟，謝謝。"),
        ("Everything looks delicious!", "每樣看起來都好好吃！"),
        ("This tastes amazing!", "這個太好吃了！味道超棒！"),
        ("It's a bit salty.", "稍微有點鹹。"),
        ("It's a bit cold.", "食物有點涼掉了。"),
        ("Excuse me, this isn't what I ordered.", "不好意思，這好像不是我點的。"),
        ("Did our food get ordered?", "我們的餐點有點到了嗎？"),
        ("How long will it take?", "大概還要等多久？"),
        ("Is our order coming soon?", "我們的餐點快好了嗎？"),
        ("Can we get the check, please?", "麻煩買單結帳，謝謝。"),
        ("Check, please!", "買單，謝謝！"),
        ("Bill, please!", "結帳，謝謝！"),
        ("We'd like to pay separately.", "我們想分開結帳。"),
        ("Can we split the bill?", "我們可以各付各的（分攤）嗎？"),
        ("Together or separate?", "一起算還是分開算？"),
        ("All on one bill, please.", "全部算一張單，謝謝。"),
        ("It's on me today!", "今天這餐我請客！"),
        ("My treat!", "我請客！我買單！"),
        ("Let me get this.", "這頓讓我來付就好。"),
        ("Let's go Dutch.", "我們各付各的吧。"),
        ("Do you take credit cards?", "你們收信用卡嗎？"),
        ("Can I pay with cash?", "我可以付現嗎？"),
        ("Keep the change.", "零錢不用找了。"),
        ("Is service charge included?", "服務費已經包含在裡面了嗎？"),
        ("Where's the restroom?", "請問洗手間在哪裡？"),
        ("Is there outdoor seating?", "有室外座位嗎？"),
        ("Is there a minimum spend?", "店裡有低消限制嗎？"),
        ("Any vegetarian options?", "有素食的餐點選項嗎？"),
        ("I'm allergic to peanuts.", "我對花生過敏。"),
        ("Does this have dairy?", "這個裡面有乳製品成分嗎？"),
        ("Is this gluten-free?", "這是無麩質的嗎？"),
        ("Can I swap the fries for salad?", "我可以把薯條換成沙拉嗎？"),
        ("Can I substitute soup?", "可以換成湯品嗎？"),
        ("Can I get extra sauce?", "可以多給我一點沾醬嗎？"),
        ("Warm water, please.", "請給我溫開水。"),
        ("No ice, please.", "完全去冰，謝謝。"),
        ("Large size, please.", "大杯／大份，謝謝。"),
        ("Regular size is good.", "中杯／正常份量就好。"),
        ("One more beer, please.", "請再來一杯啤酒。"),
        ("Another round, please.", "大家再來一輪！"),
        ("Last call for drinks!", "最後點飲品時間到了！"),
        ("Are you still working on that?", "這盤您還在用嗎？還是可以收了？"),
        ("All done with this plate.", "這盤用完了，可以收走。"),
        ("I'm stuffed!", "我吃得好撐啊！"),
        ("I couldn't eat another bite.", "我一口都吃不下了，太飽了。"),
        ("That hit the spot!", "太好吃了！完全滿足味蕾！"),
        ("Best meal ever!", "吃過最棒的一餐！"),
        ("We loved the food!", "我們很喜歡你們的料理！"),
        ("Compliments to the chef!", "幫我們向主廚致敬！煮得太棒了！"),
        ("Can I see the dessert menu?", "可以看一下甜點菜單嗎？"),
        ("What flavor ice cream do you have?", "你們有什麼口味的冰淇淋？"),
        ("Just black coffee for dessert.", "甜點只要一杯黑咖啡就好。"),
        ("Let's get some dessert.", "我們來點個甜點吧。"),
        ("Can we have two glasses?", "可以給我們兩個杯子嗎？"),
        ("Can I have a straw?", "可以給我一根吸管嗎？"),
        ("Can I have a takeout menu?", "可以給我一張外帶菜單嗎？"),
        ("I'll take the lunch special.", "我要午間特惠套餐。"),
        ("Thanks for the great service!", "謝謝你們優質的服務！")
    ],

    "購物消費與結帳": [
        ("How much is this?", "這個多少錢？"),
        ("How much for both?", "兩個一起算多少錢？"),
        ("Is this on sale?", "這個有特價嗎？"),
        ("Any discounts today?", "今天有任何折扣優惠嗎？"),
        ("Do you have this in small?", "這款有 S 號的嗎？"),
        ("Do you have this in medium?", "這款有 M 號的嗎？"),
        ("Do you have this in large?", "這款有 L 號的嗎？"),
        ("Do you have other colors?", "這件還有其他顏色嗎？"),
        ("Do you have a bigger size?", "有大一點的尺寸嗎？"),
        ("Do you have a smaller size?", "有小一點的尺寸嗎？"),
        ("Where are the fitting rooms?", "更衣室在哪裡？"),
        ("Can I try this on?", "我可以試穿這個嗎？"),
        ("Can I try these on?", "我可以試穿這幾件嗎？"),
        ("It's too small.", "這件太小了。"),
        ("It's too big.", "這件太大了。"),
        ("It's too tight.", "這件太緊了。"),
        ("It's too loose.", "這件太寬鬆了。"),
        ("It fits perfectly!", "尺寸剛剛好！非常合身！"),
        ("How does this look?", "穿起來好看嗎？看起來如何？"),
        ("Looks great on you!", "你穿起來超好看！很適合你！"),
        ("I'll take it!", "這個我要了！買了！"),
        ("I'll pass on this.", "這個我先不要好了。"),
        ("Let me think about it.", "我再考慮看看好了。"),
        ("Just looking, thanks!", "我只是隨便看看，謝謝！"),
        ("Just browsing, thank you.", "我只是隨便逛逛，謝謝。"),
        ("Where can I find shirts?", "襯衫區在哪裡？"),
        ("Where is the checkout?", "結帳櫃台在哪裡？"),
        ("Are you open?", "你們開始營業了嗎？"),
        ("What time do you close?", "你們幾點打烊？"),
        ("Are you in line?", "請問你是在排隊嗎？"),
        ("Is this the end of the line?", "這是隊伍末端嗎？"),
        ("Next, please!", "下一位客人，請！"),
        ("Did you find everything okay?", "商品都有找齊嗎？"),
        ("Can I pay by card?", "我可以刷卡嗎？"),
        ("Do you take Apple Pay?", "你們收 Apple Pay 嗎？"),
        ("Can I tap my card?", "可以直接感應卡片嗎？"),
        ("Cash or card?", "現金還是刷卡？"),
        ("Cash, please.", "付現，謝謝。"),
        ("Card, please.", "刷卡，謝謝。"),
        ("Insert your card here.", "請在這裡插入晶片卡。"),
        ("Tap your phone here.", "請把手機靠在這裡感應。"),
        ("Enter your PIN, please.", "請輸入您的密碼。"),
        ("Sign here, please.", "請在這邊簽名。"),
        ("Do you want a bag?", "你需要購物袋嗎？"),
        ("No bag, thanks.", "不用袋子，謝謝。"),
        ("I brought my own bag.", "我自己有帶購物袋。"),
        ("Can I get a paper bag?", "可以給我紙袋嗎？"),
        ("Here's your receipt.", "這是您的收據發票。"),
        ("Keep the receipt.", "收據留好喔。"),
        ("No receipt needed, thanks.", "不用收據發票，謝謝。"),
        ("Can I get a gift receipt?", "可以給我一張禮品收據（不顯示價格）嗎？"),
        ("Can you gift wrap this?", "可以幫我包裝成禮物嗎？"),
        ("What's the return policy?", "退貨規定是什麼？"),
        ("Can I return this?", "這個可以退貨嗎？"),
        ("Can I exchange this?", "這個可以換貨嗎？"),
        ("I have the receipt.", "我有帶發票收據。"),
        ("It's the wrong size.", "尺寸買錯了。"),
        ("It's damaged.", "這個有破損瑕疵。"),
        ("It doesn't work.", "這個故障不能運作。"),
        ("Can I get a refund?", "我可以申請退款嗎？"),
        ("Store credit is fine.", "換成店內購物折抵金也可以。"),
        ("Is this buy one get one?", "這是買一送一嗎？"),
        ("Is this fifty percent off?", "這是打五折嗎？"),
        ("What's the total?", "全部一共多少錢？"),
        ("What's the damage?", "這下一共要噴多少錢？（口語結帳）"),
        ("That's twenty dollars total.", "總共是二十元。"),
        ("Here is twenty dollars.", "這裡給您二十元。"),
        ("Here's your change.", "這是找給您的零錢。"),
        ("Do you have a rewards card?", "您有會員集點卡嗎？"),
        ("Any membership points?", "有會員點數可以折抵嗎？"),
        ("Can I sign up for free?", "可以免費加入會員嗎？"),
        ("Is this tax included?", "這有含稅金嗎？"),
        ("Plus tax, right?", "還要外加稅金，對吧？"),
        ("Do you price match?", "你們有買貴退差價（比價保證）嗎？"),
        ("Is this the best price?", "這已經是最划算的價格了嗎？"),
        ("Can you do ten dollars?", "算十元可以嗎？（殺價口語）"),
        ("Can you give me a deal?", "可以算我便宜一點嗎？"),
        ("It's a steal!", "太便宜了！買到賺到！"),
        ("That's a rip-off!", "那根本是敲竹槓！太貴了！"),
        ("Way too expensive.", "太貴了啦。"),
        ("Pretty cheap!", "挺便宜的！"),
        ("Good quality!", "品質很棒！"),
        ("Feels really soft.", "摸起來很柔軟舒服。"),
        ("Made of real leather?", "這是真皮做的嗎？"),
        ("Is it waterproof?", "這個防水嗎？"),
        ("Is this dishwasher safe?", "這個可以放洗碗機洗嗎？"),
        ("Is this in stock?", "這個有現貨嗎？"),
        ("Out of stock right now.", "目前缺貨中喔。"),
        ("When will it come in?", "什麼時候會進貨？"),
        ("Can you hold it for me?", "可以幫我保留嗎？"),
        ("I'll take both.", "兩個我都要了。"),
        ("Just this one, please.", "只要買這一個就好，謝謝。"),
        ("Have a great day!", "祝您有美好的一天！"),
        ("Thanks for your help!", "謝謝你的幫忙！"),
        ("Have a good one!", "祝你順心！"),
        ("See you next time!", "下次見！"),
        ("Come back soon!", "歡迎下次再來！"),
        ("Can you check the back?", "可以幫我去庫房找找看嗎？"),
        ("All set!", "全部弄好結清了！"),
        ("You're all set to go!", "您都結帳完成可以走囉！")
    ],

    "外出交通與問路": [
        ("Where's the nearest station?", "最近的車站站在哪裡？"),
        ("Where's the subway station?", "地鐵捷運站在哪？"),
        ("Where's the bus stop?", "公車站牌在哪裡？"),
        ("Which bus goes downtown?", "哪一班公車有開往市中心？"),
        ("Does this bus go to the airport?", "這班公車有到機場嗎？"),
        ("Is this the right train?", "這班火車坐對了嗎？"),
        ("Which platform for the airport?", "去機場要到哪個月台？"),
        ("Platform three, right over there.", "三號月台，就在那邊。"),
        ("When is the next train?", "下一班火車什麼時候來？"),
        ("Is the train on time?", "火車有準點嗎？"),
        ("Running ten minutes late.", "誤點了十分鐘。"),
        ("Where can I buy a ticket?", "哪裡可以買車票？"),
        ("One ticket downtown, please.", "買一張到市區的票，謝謝。"),
        ("Round trip or one way?", "來回還是單程？"),
        ("One way, please.", "單程，謝謝。"),
        ("Round trip, please.", "來回票，謝謝。"),
        ("Can I tap with my phone?", "可以直接用手機逼卡感應嗎？"),
        ("Where's the exit?", "出口在哪個方向？"),
        ("Exit B is right upstairs.", "B 出口直接往樓上走就是了。"),
        ("How do I get to the museum?", "去博物館要怎麼走？"),
        ("Go straight ahead.", "一直往前直走。"),
        ("Turn left at the light.", "在紅綠燈路口左轉。"),
        ("Turn right at the corner.", "在轉角處右轉。"),
        ("It's on your left.", "它就在你的左手邊。"),
        ("It's on your right.", "它就在你的右手邊。"),
        ("You can't miss it!", "你一定找得到的！目標很明顯！"),
        ("Is it far from here?", "離這裡很遠嗎？"),
        ("Is it walkable?", "走路走得到嗎？"),
        ("About ten minutes on foot.", "走路大概十分鐘。"),
        ("Just around the corner.", "就在轉角過去而已。"),
        ("Right across the street.", "就在正對面馬路。"),
        ("Next to the bank.", "就在銀行隔壁。"),
        ("Behind the supermarket.", "在超市後方。"),
        ("I'm lost.", "我迷路了。"),
        ("Can you show me on the map?", "可以在地圖上指給我看嗎？"),
        ("Follow me, I'll show you.", "跟我走吧，我帶你去。"),
        ("Taxi!", "計程車！"),
        ("Are you available?", "請問有載客嗎？／空車嗎？"),
        ("Hop in!", "快上車吧！"),
        ("Where to?", "要去哪裡？"),
        ("Take me to this address, please.", "請載我到這個地址，謝謝。"),
        ("Take me to the airport, please.", "請載我到機場，謝謝。"),
        ("How long will it take?", "大概需要多久時間？"),
        ("About twenty minutes.", "大概二十分鐘。"),
        ("I'm in a rush.", "我趕時間。"),
        ("Step on it, please.", "麻煩開快一點（油門踩下去）。"),
        ("Please slow down.", "請開慢一點。"),
        ("Drop me off here, please.", "請讓我在這裡下車，謝謝。"),
        ("Drop me off at the corner.", "請在轉角放我下車。"),
        ("Pull over here, please.", "請靠邊停這裡就好。"),
        ("Keep the meter running.", "請不要跳錶暫停，維持跳錶計費。"),
        ("How much is on the meter?", "跳錶金額是多少？"),
        ("Stuck in traffic.", "塞在車陣中。"),
        ("Traffic is awful today.", "今天路況太差了，塞爆。"),
        ("Bumper to bumper traffic.", "車子塞得動彈不得。"),
        ("Take the highway.", "走高速公路／快速道路。"),
        ("Any toll fees?", "有過路費嗎？"),
        ("Can I open the window?", "我可以開窗戶嗎？"),
        ("Can you turn on the AC?", "可以開一下冷氣空調嗎？"),
        ("Can you turn down the music?", "可以把音樂關小聲點嗎？"),
        ("Fasten your seatbelt.", "請繫上安全帶。"),
        ("Watch your step getting out.", "下車時注意腳步。"),
        ("Mind the gap.", "小心月台間隙。"),
        ("Stand clear of the doors.", "請遠離車門／請勿靠近車門。"),
        ("Next stop is Main Street.", "下一站是主街。"),
        ("This is our stop.", "我們這站要下車了。"),
        ("Let people off first.", "先讓車上的人下來。"),
        ("Move down the car, please.", "請往車廂裡面走。"),
        ("Excuse me, getting off here.", "不好意思，借過一下，我要下車。"),
        ("Can you call me an Uber?", "可以幫我叫台 Uber 嗎？"),
        ("My ride is here.", "來接我的車到了。"),
        ("I'm tracking your ride.", "我正在追蹤你的車輛位置。"),
        ("Driver is two minutes away.", "司機還有兩分鐘抵達。"),
        ("License plate matches.", "車牌號碼對得起來。"),
        ("Where can I park?", "哪裡可以停車？"),
        ("Is parking free here?", "這裡停車免費嗎？"),
        ("Pay for parking over there.", "去那邊繳停車費。"),
        ("Take a parking ticket.", "抽一張停車票卡。"),
        ("Fill it up, please.", "請幫我加滿油。"),
        ("Regular unleaded, please.", "加 95 / 92 無鉛汽油，謝謝。"),
        ("Check the tires, please.", "請幫我檢查胎壓。"),
        ("Clean the windshield, please.", "麻煩幫忙擦一下擋風玻璃。"),
        ("I have a flat tire.", "我爆胎了。"),
        ("My battery is dead.", "我電瓶沒電了。"),
        ("Need a jump start.", "需要接電過電發動。"),
        ("Call roadside assistance.", "打給道路救援。"),
        ("Call a tow truck.", "叫拖吊車來。"),
        ("Gas tank is empty.", "油箱見底沒油了。"),
        ("Running on fumes.", "油快燒光了，在撐最後一哩。"),
        ("Pedestrian crossing ahead.", "前方是行人穿越道。"),
        ("Green light, let's go.", "綠燈了，快走吧。"),
        ("Red light, stop here.", "紅燈，停這裡。"),
        ("Watch out for bikes.", "注意旁邊的腳踏車。"),
        ("Yield to pedestrians.", "禮讓行人優先通行。"),
        ("One-way street.", "單行道。"),
        ("No parking zone.", "禁止停車區域。"),
        ("Tow-away zone.", "拖吊專用區。"),
        ("Speed limit is fifty.", "速限是五十。"),
        ("Slow down around the bend.", "過彎時請減速慢行。"),
        ("Safe travels!", "祝你旅途平安！")
    ],

    "居家生活與日常": [
        ("I'll grab the door.", "我去開門。"),
        ("Someone's knocking.", "有人在敲門。"),
        ("The doorbell is ringing.", "電鈴在響。"),
        ("Lock the front door.", "把大門鎖好。"),
        ("Did you lock up?", "你有鎖好門窗嗎？"),
        ("Where are my keys?", "我的鑰匙跑去哪了？"),
        ("Found my keys!", "找到我的鑰匙了！"),
        ("Can you take out the trash?", "你可以幫忙拿垃圾去倒嗎？"),
        ("Today is recycling day.", "今天是資源回收日。"),
        ("We're out of milk.", "家裡的牛奶喝光了。"),
        ("We're out of eggs.", "家裡沒有雞蛋了。"),
        ("Put it on the grocery list.", "把它寫進採買清單裡。"),
        ("I'm doing the dishes.", "我正在洗碗。"),
        ("Can you load the dishwasher?", "你能把碗盤放進洗碗機嗎？"),
        ("Can you unload the dishwasher?", "你能把洗碗機裡的碗盤拿出來收好嗎？"),
        ("I'll clean the kitchen.", "我去清理廚房。"),
        ("Wipe down the counter, please.", "麻煩把流理台擦乾淨。"),
        ("Sweep the floor, please.", "幫忙掃一下地板。"),
        ("Mop the floor, please.", "幫忙拖一下地板。"),
        ("Vacuum the living room.", "用吸塵器吸一下客廳。"),
        ("Do a load of laundry.", "洗一桶衣服。"),
        ("Hang up the clothes.", "把衣服晾起來。"),
        ("Fold the laundry.", "把洗好的衣服折好。"),
        ("Put away your clothes.", "把你的衣服收進衣櫃裡。"),
        ("Iron this shirt, please.", "幫我把這件襯衫燙一下。"),
        ("Make your bed.", "把你自己的床鋪整理好。"),
        ("Change the sheets.", "把床單換洗一下。"),
        ("Turn off the lights.", "把燈關掉。"),
        ("Leave the light on.", "讓燈開著沒關係。"),
        ("Turn down the TV, please.", "請把電視聲音關小一點。"),
        ("Turn up the volume.", "把音量調大一點。"),
        ("Where's the remote?", "遙控器放在哪裡？"),
        ("Pass me the remote.", "把遙控器遞給我一下。"),
        ("What's on TV tonight?", "今晚電視有播什麼節目？"),
        ("Let's watch a movie.", "我們來看部電影吧。"),
        ("Pick a show.", "挑個影集或節目來看。"),
        ("Pause it real quick.", "先暫停一下下。"),
        ("Play it again.", "再重播一次。"),
        ("Time for bed.", "該上床睡覺了。"),
        ("I'm hit the sack.", "我要去躺平睡覺了。"),
        ("Time to crash.", "該躺平昏睡了。"),
        ("Set your alarm.", "記得設你的鬧鐘。"),
        ("My alarm didn't go off.", "我的鬧鐘早上沒響。"),
        ("I overslept this morning.", "我今天早上睡過頭了。"),
        ("Wake up, sleepyhead!", "起床囉，小懶豬！"),
        ("Five more minutes, please.", "拜託再讓我多睡五分鐘。"),
        ("Breakfast is ready!", "早餐做好了！"),
        ("Dinner is served!", "晚餐開動囉！"),
        ("Smells great in here!", "這裡聞起來好香喔！"),
        ("What's for dinner?", "今天晚餐吃什麼？"),
        ("I'll make some eggs.", "我去煎幾顆蛋。"),
        ("Make some coffee, please.", "幫忙泡點咖啡，謝謝。"),
        ("Warm it up in the microwave.", "用微波爐熱一下。"),
        ("Put it in the fridge.", "把它放進冰箱裡。"),
        ("Put it in the freezer.", "把它放進冷凍庫。"),
        ("It's expired.", "這個已經過期了。"),
        ("Throw it away.", "把它丟掉吧。"),
        ("Keep the leftovers.", "把剩菜留起來。"),
        ("Save it for tomorrow.", "留到明天吃。"),
        ("Water the plants, please.", "麻煩幫植物澆個水。"),
        ("Feed the cat, please.", "幫忙餵一下貓咪。"),
        ("Walk the dog, please.", "帶狗狗去散步。"),
        ("Close the blinds.", "把百葉窗拉上。"),
        ("Open the curtains.", "把窗簾拉開。"),
        ("Let some fresh air in.", "讓新鮮空氣流通進來。"),
        ("It's chilly inside.", "屋子裡有點涼意。"),
        ("Turn on the heater.", "把暖氣打開。"),
        ("Turn on the fan.", "把電風扇打開。"),
        ("The AC is too cold.", "冷氣吹得太冷了。"),
        ("Grab a blanket.", "去拿件毛毯蓋著。"),
        ("Cozy night in.", "今晚窩在家裡真舒服。"),
        ("I love staying home.", "我超喜歡待在家裡的。"),
        ("Home sweet home!", "回到溫暖的家真好！"),
        ("House is a mess.", "家裡亂成一團。"),
        ("Time for spring cleaning.", "該來大掃除了。"),
        ("Tidy up your room.", "把你房間整理整齊。"),
        ("Put things back in place.", "東西用完放回原位。"),
        ("Take a quick shower.", "去沖個快澡。"),
        ("Brush your teeth.", "去刷牙。"),
        ("Wash your face.", "去洗臉。"),
        ("Comb your hair.", "梳一下頭髮。"),
        ("Put on some clothes.", "換上外出衣服。"),
        ("Grab your coat.", "拿上你的外套。"),
        ("Don't forget your umbrella.", "別忘了帶雨傘。"),
        ("It looks like rain.", "看起來好像快下雨了。"),
        ("Phone is on the charger.", "手機正插著充電。"),
        ("Battery is at ten percent.", "電量只剩百分之十了。"),
        ("Pass me the charger.", "充電線遞給我一下。"),
        ("Wi-Fi is down.", "Wi-Fi 網路斷掉了。"),
        ("Restart the router.", "把路由器重開機一下。"),
        ("Connection is slow.", "網路連線速度好慢。"),
        ("Everything is working now.", "一切都恢復正常運作了。"),
        ("Good job cleaning up!", "整理得很乾淨，做得好！"),
        ("Let's relax now.", "現在可以好好放鬆了。"),
        ("Time to unwind.", "該好好放鬆舒壓了。"),
        ("Read a book in bed.", "躺在床上看本書。"),
        ("Night night!", "晚安囉！"),
        ("Sleep well tonight.", "今晚好好睡一覺。"),
        ("See you in the morning.", "明早見囉。"),
        ("Everything is clean now.", "現在每樣東西都弄得乾乾淨淨了。")
    ],

    "朋友邀約與聚會": [
        ("Are you free tonight?", "你今晚有空嗎？"),
        ("Are you free this weekend?", "你這週末有空嗎？"),
        ("Got any plans later?", "等等有任何安排或計畫嗎？"),
        ("What are you up to tonight?", "你今晚打算做什麼？"),
        ("Wanna grab a coffee?", "想一起去喝杯咖啡嗎？"),
        ("Wanna grab lunch?", "想不想一起去吃個午餐？"),
        ("Wanna grab a bite?", "想一起去吃點東西墊墊肚子嗎？"),
        ("Wanna grab drinks later?", "待會兒想一起去喝兩杯嗎？"),
        ("Let's get dinner tonight.", "今晚我們一起吃晚餐吧。"),
        ("Let's hang out this weekend.", "這週末我們一起出來聚聚吧。"),
        ("Let's catch up soon.", "我們改天找時間好好敘敘舊。"),
        ("We should totally meet up.", "我們真的該找機會碰個面了。"),
        ("Count me in!", "算我一份！我一定去！"),
        ("I'm so in!", "我超想去！加我一個！"),
        ("I'm totally down!", "我完全贊成！算我一個！"),
        ("Sounds like a blast!", "聽起來一定超好玩的！"),
        ("Sounds fun, let's go!", "聽起來很有趣，走吧！"),
        ("I'd love to come!", "我很想去！"),
        ("What time works for you?", "你什麼時間比較方便？"),
        ("When are you free?", "你什麼時候有空？"),
        ("Where should we meet?", "我們要在哪裡碰面集合？"),
        ("Meet me at the cafe.", "在咖啡店跟我碰面。"),
        ("Meet you in the lobby.", "在大廳跟你碰面。"),
        ("Meet you outside.", "在外面跟你碰頭。"),
        ("See you there at seven.", "七點在那邊見。"),
        ("I'll pick you up.", "我去開車接你。"),
        ("Pick me up at six.", "六點來接我。"),
        ("Can you give me a ride?", "你能順路載我一程嗎？"),
        ("I'll meet you there directly.", "我直接去現場跟你們會合。"),
        ("I might be five minutes late.", "我可能會遲到個五分鐘。"),
        ("On my way right now!", "我現在正趕過去途中！"),
        ("Just parked my car.", "我剛停好車。"),
        ("I'm right outside.", "我人就在正門外了。"),
        ("I'm inside already.", "我已經在裡面了。"),
        ("Saved you a seat.", "幫你留好位子了。"),
        ("I can't make it today.", "我今天去不了了。"),
        ("Something came up.", "臨時突然有事發生。"),
        ("I have other plans.", "我另外已經有約了。"),
        ("I'm tied up today.", "我今天抽不開身。"),
        ("Rain check, please?", "這次先改期改天好嗎？"),
        ("Can we take a rain check?", "我們可以下次再約嗎？"),
        ("Next time for sure!", "下次一定到！"),
        ("No worries, another time!", "沒關係，下次再約！"),
        ("Let me check my schedule.", "我查一下我的行事曆。"),
        ("I'll let you know tomorrow.", "我明天跟你確認。"),
        ("Up to you!", "隨你決定！由你作主！"),
        ("Whatever you want.", "你想怎樣都行。"),
        ("You decide.", "你來決定就好。"),
        ("I'm easy.", "我都隨意，很好配合。"),
        ("Any place is fine with me.", "去哪裡我都OK。"),
        ("You pick the spot.", "你來選地點。"),
        ("Have you tried that new place?", "你有去過那家新開的店嗎？"),
        ("Let's try something new.", "我們來嘗試點新花樣。"),
        ("Let's stick to our usual spot.", "我們還是去平常那家老地方吧。"),
        ("Who else is coming?", "還有誰會去？"),
        ("Just the two of us.", "就我們兩個人。"),
        ("The whole crew will be there.", "整群好朋友都會到。"),
        ("Bring a friend along!", "帶個朋友一起來啊！"),
        ("Feel free to bring someone.", "歡迎隨意帶人一起來。"),
        ("The more the merrier!", "人越多越熱鬧！"),
        ("Party starts at eight.", "派對八點開始。"),
        ("Dress casual.", "穿著休閒便服就可以了。"),
        ("BYOB, bring your own beer.", "自己帶酒水飲料喔。"),
        ("I'll bring some snacks.", "我會帶點零食點心過去。"),
        ("Thanks for having us!", "謝謝你的熱情招待！"),
        ("Great party tonight!", "今晚的派對太讚了！"),
        ("We had so much fun!", "我們玩得太開心了！"),
        ("Time flies when you're having fun!", "歡樂時光總是過得特別快！"),
        ("I had a great time.", "我玩得很開心。"),
        ("Thanks for organizing this!", "謝謝你主辦籌劃這次聚會！"),
        ("We gotta do this more often.", "我們真的要常常這樣聚聚。"),
        ("Let's make this a weekly thing.", "我們把它變成每週固定聚會吧。"),
        ("I'm exhausted but happy.", "雖然很累但心情超好。"),
        ("Heading home now.", "現在準備回家囉。"),
        ("Text me when you get back.", "回到家傳個訊息給我喔。"),
        ("Made it home safe!", "我平安到家了！"),
        ("Thanks for the ride home!", "謝謝你開車送我回家！"),
        ("Sleep well after all that fun.", "玩了一整天好好睡一覺吧。"),
        ("See you guys next time!", "大家下次見囉！"),
        ("Can't wait for our next trip!", "等不及我們下一次出遊了！"),
        ("Let's plan a beach trip.", "我們來規畫去海邊玩吧。"),
        ("Are you into board games?", "你喜歡玩桌遊嗎？"),
        ("Let's have a game night.", "我們來辦個桌遊遊戲之夜吧。"),
        ("Let's have a movie night.", "我們來辦個電影之夜。"),
        ("I'll make the popcorn.", "我來爆爆米花。"),
        ("Grab some ice cream on the way.", "路上順便買個冰淇淋。"),
        ("Don't be late!", "別遲到喔！"),
        ("I'm running on time.", "我時間抓得很準沒遲到。"),
        ("Traffic was crazy.", "剛剛路上塞瘋了。"),
        ("Glad you could make it!", "很高興你能趕得及來！"),
        ("So good seeing everyone!", "能看到大家聚在一起真好！"),
        ("Cheers to the weekend!", "為美好的週末乾杯！"),
        ("Cheers to friendship!", "為我們的友誼乾杯！"),
        ("Bottoms up!", "乾杯！喝光它！"),
        ("One more drink won't hurt.", "再喝一杯沒事的啦。"),
        ("I'm calling it a night.", "我今天喝到／玩到這就好，該退場了。"),
        ("Time for me to head out.", "我差不多該先走囉。"),
        ("Don't leave yet!", "別這麼早走嘛！"),
        ("Stay for one more song!", "再留下來聽一首歌啦！"),
        ("Catch you guys soon!", "各位改天見囉！")
    ],

    "情緒表達與安慰": [
        ("I'm swamped.", "我快被事情淹沒了／忙得不可開交。"),
        ("I'm so stressed out.", "我壓力真的超級大。"),
        ("I'm burned out.", "我精疲力竭、快要燃燒殆盡了。"),
        ("I need a break.", "我需要好好喘口氣休息一下。"),
        ("I'm losing my mind.", "我快被逼瘋了。"),
        ("I can't take this anymore.", "我快受不了這一切了。"),
        ("Everything is going wrong.", "每件事都不順遂。"),
        ("Nothing is going my way.", "沒有一件事情照著我想的走。"),
        ("Hang in there!", "撐住！堅持下去！"),
        ("Stay strong!", "要堅強喔！加油！"),
        ("You got this!", "你沒問題的！你可以辦到！"),
        ("I believe in you.", "我相信你的實力。"),
        ("Don't give up now.", "千萬別在現在放棄。"),
        ("Keep your chin up!", "抬起頭振作起來！別灰心！"),
        ("Cheer up!", "開心點！振作起來！"),
        ("Things will get better.", "情況一定會好轉的。"),
        ("Tomorrow is a fresh start.", "明天又是全新的開始。"),
        ("Every cloud has a silver lining.", "黑暗中總有一線光明／否極泰來。"),
        ("It's not the end of the world.", "這又不是世界末日，別太難過。"),
        ("Don't beat yourself up.", "別太自責了／別對自己太苛刻。"),
        ("You did your best.", "你已經盡了全力了。"),
        ("That's all that matters.", "盡力了才是最重要的。"),
        ("I'm always here for you.", "我隨時都在這裡陪著你。"),
        ("You can lean on me.", "你可以依靠我。"),
        ("Cry it out if you need to.", "想哭就大聲哭出來吧。"),
        ("Let it all out.", "把委屈都發洩出來吧。"),
        ("Take a deep breath.", "深呼吸一下。"),
        ("One step at a time.", "一步一步慢慢來。"),
        ("Don't rush yourself.", "別給自己太大時間壓力。"),
        ("Give it some time.", "給它一點時間沉澱。"),
        ("Time heals all wounds.", "時間會撫平所有傷痛的。"),
        ("I'm so sorry you're going through this.", "看到你經歷這些，我真的很心疼。"),
        ("That must be really tough.", "那一定非常不好受。"),
        ("I can imagine how hard it is.", "我完全能想像那有多不容易。"),
        ("Thanks for being there for me.", "謝謝你一直陪在我身邊。"),
        ("That means the world to me.", "這對我來說意義無比重大。"),
        ("I feel so much better now.", "我現在心情好多了。"),
        ("Thanks for listening to me.", "謝謝你願意聽我傾訴。"),
        ("I needed to hear that.", "我正好需要聽你這句話。"),
        ("You made my day!", "你讓我今天整天都變美好了！"),
        ("I'm so thrilled!", "我太興奮了！超開心的！"),
        ("I'm over the moon!", "我欣喜若狂！開心到飛上天！"),
        ("On cloud nine today!", "今天心情好到像在雲端飄！"),
        ("Couldn't be happier!", "幸福得不能再幸福了！"),
        ("Best day ever!", "最棒的一天！"),
        ("I'm in such a good mood.", "我今天心情超好。"),
        ("Good vibes only!", "只要正能量！"),
        ("That put a smile on my face.", "那讓我臉上露出了笑容。"),
        ("I feel so relieved.", "我總算鬆了一口氣。"),
        ("What a relief!", "真是鬆了一大口氣！"),
        ("A weight off my chest.", "心頭的大石頭終於放下了。"),
        ("I was so nervous.", "我剛才超級緊張的。"),
        ("I had butterflies in my stomach.", "我剛剛心裡七上八下緊張極了。"),
        ("My hands were shaking.", "我的雙手剛剛都在發抖。"),
        ("Glad that's over with.", "真慶幸那件事情終於結束了。"),
        ("I'm so annoyed.", "我真的覺得很煩很惱火。"),
        ("It drives me crazy!", "那真的快把我逼瘋了！"),
        ("It gets on my nerves.", "那一直刺激踩到我的神經底線。"),
        ("I'm fed up with this.", "我真的受夠這件事了。"),
        ("I've had enough.", "我忍無可忍了。"),
        ("Calm down, please.", "請冷靜下來。"),
        ("Take it easy.", "放寬心，別太激動。"),
        ("Don't lose your temper.", "別發脾氣動怒。"),
        ("Count to ten.", "在心裡數到十冷靜一下。"),
        ("Sleep on it.", "先睡一覺明天再說。"),
        ("You'll feel better in the morning.", "明早起來你心情就會好點了。"),
        ("I'm feeling down today.", "我今天心情有點低落鬱悶。"),
        ("Just having an off day.", "只是今天狀態稍微不太對而已。"),
        ("We all have bad days.", "每個人都會有不順遂的日子。"),
        ("Don't let it ruin your day.", "別讓這件事毀了你整天的心情。"),
        ("Look on the bright side!", "往好處想嘛！"),
        ("It could have been worse.", "情況本來可能會更糟的。"),
        ("Count your blessings.", "多想想自己擁有的美好人事物。"),
        ("I'm proud of how you handled that.", "我很欣賞你處理那件事的方式。"),
        ("You showed a lot of courage.", "你展現了無比的勇氣。"),
        ("You're stronger than you think.", "你比你自己想像的還要堅強。"),
        ("Never doubt yourself.", "永遠不要懷疑自己的能力。"),
        ("Trust your gut.", "相信你的直覺。"),
        ("Everything happens for a reason.", "一切事情的發生都有它的原因安排。"),
        ("Better days are coming.", "更美好的日子就在前方了。"),
        ("I've got your back.", "我會挺你到底的。"),
        ("We're in this together.", "我們共同面對、同在一艘船上。"),
        ("You're not alone.", "你絕不是孤單一人。"),
        ("Call me if you need anything.", "有任何需要隨時打給我。"),
        ("Just wanted to check on you.", "只是想關心一下你過得好不好。"),
        ("Thinking of you!", "心裡惦記著你！關心你！"),
        ("Sending you hugs!", "給你大大的擁抱！"),
        ("Sending good vibes your way!", "把滿滿的正能量傳送給你！"),
        ("Take all the time you need.", "你需要多少時間就拿去，別急。"),
        ("No pressure at all.", "完全沒有壓力的，放輕鬆。"),
        ("I understand completely.", "我完全理解。"),
        ("It's okay not to be okay.", "暫時感到沮喪難過也是沒關係的。"),
        ("Be kind to yourself.", "對自己好一點，別太嚴苛。"),
        ("Treat yourself today.", "今天好好犒賞一下自己吧。"),
        ("Go get some rest.", "快去好好休息吧。"),
        ("You deserve a treat.", "你值得好好享受一下。"),
        ("Tomorrow is another day.", "明天又是新的一天。"),
        ("Keep your head high.", "昂首闊步面對吧。"),
        ("Love ya, buddy!", "愛你喔，好兄弟／好閨蜜！"),
        ("You're doing amazing.", "你真的做得太棒了。")
    ],

    "意見看法與簡短回應": [
        ("Sounds good!", "聽起來很不錯！"),
        ("Sounds like a good idea.", "聽起來是個好點子。"),
        ("I'm with you on that.", "在那一點上我和你站在同一陣線。"),
        ("I couldn't agree more.", "我完全贊同，不能同意更多了。"),
        ("You took the words right out of my mouth.", "你把我想說的話都說出來了。"),
        ("I was just about to say that.", "我剛好正準備要那樣說呢。"),
        ("Same here.", "我也是這樣想。"),
        ("I agree one hundred percent.", "我百分之百同意。"),
        ("Point taken.", "你說的這點我聽進去了。"),
        ("Good point.", "說得好／這點很有道理。"),
        ("That makes sense.", "那樣很合理說得通。"),
        ("Fair point.", "合理的觀點。"),
        ("I see what you mean.", "我明白你的意思了。"),
        ("I see your point.", "我理解你的論點出發點。"),
        ("I'm not so sure about that.", "我對這點不太確定。"),
        ("I doubt it.", "我很懷疑會是那樣。"),
        ("I don't think so.", "我不這麼認為。"),
        ("Not necessarily.", "那倒也未必如此。"),
        ("That's not always true.", "那可不一定總是對的。"),
        ("I see it differently.", "我的看法跟你不太一樣。"),
        ("Let's agree to disagree.", "我們各自保留自己的看法吧。"),
        ("To each their own.", "青菜蘿蔔各有所好，每個人不同。"),
        ("Whatever floats your boat.", "只要你喜歡高興就好。"),
        ("If you say so.", "既然你堅持這樣說的話。"),
        ("I don't care.", "我不在乎。"),
        ("It doesn't matter to me.", "這對我來說都沒差。"),
        ("Either way is fine.", "兩種方式都可以。"),
        ("Whatever works.", "只要行得通都好。"),
        ("Whatever you prefer.", "看你比較喜歡哪種。"),
        ("It's totally your call.", "完全由你做決定。"),
        ("I'm fine with whatever.", "我怎樣都可以配合。"),
        ("I'm flexible.", "我的時間和安排很彈性。"),
        ("Not my cup of tea.", "那不是我喜歡的類型／我不太感興趣。"),
        ("Not really a fan.", "我其實不是很熱衷那個。"),
        ("Hard pass for me.", "我直接果斷拒絕／我先不要。"),
        ("I'll pass on that one.", "那項我就先跳過不跟了。"),
        ("No way in hell.", "絕無可能！休想！"),
        ("Don't count on it.", "別指望那件事會發生。"),
        ("Fat chance!", "機會渺茫！門都沒有！"),
        ("As if!", "哪可能！才怪！"),
        ("I have no clue.", "我完全毫無頭緒。"),
        ("Beats me!", "考倒我了！我哪知道！"),
        ("Your guess is as good as mine.", "我跟你一樣一無所知。"),
        ("Who knows?", "誰知道呢？"),
        ("Time will tell.", "時間會給出答案的。"),
        ("We'll see.", "我們走著瞧／到時再看吧。"),
        ("Let's wait and see.", "我們先靜觀其變。"),
        ("It depends.", "這要看情況而定。"),
        ("Depends on the weather.", "看天氣狀況而定。"),
        ("Depends on the price.", "看價格多少而定。"),
        ("That works for me.", "那樣的安排對我很合適。"),
        ("Works like a charm!", "效果奇好無比！靈驗極了！"),
        ("That's a deal breaker.", "那是無法妥協的破局點。"),
        ("No brainer!", "這根本不用思考（顯而易見的好選擇）！"),
        ("Easy decision.", "輕而易舉的決定。"),
        ("Tough call.", "這真的很難下決定。"),
        ("I'm torn between the two.", "我在這兩者之間猶豫不決。"),
        ("I'm on the fence.", "我還在觀望猶豫、舉棋不定。"),
        ("I'm leaning towards yes.", "我目前比較傾向答應同意。"),
        ("Let me sleep on it.", "讓我深思熟慮考慮一晚。"),
        ("I changed my mind.", "我改變心意了。"),
        ("Second thoughts.", "我又有了第二種想法／有些猶豫。"),
        ("Stick to the plan.", "堅持原定計畫不要改。"),
        ("Back to square one.", "又回到最初的原點了。"),
        ("Start from scratch.", "從零開始從頭來過。"),
        ("In my opinion.", "依我個人的看法。"),
        ("From my perspective.", "從我的觀點來看。"),
        ("As far as I know.", "就我所知。"),
        ("If I'm not mistaken.", "如果我沒弄錯的話。"),
        ("Correct me if I'm wrong.", "如果我有說錯請糾正我。"),
        ("Off the top of my head.", "不假思索憑直覺來說。"),
        ("Don't quote me on this.", "這只是我個人印象，別當作官方說法。"),
        ("Take it with a grain of salt.", "聽聽就好，持保留態度。"),
        ("For what it's worth.", "無論是否有價值，姑且說說。"),
        ("Just my two cents.", "純粹是我個人的淺見。"),
        ("No offense taken.", "我沒介意，沒放在心上。"),
        ("No offense, but...", "無意冒犯，但..."),
        ("Don't take it personally.", "別針對個人對號入座。"),
        ("Fair is fair.", "公道話還是要講／公平就是公平。"),
        ("Give credit where it's due.", "該給肯定時就要給予肯定。"),
        ("That's beside the point.", "那根本偏離重點了。"),
        ("You're missing the point.", "你沒抓到核心重點。"),
        ("Get to the point.", "請講重點。"),
        ("Cut to the chase.", "直接切入正題吧。"),
        ("Keep it simple.", "簡單明瞭就好。"),
        ("Let's be real here.", "我們現實一點面對吧。"),
        ("Truth hurts.", "忠言逆耳／事實往往殘酷。"),
        ("Face the music.", "勇敢面對現實和後果吧。"),
        ("It is what it is.", "事情就是這樣了，只能接受。"),
        ("What's done is done.", "做了就做了，覆水難收。"),
        ("No use crying over spilled milk.", "事情發生了，哭也沒有用。"),
        ("Live and learn.", "吸取教訓，增長見識。"),
        ("Better late than never.", "遲做總比不做好。"),
        ("Practice makes perfect.", "熟能生巧。"),
        ("Easier said than done.", "說得容易做起來難。"),
        ("Actions speak louder than words.", "行動勝於空談。"),
        ("So far so good.", "到目前為止一切都很順利。"),
        ("Touch wood!", "敲敲木頭！（求好運避免霉運）"),
        ("Cross my heart!", "我發誓說的是真話！"),
        ("You have my word.", "我向你打包票保證。")
    ],

    "職場工作與快速同步": [
        ("Got a minute?", "現在有一分鐘空檔嗎？"),
        ("Can we talk real quick?", "我們可以快速講兩句話嗎？"),
        ("Quick question for you.", "快速請教你一個小問題。"),
        ("I'm on it.", "我現在立刻去處理。"),
        ("I'll take care of it.", "這件事我來負責辦好。"),
        ("Consider it done.", "包在我身上，當作已經搞定了。"),
        ("Let's touch base later.", "我們晚點再對一下進度。"),
        ("Let's sync up after lunch.", "午餐後我們快速同步一下資訊。"),
        ("Loop me in on the email.", "寫信時記得把我加入副本 (CC)。"),
        ("Keep me in the loop.", "有最新進度請隨時讓我知道。"),
        ("Let's wrap this up.", "我們把這個會議／工作做個收尾吧。"),
        ("Let's call it a day.", "今天就先做到這裡，收工！"),
        ("I'm swamped with work.", "我被工作塞得滿滿的。"),
        ("My plate is full.", "我手頭上的事情已經全滿了。"),
        ("I can't take on more tasks.", "我沒辦法再接更多工作了。"),
        ("What's the deadline?", "截止期限是什麼時候？"),
        ("Deadline is end of day.", "截止時間是今天下班前。"),
        ("ASAP, please.", "越快越好，拜託了。"),
        ("First thing tomorrow morning.", "明天一大早第一優先處理。"),
        ("On track for tomorrow.", "進度一切正常，明天可完成。"),
        ("Running a bit behind.", "進度稍微有點落後。"),
        ("Ahead of schedule.", "進度超前了。"),
        ("Let me double check that.", "讓我再仔細覆核確認一下。"),
        ("I'll get back to you soon.", "我等等查好再回覆你。"),
        ("Leave it with me.", "這件事交給我處理就好。"),
        ("Send me the file.", "把檔案傳給我。"),
        ("Did you get my email?", "你有收到我發的電子郵件嗎？"),
        ("Check your inbox.", "看一下你的收件匣。"),
        ("I just sent it over.", "我剛剛已經寄過去了。"),
        ("Thanks for the quick reply!", "謝謝你迅速的回信！"),
        ("Sorry for the delay.", "抱歉回覆延誤了。"),
        ("I was away from my desk.", "我剛才離開座位了一下。"),
        ("I was stuck in a meeting.", "我剛剛卡在會議中開會。"),
        ("Meeting is rescheduled.", "會議改時間了。"),
        ("Meeting is pushed back.", "會議往後延期了。"),
        ("Meeting is canceled.", "會議取消了。"),
        ("Let's take this offline.", "這個問題我們私下再另外討論。"),
        ("Who's running the meeting?", "這場會議是由誰主持的？"),
        ("Can everyone see my screen?", "大家都能看到我的分享畫面嗎？"),
        ("You're on mute.", "你麥克風靜音了。"),
        ("Unmute yourself, please.", "請把你的麥克風開啟。"),
        ("We can hear you clearly now.", "現在聽得很清楚了。"),
        ("Share your screen, please.", "麻煩請分享一下你的螢幕。"),
        ("Let me share my slides.", "讓我來分享一下我的簡報投影片。"),
        ("Next slide, please.", "請切換到下一張投影片。"),
        ("Any questions so far?", "到目前為止大家有任何問題嗎？"),
        ("Let's brainstorm some ideas.", "我們來腦力激盪想些點子。"),
        ("Think outside the box.", "跳脫框架思考。"),
        ("Bottom line is this.", "核心最關鍵的重點就是這個。"),
        ("We need to cut costs.", "我們需要精簡降低成本。"),
        ("Boost our sales.", "衝高我們的銷售業績。"),
        ("Hit our monthly target.", "達成我們的月度業績目標。"),
        ("Team effort!", "這是團隊共同努力的成果！"),
        ("Great job, everyone!", "大家做得太棒了！"),
        ("Shout out to the dev team!", "特別感謝研發團隊的付出！"),
        ("Give him a round of applause.", "大家給他熱烈的掌聲。"),
        ("Well deserved promotion!", "升遷當之無愧！恭喜！"),
        ("Who's leading this project?", "這個專案目前是由誰主導？"),
        ("I'm heading this project.", "我是這個專案的負責人。"),
        ("Let's assign tasks.", "我們來分配工作事項。"),
        ("Take notes, please.", "麻煩做一下會議紀錄。"),
        ("Send meeting minutes later.", "會後請發送會議記錄。"),
        ("Action items for today.", "今天的待辦執行項目。"),
        ("Follow up with the client.", "跟客戶追蹤後續進度。"),
        ("Sign the contract.", "在合約上簽名。"),
        ("Deal is signed!", "合約順利簽下來了！"),
        ("Good news from the client.", "客戶那邊傳來好消息。"),
        ("Client approved the plan.", "客戶已經核准計畫案了。"),
        ("Back to work!", "回到工作崗位上工吧！"),
        ("Coffee break time!", "咖啡休息時間到了！"),
        ("Who wants coffee?", "有誰想喝咖啡嗎？"),
        ("Grab me an espresso, please.", "幫我帶一杯濃縮咖啡，謝謝。"),
        ("Office is quiet today.", "今天辦公室好安靜。"),
        ("Working from home today.", "今天在家遠端工作。"),
        ("I'll be in the office tomorrow.", "我明天會進辦公室。"),
        ("Out of office today.", "今天休假外出不在辦公室。"),
        ("Set your automatic reply.", "記得設定自動休假回信。"),
        ("Taking half a day off.", "今天下午請半天假。"),
        ("Taking sick leave today.", "今天請病假一天。"),
        ("Get well soon!", "早日康復！"),
        ("Cover for me, please.", "拜託幫我代班一下。"),
        ("I'll cover your shift.", "我會幫你頂這個班。"),
        ("Clock in on time.", "準時打卡上班。"),
        ("Clock out now.", "現在打卡下班囉。"),
        ("Working overtime today.", "今天得留下來加班。"),
        ("No overtime today, yes!", "今天不用加班，太棒了！"),
        ("TGIF, Thank God it's Friday!", "感謝老天，終於星期五了！"),
        ("Have a good weekend, team!", "大家週末愉快！"),
        ("See you all on Monday.", "各位週一見囉。"),
        ("Fresh week, fresh start.", "新的一週，全新衝刺。"),
        ("Let's crush this week!", "這週我們一起大顯身手！"),
        ("Keep up the good work!", "繼續保持優異表現！"),
        ("Nice presentation today.", "今天簡報報得很精彩。"),
        ("You handled the questions well.", "你剛才回答問題答得很好。"),
        ("Thanks for the feedback.", "謝謝你的寶貴回饋建議。"),
        ("Open to constructive criticism.", "樂於接受建設性的批評。"),
        ("Let's improve on this.", "我們可以在這點上再做優化。"),
        ("Ready for launch!", "一切準備就緒，可以正式上線！"),
        ("Project goes live tomorrow.", "專案明天正式上線發布。"),
        ("All systems green.", "所有系統運作一切正常。")
    ],

    "電話通訊與訊息": [
        ("Hello, who's calling?", "您好，請問哪位找？"),
        ("This is Alex speaking.", "我是 Alex。"),
        ("Can I speak to Sarah, please?", "可以請 Sarah 接電話嗎？"),
        ("Speaking!", "我就是！（電話中回答本人）"),
        ("Hold on a second, please.", "請稍候一下下。"),
        ("Hang on a minute.", "請先別掛斷，等我一下。"),
        ("Let me transfer your call.", "我幫您轉接電話。"),
        ("I'll put you through.", "我這就幫您接通過去。"),
        ("Line is busy right now.", "線路目前通話中忙線。"),
        ("She's on another call.", "她正在講另一通電話。"),
        ("He's away from his desk.", "他目前不在座位上。"),
        ("Can I take a message?", "需要我幫您留言嗎？"),
        ("Would you like to leave a message?", "您想留個話給他嗎？"),
        ("Tell him Alex called.", "請轉告他 Alex 有打電話來。"),
        ("Ask her to call me back.", "麻煩請她回電給我。"),
        ("What's your phone number?", "您的電話號碼是多少？"),
        ("My number is 555-0199.", "我的號碼是 555-0199。"),
        ("Got it, I'll let him know.", "記下來了，我會轉告他。"),
        ("Thanks for calling.", "謝謝您的來電。"),
        ("I'll call you right back.", "我等等立刻回撥給你。"),
        ("Can you hear me okay?", "你能聽得清楚我的聲音嗎？"),
        ("You're breaking up.", "你的聲音斷斷續續的。"),
        ("Bad connection here.", "這裡的收訊連線很差。"),
        ("I lost you for a second.", "剛才收訊斷了一下沒聽到你說的。"),
        ("Say that again, please.", "請再說一次好嗎？"),
        ("Could you speak up a bit?", "你可以說大聲一點點嗎？"),
        ("It's noisy here.", "我這邊環境滿吵的。"),
        ("Call got disconnected.", "電話剛剛斷線掉了。"),
        ("My battery is dying.", "我手機快沒電了。"),
        ("Phone shut down.", "手機自動關機了。"),
        ("Send me a text instead.", "改傳簡訊訊息給我吧。"),
        ("Text me the address.", "把地址傳訊息給我。"),
        ("Text me your location.", "把你的即時定位傳給我。"),
        ("I'll send you a link.", "我等等傳連結給你。"),
        ("Check your messages.", "看一下你的簡訊訊息。"),
        ("Did you see my text?", "你有看到我剛發的訊息嗎？"),
        ("Replying to your text now.", "我正在回覆你的訊息。"),
        ("Got your voice note.", "收到你的語音訊息了。"),
        ("Send a quick voice note.", "錄一小段語音訊息傳過去。"),
        ("Let's do a video call.", "我們來打視訊電話吧。"),
        ("Turn on your camera.", "把你的視訊鏡頭打開。"),
        ("Nice seeing your face!", "看見你的臉真好！"),
        ("I'll screen share with you.", "我把螢幕畫面分享給你看。"),
        ("Mute your microphone.", "把你的麥克風靜音。"),
        ("Hit me up later!", "晚點再敲我／聯絡我！"),
        ("Drop me a line anytime.", "隨時發個訊息給我。"),
        ("Ping me on chat.", "在聊天軟體上叮我一下。"),
        ("I'll DM you the details.", "我會私訊你詳細資訊。"),
        ("Add me on Instagram.", "在 Instagram 上加我好友。"),
        ("What's your handle?", "你的帳號 ID 是什麼？"),
        ("Follow me back!", "記得回追蹤我喔！"),
        ("Tag me in the photo.", "在照片裡標記 (Tag) 我。"),
        ("Post it on your story.", "把它發到你的限時動態。"),
        ("Sent you a friend request.", "我傳送交友邀請給你了。"),
        ("Accept my invite.", "接受我的邀請。"),
        ("Join the group chat.", "加入群組聊天室。"),
        ("Created a new group.", "建了一個新的群組。"),
        ("Leave the group chat.", "退出群組聊天室。"),
        ("Spam call, ignore it.", "那是垃圾推銷電話，別理它。"),
        ("Block that number.", "把那個號碼封鎖掉。"),
        ("Wrong number, sorry.", "抱歉，您打錯電話了。"),
        ("No problem, have a good day.", "沒關係，祝您順心。"),
        ("Voicemail is full.", "語音信箱已經全滿了。"),
        ("Leave a voicemail.", "在語音信箱留言。"),
        ("Check your voicemail.", "去聽一下你的語音信箱。"),
        ("Ring tone is loud.", "手機鈴聲調得很大聲。"),
        ("Put it on vibrate.", "把它切換成震動模式。"),
        ("Put phone on silent.", "把手機轉成靜音。"),
        ("Do Not Disturb mode is on.", "勿擾模式開啟中。"),
        ("Missed your call.", "剛才沒接到你的未接來電。"),
        ("Calling you back now.", "現在回撥給你。"),
        ("Sorry, I was driving.", "抱歉，剛才開車中沒辦法接。"),
        ("Sorry, I was asleep.", "抱歉，剛才睡著了。"),
        ("Call me when you wake up.", "醒來後打給我。"),
        ("Call me when you land.", "班機落地後打給我。"),
        ("Call me when you get home.", "回到家打給我。"),
        ("Stay on the line.", "請先在線上不要掛斷。"),
        ("Thanks for waiting.", "感謝您的耐心等候。"),
        ("Glad we connected.", "真高興能通上電話。"),
        ("Talk to you later, bye!", "晚點再聊囉，掰掰！"),
        ("I gotta hang up now.", "我現在得掛電話了。"),
        ("Someone else is calling in.", "有插播電話進來了。"),
        ("Let me take this call.", "我先接一下這通電話。"),
        ("I'll call right after this.", "講完這通立刻打給你。"),
        ("Talk soon!", "很快再聊！"),
        ("Bye for now!", "先這樣囉，掰！"),
        ("Take care, bye!", "保重喔，掰掰！"),
        ("Catch you tomorrow.", "明天再打給你聊。"),
        ("Sending love over the phone.", "透過電話送上滿滿的愛。"),
        ("Goodnight, talk tomorrow.", "晚安，明天再聊。"),
        ("Read at 10 PM.", "已讀時間晚上十點。"),
        ("Left on read.", "被已讀不回了。"),
        ("Typing a response...", "正在輸入訊息中..."),
        ("Autocorrect failed me!", "自動選字害慘我了！選錯字！"),
        ("Typo, sorry!", "打錯字了，抱歉！"),
        ("Ignore my last message.", "請略過我剛發的那條訊息。"),
        ("Meant to send to John.", "本來是要傳給 John 的，傳錯了。"),
        ("Forward the message.", "把這條訊息轉發出去。"),
        ("Save the picture.", "把照片儲存下來。"),
        ("Sent!", "傳送出去了！")
    ],

    "身體健康與日常狀況": [
        ("I'm feeling beat today.", "我今天感到累翻了。"),
        ("I'm exhausted.", "我精疲力竭了。"),
        ("I need some sleep.", "我需要好好睡一覺。"),
        ("I'm under the weather.", "我身體稍微有點不太舒服。"),
        ("I feel a cold coming on.", "我感覺自己好像快感冒了。"),
        ("I have a sore throat.", "我喉嚨很痛。"),
        ("I have a runny nose.", "我一直在流鼻水。"),
        ("I can't stop sneezing.", "我一直打噴嚏停不下來。"),
        ("I have a bad cough.", "我咳得很厲害。"),
        ("My head is killing me.", "我的頭痛得要命。"),
        ("I have a splitting headache.", "我頭痛欲裂。"),
        ("I have a slight fever.", "我有一點輕微發燒。"),
        ("My temperature is 38 degrees.", "我體溫是三十八度。"),
        ("Take your temperature.", "去量一下你的體溫。"),
        ("Take some medicine.", "去吃點藥。"),
        ("Take two pills with water.", "配水吞兩顆藥丸。"),
        ("Take this after meals.", "這個請在三餐飯後服用。"),
        ("Take this on an empty stomach.", "這個請空腹服用。"),
        ("Does this cause drowsiness?", "這個藥吃了會嗜睡想睡覺嗎？"),
        ("Drink lots of fluids.", "多補充水分多喝水。"),
        ("Get plenty of rest.", "好好充分休息。"),
        ("Stay in bed today.", "今天躺在床上好好休養。"),
        ("I have a stomachache.", "我肚子痛／胃痛。"),
        ("My stomach is upset.", "我的胃腸不太舒服。"),
        ("I feel nauseous.", "我感覺反胃想吐。"),
        ("I feel dizzy.", "我感覺頭暈目眩。"),
        ("Sit down and rest.", "坐下來休息一下。"),
        ("I twisted my ankle.", "我扭傷腳踝了。"),
        ("Put some ice on it.", "拿冰塊在上面冰敷一下。"),
        ("My muscles are sore.", "我全身肌肉好痠痛。"),
        ("Worked out too hard yesterday.", "昨天健身運動練太兇了。"),
        ("I need a massage.", "我好需要去按摩一下放鬆。"),
        ("My back hurts.", "我的腰背好痛。"),
        ("My eyes are strained.", "我的眼睛好疲勞乾澀。"),
        ("Take a screen break.", "讓眼睛離開螢幕休息一下。"),
        ("Look out the window.", "看看窗外遠處放鬆。"),
        ("I need some fresh air.", "我需要去吸點新鮮空氣。"),
        ("Let's go for a walk.", "我們去散個步透透氣。"),
        ("Stretch your arms and legs.", "拉拉筋、伸展一下手腳。"),
        ("Do some light yoga.", "做點溫和的瑜珈伸展。"),
        ("I'm feeling much better now.", "我現在感覺好多了。"),
        ("Back on my feet!", "完全康復、重獲活力了！"),
        ("Full of energy today!", "今天活力充沛、精神百倍！"),
        ("Glad you're feeling better.", "真高興看到你身體好轉了。"),
        ("Get well soon!", "祝你早日康復！"),
        ("Take good care of yourself.", "好好保重照顧自己喔。"),
        ("Don't push yourself too hard.", "別把自己逼得太緊累壞了。"),
        ("Listen to your body.", "聆聽傾聽自己身體的聲音。"),
        ("Health comes first.", "健康永遠是第一位的。"),
        ("Eat healthy foods.", "多吃健康的食物。"),
        ("More greens and fruits.", "多吃蔬菜和水果。"),
        ("Cut down on sugar.", "少吃點糖分。"),
        ("Cut back on junk food.", "少吃點垃圾垃圾食物。"),
        ("Stay hydrated!", "記得隨時補充水分！"),
        ("Drink eight glasses a day.", "一天喝足八杯水。"),
        ("Are you sleeping well?", "你最近睡眠品質好嗎？"),
        ("I have insomnia lately.", "我最近一直有失眠問題。"),
        ("Tossing and turning all night.", "整晚翻來覆去睡不著。"),
        ("Try drinking warm milk.", "試試看喝杯溫牛奶。"),
        ("No caffeine after 3 PM.", "下午三點後不要碰咖啡因。"),
        ("Put phone away before bed.", "睡前把手機放遠一點。"),
        ("I need to see a doctor.", "我需要去看醫生。"),
        ("Make a doctor's appointment.", "預約看診掛號。"),
        ("Where is the clinic?", "診所在哪裡？"),
        ("Where's the pharmacy?", "藥局在哪裡？"),
        ("Is there an emergency room nearby?", "這附近有急診室嗎？"),
        ("Call an ambulance!", "快叫救護車！"),
        ("I have health insurance.", "我有全民健保／醫療保險。"),
        ("Show your health insurance card.", "出示你的健保卡。"),
        ("Doctor will see you now.", "醫生現在可以為您看診了。"),
        ("Where does it hurt?", "哪裡會痛呢？"),
        ("It hurts right here.", "就是這裡在痛。"),
        ("How long has it hurt?", "痛了多久時間了？"),
        ("Started two days ago.", "兩天前開始痛的。"),
        ("Breathe in deeply.", "深吸一口氣。"),
        ("Breathe out slowly.", "慢慢吐氣。"),
        ("Open wide and say Ah.", "嘴巴張大，說『啊～』。"),
        ("Nothing serious, don't worry.", "沒有大礙，不用太擔心。"),
        ("You'll be fine in a few days.", "過幾天就會痊癒沒事了。"),
        ("Take this prescription to the counter.", "拿這張處方箋去領藥櫃台。"),
        ("Take vitamins daily.", "每天補充綜合維他命。"),
        ("Vitamin C boosts immunity.", "維他命 C 能提升免疫力。"),
        ("Wash your hands often.", "常常用肥皂洗手。"),
        ("Use hand sanitizer.", "使用酒精乾洗手消毒。"),
        ("Wear a mask if you're sick.", "生病時請記得戴上口罩。"),
        ("Cover your mouth when coughing.", "咳嗽時記得遮住嘴巴。"),
        ("Stay home if you have a fever.", "發燒請留在家裡休息不要外出。"),
        ("Annual health checkup.", "每年的年度健康檢查。"),
        ("Blood pressure is normal.", "血壓量出來很正常。"),
        ("Heart rate looks good.", "心跳頻率很健康。"),
        ("Keep up the good habits!", "繼續維持良好的生活習慣！"),
        ("Regular exercise is key.", "規律運動是關鍵要訣。"),
        ("Go for a run.", "去慢跑一下。"),
        ("Hit the gym.", "去健身房鍛鍊。"),
        ("Feeling strong and fit!", "感覺強健又充滿體態活力！"),
        ("Stay safe and healthy!", "保持安全健康喔！"),
        ("Cheers to good health!", "為身體健康乾杯！"),
        ("Wishing you good health always.", "祝福您身體常保健康安康。"),
        ("Take it easy and rest up.", "放寬心，好好多休息補眠。"),
        ("Stay in good shape!", "保持良好的健康體態！")
    ]
}

def generate_json_files():
    total_list = []
    item_id = 1

    for category_name, pairs in categories_data.items():
        count = len(pairs)
        print(f"Category '{category_name}': {count} sentences")
        for en, zh in pairs:
            total_list.append({
                "id": item_id,
                "category": category_name,
                "en": en.strip(),
                "zh": zh.strip()
            })
            item_id += 1

    print(f"\nTotal sentences generated: {len(total_list)}")
    assert len(total_list) == 1200, f"Expected 1200 sentences, got {len(total_list)}"

    target_paths = [
        r'c:\Users\aggyy\source\repos\Englishtest\sentences_spoken.json',
        r'c:\Users\aggyy\source\repos\Englishtest\data\sentences_spoken.json',
        r'c:\Users\aggyy\source\repos\Englishtest\web\sentences_spoken.json',
        r'c:\Users\aggyy\source\repos\Englishtest\web\data\sentences_spoken.json'
    ]

    for p in target_paths:
        os.makedirs(os.path.dirname(p), exist_ok=True)
        with open(p, 'w', encoding='utf-8') as f:
            json.dump(total_list, f, ensure_ascii=False, indent=2)
        print(f"Written: {p} ({len(total_list)} sentences)")

if __name__ == '__main__':
    generate_json_files()
