# -*- coding: utf-8 -*-
import json
import random
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORDS_PATH = os.path.join(ROOT, "words.json")

# (Level, Chinese, [English...])
NEW_WORDS = [
# A1 batch
("A1","零","zero"),("A1","十一","eleven"),("A1","十二","twelve"),("A1","十三","thirteen"),
("A1","十四","fourteen"),("A1","十五","fifteen"),("A1","十六","sixteen"),("A1","十七","seventeen"),
("A1","十八","eighteen"),("A1","十九","nineteen"),("A1","二十","twenty"),("A1","三十","thirty"),
("A1","四十","forty"),("A1","五十","fifty"),("A1","六十","sixty"),("A1","七十","seventy"),
("A1","八十","eighty"),("A1","九十","ninety"),("A1","百","hundred"),("A1","千","thousand"),
("A1","紅色","red"),("A1","藍色","blue"),("A1","綠色","green"),("A1","黃色","yellow"),
("A1","黑色","black"),("A1","白色","white"),("A1","橙色","orange"),("A1","粉色","pink"),
("A1","棕色","brown"),("A1","灰色","gray"),("A1","父親","father"),("A1","母親","mother"),
("A1","兒子","son"),("A1","女兒","daughter"),("A1","兄弟","brother"),("A1","姐妹","sister"),
("A1","爺爺","grandfather"),("A1","奶奶","grandmother"),("A1","丈夫","husband"),("A1","妻子","wife"),
("A1","男孩","boy"),("A1","女孩","girl"),("A1","嬰兒","baby"),("A1","人","person"),
("A1","人們","people"),("A1","狗","dog"),("A1","貓","cat"),("A1","鳥","bird"),
("A1","魚","fish"),("A1","馬","horse"),("A1","牛","cow"),("A1","豬","pig"),
("A1","雞","chicken"),("A1","老鼠","mouse"),("A1","兔子","rabbit"),("A1","頭","head"),
("A1","手","hand"),("A1","腳","foot"),("A1","眼睛","eye"),("A1","耳朵","ear"),
("A1","鼻子","nose"),("A1","嘴巴","mouth"),("A1","牙齒","tooth"),("A1","頭髮","hair"),
("A1","身體","body"),("A1","手臂","arm"),("A1","腿","leg"),("A1","心","heart"),
("A1","車","car"),("A1","公車","bus"),("A1","火車","train"),("A1","計程車","taxi"),
("A1","腳踏車","bicycle"),("A1","船","boat"),("A1","飛機","airplane"),
("A1","桌子","table"),("A1","椅子","chair"),("A1","門","door"),("A1","窗","window"),
("A1","床","bed"),("A1","房間","room"),("A1","房子","house"),("A1","廚房","kitchen"),
("A1","浴室","bathroom"),("A1","筆","pen"),("A1","鉛筆","pencil"),("A1","紙","paper"),
("A1","包","bag"),("A1","錢","money"),("A1","電話","telephone"),("A1","電視","TV"),
("A1","早上","morning"),("A1","下午","afternoon"),("A1","晚上","evening"),("A1","夜","night"),
("A1","星期","week"),("A1","月","month"),("A1","年","year"),("A1","小時","hour"),
("A1","分鐘","minute"),("A1","秒","second"),("A1","昨天","yesterday"),("A1","現在","now"),
("A1","熱","hot"),("A1","冷","cold"),("A1","暖","warm"),("A1","涼","cool"),
("A1","新","new"),("A1","舊","old"),("A1","年輕","young"),("A1","老","old"),
("A1","長","long"),("A1","短","short"),("A1","高","tall"),("A1","胖","fat"),
("A1","瘦","thin"),("A1","快","fast"),("A1","慢","slow"),("A1","強","strong"),
("A1","弱","weak"),("A1","乾淨","clean"),("A1","髒","dirty"),("A1","漂亮","pretty"),
("A1","醜","ugly"),("A1","餓","hungry"),("A1","渴","thirsty"),("A1","累","tired"),
("A1","生病","sick"),("A1","健康","healthy"),("A1","醫生","doctor"),("A1","護士","nurse"),
("A1","藥","medicine"),("A1","痛","pain"),("A1","幫助","help"),("A1","請","please"),
("A1","謝謝","thanks"),("A1","對不起","sorry"),("A1","你好","hello"),("A1","再見","goodbye"),
("A1","請進","welcome"),("A1","等待","wait"),("A1","開始","start"),("A1","結束","end"),
("A1","打開","open"),("A1","關上","close"),("A1","推","push"),("A1","拉","pull"),
("A1","走","walk"),("A1","跑","run"),("A1","跳","jump"),("A1","坐","sit"),
("A1","站","stand"),("A1","睡","sleep"),("A1","醒","wake"),("A1","穿","wear"),
("A1","洗","wash"),("A1","煮","cook"),("A1","切","cut"),("A1","畫","draw"),
("A1","寫","write"),("A1","讀","read"),("A1","教","teach"),("A1","玩","play"),
("A1","遊戲","game"),("A1","球","ball"),("A1","米","rice"),("A1","麵包","bread"),
("A1","肉","meat"),("A1","蛋","egg"),("A1","牛奶","milk"),("A1","茶","tea"),
("A1","湯","soup"),("A1","糖","sugar"),("A1","鹽","salt"),("A1","水果","fruit"),
("A1","蔬菜","vegetable"),("A1","香蕉","banana"),("A1","橘子","orange"),
("A1","城市","city"),("A1","鄉村","village"),("A1","國家","country"),("A1","街道","street"),
("A1","商店","store"),("A1","市場","market"),("A1","公園","park"),("A1","銀行","bank"),
("A1","郵局","post office"),("A1","圖書館","library"),("A1","博物館","museum"),
("A1","北","north"),("A1","南","south"),("A1","東","east"),("A1","西","west"),
("A1","左","left"),("A1","右","right"),("A1","上","up"),("A1","下","down"),
("A1","裡面","inside"),("A1","外面","outside"),("A1","附近","near"),("A1","遠","far"),
("A1","這","this"),("A1","那","that"),("A1","這些","these"),("A1","那些","those"),
("A1","什麼","what"),("A1","誰","who"),("A1","哪裡","where"),("A1","何時","when"),
("A1","為什麼","why"),("A1","怎麼","how"),("A1","多少","how many"),("A1","非常","very"),
("A1","也","also"),("A1","只","only"),("A1","還","still"),("A1","已經","already"),
("A1","從","from"),("A1","到","to"),("A1","給","give"),("A1","拿","take"),
("A1","買","buy"),("A1","賣","sell"),("A1","找","find"),("A1","丟","lose"),
("A1","放","put"),("A1","用","use"),("A1","做","make"),("A1","做","do"),
("A1","有","have"),("A1","是","be"),("A1","能","can"),("A1","將","will"),
("A1","要","want"),("A1","需要","need"),("A1","試","try"),("A1","記得","remember"),
("A1","忘記","forget"),("A1","相信","believe"),("A1","希望","hope"),("A1","覺得","feel"),
("A1","看見","see"),("A1","聽見","hear"),("A1","聞","smell"),("A1","嘗","taste"),
("A1","觸摸","touch"),("A1","笑","smile"),("A1","哭","cry"),("A1","生氣","angry"),
("A1","害怕","afraid"),("A1","驚訝","surprised"),("A1","語言","language"),("A1","問題","question"),
("A1","答案","answer"),("A1","事情","thing"),("A1","地方","place"),("A1","時間","time"),
("A1","生活","life"),("A1","世界","world"),("A1","天","day"),("A1","太陽","sun"),
("A1","月亮","moon"),("A1","星星","star"),("A1","天空","sky"),("A1","雨","rain"),
("A1","雪","snow"),("A1","風","wind"),("A1","雲","cloud"),("A1","樹","tree"),
("A1","花","flower"),("A1","草","grass"),("A1","山","mountain"),("A1","河","river"),
("A1","海","sea"),("A1","湖","lake"),("A1","島","island"),("A1","地圖","map"),
# A2 batch
("A2","雖然","although"),("A2","除非","unless"),("A2","直到","until"),("A2","當…時","while"),
("A2","如果","if"),("A2","可能","maybe"),("A2","大概","probably"),("A2","幾乎","almost"),
("A2","剛剛","just"),("A2","仍然","still"),("A2","再次","again"),("A2","一起","together"),
("A2","單獨","alone"),("A2","其他","other"),("A2","相同","same"),("A2","不同","different"),
("A2","另一個","another"),("A2","足夠","enough"),("A2","太多","too much"),("A2","很少","a little"),
("A2","幾個","several"),("A2","每個","each"),("A2","兩者","both"),("A2","借","borrow"),
("A2","歸還","return"),("A2","借出","lend"),("A2","花費","spend"),("A2","節省","save"),
("A2","支付","pay"),("A2","到達","arrive"),("A2","離開","leave"),("A2","停留","stay"),
("A2","參觀","visit"),("A2","邀請","invite"),("A2","歡迎","welcome"),("A2","準備","prepare"),
("A2","完成","complete"),("A2","繼續","continue"),("A2","停止","stop"),("A2","嘗試","try"),
("A2","成功","succeed"),("A2","失敗","fail"),("A2","同意","agree"),("A2","拒絕","refuse"),
("A2","允許","allow"),("A2","禁止","forbid"),("A2","修理","repair"),("A2","建造","build"),
("A2","打破","break"),("A2","天氣","weather"),("A2","下雨","rain"),("A2","下雪","snow"),
("A2","季節","season"),("A2","春天","spring"),("A2","夏天","summer"),("A2","秋天","fall"),
("A2","冬天","winter"),("A2","運動","exercise"),("A2","足球","soccer"),("A2","游泳","swim"),
("A2","跑步","jog"),("A2","跳舞","dance"),("A2","唱歌","sing"),("A2","音樂","music"),
("A2","電影","film"),("A2","新聞","news"),("A2","故事","story"),("A2","照片","picture"),
("A2","興趣","interest"),("A2","花園","garden"),("A2","臥室","bedroom"),("A2","客廳","living room"),
("A2","鄰居","neighbor"),("A2","同事","coworker"),("A2","老闆","boss"),("A2","顧客","client"),
("A2","工程師","engineer"),("A2","警察","policeman"),("A2","司機","driver"),
("A2","廚師","cook"),("A2","藝術家","painter"),("A2","科學家","researcher"),
("A2","考試","test"),("A2","作業","assignment"),("A2","課程","class"),("A2","大學","college"),
("A2","機場","airport"),("A2","飯店","inn"),("A2","餐廳","dining"),("A2","超市","grocery"),
("A2","藥局","pharmacy"),("A2","電影院","cinema"),("A2","健身房","gym"),
("A2","網路","internet"),("A2","電子郵件","email"),("A2","密碼","password"),
("A2","下載","download"),("A2","上傳","upload"),("A2","網站","website"),
("A2","電池","battery"),("A2","充電","charge"),("A2","相機","camera"),("A2","錄影","record"),
("A2","護照","passport"),("A2","簽證","visa"),("A2","行李","luggage"),("A2","訂票","book"),
("A2","取消","cancel"),("A2","延遲","delay"),("A2","準時","punctual"),("A2","迷路","lost"),
("A2","方向","direction"),("A2","地鐵","subway"),("A2","高速公路","highway"),
("A2","紅綠燈","traffic light"),("A2","停車","parking"),("A2","事故","crash"),
("A2","受傷","injured"),("A2","保險","insurance"),("A2","合約","contract"),
("A2","薪水","wage"),("A2","加班","overtime"),("A2","面試","interview"),("A2","履歷","resume"),
("A2","退休","retire"),("A2","升遷","promotion"),("A2","解雇","fire"),("A2","辭職","resign"),
# B1 batch  
("B1","成就","achievement"),("B1","野心","ambition"),("B1","焦慮","anxiety"),
("B1","自信","confidence"),("B1","創造力","creativity"),("B1","好奇心","curiosity"),
("B1","耐心","patience"),("B1","誠實","honesty"),("B1","謙虛","modesty"),("B1","忠誠","loyalty"),
("B1","同情","compassion"),("B1","嫉妒","envy"),("B1","憤怒","rage"),("B1","恐懼","terror"),
("B1","驚訝","astonishment"),("B1","後悔","remorse"),("B1","絕望","hopelessness"),
("B1","滿意","contentment"),("B1","失望","frustration"),("B1","承認","acknowledge"),
("B1","避免","avoid"),("B1","承諾","commit"),("B1","控制","control"),("B1","貢獻","contribute"),
("B1","說服","persuade"),("B1","假設","assume"),("B1","想像","envision"),("B1","懷疑","suspect"),
("B1","證明","demonstrate"),("B1","否認","reject"),("B1","原諒","pardon"),("B1","道歉","apologize"),
("B1","感謝","grateful"),("B1","尊重","honor"),("B1","忽視","neglect"),("B1","注意","attend"),
("B1","觀察","watch"),("B1","專注","concentrate"),("B1","分心","divert"),("B1","組織","organize"),
("B1","安排","schedule"),("B1","管理","administer"),("B1","領導","guide"),("B1","合作","collaborate"),
("B1","競爭","rival"),("B1","參加","join"),("B1","放棄","abandon"),("B1","堅持","persevere"),
("B1","適應","adjust"),("B1","改變","change"),("B1","替換","substitute"),("B1","更新","refresh"),
("B1","擴大","enlarge"),("B1","縮小","reduce"),("B1","加強","enhance"),("B1","削弱","undermine"),
("B1","維持","preserve"),("B1","破壞","destroy"),("B1","修復","fix"),("B1","保護","guard"),
("B1","攻擊","assault"),("B1","防禦","guard"),("B1","威脅","intimidate"),("B1","安全","safety"),
("B1","危險","hazard"),("B1","風險","hazard"),("B1","災難","catastrophe"),("B1","污染","contaminate"),
("B1","回收","reuse"),("B1","節能","save energy"),("B1","氣候","weather pattern"),
("B1","人口","demographics"),("B1","移民","migrant"),("B1","難民","displaced person"),
("B1","貧窮","destitution"),("B1","財富","affluence"),("B1","稅","levy"),("B1","債務","liability"),
("B1","預算","financial plan"),("B1","福利","benefit"),("B1","權利","right"),("B1","義務","duty"),
("B1","法律","law"),("B1","規則","rule"),("B1","自由","liberty"),("B1","平等","equality"),
("B1","正義","fairness"),("B1","選舉","ballot"),("B1","政府","administration"),("B1","政策","policy"),
("B1","抗議","demonstrate"),("B1","革命","uprising"),("B1","和平","harmony"),("B1","戰爭","warfare"),
("B1","媒體","media"),("B1","廣告","advertisement"),("B1","品牌","brand"),("B1","消費者","consumer"),
("B1","生產","produce"),("B1","服務","service"),("B1","品質","quality"),("B1","數量","quantity"),
("B1","價格","price"),("B1","利潤","profit"),("B1","成本","cost"),("B1","需求","demand"),
("B1","供應","supply"),("B1","競爭力","competitiveness"),("B1","創新","innovation"),
("B1","技術","technology"),("B1","科學","science"),("B1","研究","research"),("B1","實驗","experiment"),
("B1","理論","theory"),("B1","實踐","practice"),("B1","證據","proof"),("B1","結論","conclusion"),
("B1","原因","cause"),("B1","結果","outcome"),("B1","影響","effect"),("B1","關係","relation"),
("B1","溝通","communication"),("B1","討論","discussion"),("B1","辯論","argument"),
("B1","演講","speech"),("B1","報告","report"),("B1","文章","article"),("B1","段落","paragraph"),
("B1","句子","sentence"),("B1","單字","vocabulary"),("B1","文法","grammar"),("B1","發音","pronunciation"),
("B1","口音","accent"),("B1","流利","fluent"),("B1","翻譯","translate"),("B1","解釋","interpret"),
("B1","描述","describe"),("B1","比較","compare"),("B1","對比","contrast"),("B1","總結","summarize"),
("B1","分析","examine"),("B1","評價","evaluate"),("B1","建議","suggest"),("B1","推薦","recommend"),
("B1","批評","criticize"),("B1","鼓勵","encourage"),("B1","激勵","motivate"),("B1","啟發","inspire"),
("B1","無聊","bored"),("B1","有趣","interesting"),("B1","興奮","excited"),("B1","緊張","nervous"),
("B1","放鬆","relaxed"),("B1","壓力","pressure"),("B1","平衡","equilibrium"),("B1","習慣","routine"),
("B1","目標","objective"),("B1","計畫","plan"),("B1","步驟","step"),("B1","過程","process"),
("B1","方法","method"),("B1","系統","system"),("B1","結構","structure"),("B1","功能","function"),
("B1","目的","purpose"),("B1","意義","meaning"),("B1","價值","value"),("B1","傳統","tradition"),
("B1","文化","culture"),("B1","社會","community"),("B1","社區","neighborhood"),("B1","公民","citizen"),
("B1","環境","surroundings"),("B1","自然","nature"),("B1","資源","resource"),("B1","能源","power source"),
("B1","浪費","waste"),("B1","節約","economize"),("B1","慈善","charity"),("B1","志工","volunteer"),
("B1","捐贈","donate"),("B1","基金會","foundation"),("B1","教育","education"),("B1","訓練","train"),
("B1","技能","skill"),("B1","經驗","background"),("B1","能力","capability"),("B1","才華","talent"),
("B1","努力","effort"),("B1","運氣","luck"),("B1","機會","opportunity"),("B1","挑戰","challenge"),
("B1","困難","difficulty"),("B1","解決","resolve"),("B1","問題","issue"),("B1","危機","crisis"),
("B1","穩定","stable"),("B1","變化","variation"),("B1","趨勢","tendency"),("B1","發展","development"),
("B1","進步","advance"),("B1","落後","backward"),("B1","現代化","modernize"),("B1","全球化","globalize"),
# B2 batch
("B2","分析師","analyst"),("B2","評估師","appraiser"),("B2","預測師","forecaster"),
("B2","假設檢驗","hypothesis test"),("B2","推論","inference"),("B2","驗證","validate"),
("B2","反駁","rebut"),("B2","質詢","interrogate"),("B2","辯護","defend"),
("B2","調停","arbitrate"),("B2","讓步","yield"),("B2","堅持己見","insist"),("B2","主張","maintain"),
("B2","聲稱","allege"),("B2","暗示","suggest"),("B2","明示","state clearly"),("B2","概括","summarize broadly"),
("B2","具體說明","elaborate"),("B2","澄清","clear up"),("B2","簡化","streamline"),
("B2","複雜化","complicate"),("B2","強調","stress"),("B2","淡化","minimize"),
("B2","突出","accentuate"),("B2","象徵","stand for"),("B2","反映","mirror"),
("B2","揭示","uncover"),("B2","隱藏","hide"),("B2","暴露","uncover"),("B2","滲透","infiltrate"),
("B2","擴散","disseminate"),("B2","抑制","restrain"),("B2","刺激","provoke"),("B2","引發","spark"),
("B2","促成","enable"),("B2","阻礙","impede"),("B2","促進","advance"),("B2","阻撓","block"),
("B2","授權","empower"),("B2","禁止","ban"),("B2","規範","standardize"),("B2","執行","implement"),
("B2","違反","breach"),("B2","合法化","legalize"),("B2","非法化","criminalize"),
("B2","腐敗","corrupt"),("B2","透明化","disclose"),("B2","問責","hold accountable"),
("B2","民主化","democratize"),("B2","獨裁者","dictator"),("B2","投票權","suffrage"),
("B2","改革派","reformer"),("B2","保守派","conservative"),("B2","激進派","radical"),
("B2","聯盟","coalition"),("B2","制裁","penalize"),("B2","條約","pact"),("B2","主權","autonomy"),
("B2","領土爭議","territorial dispute"),("B2","軍事行動","military operation"),
("B2","間諜活動","espionage"),("B2","情報機構","intelligence agency"),("B2","恐怖攻擊","terror attack"),
("B2","網路安全","cybersecurity"),("B2","資料外洩","data breach"),("B2","隱私權","privacy"),
("B2","演算法","algorithm"),("B2","人工智慧","artificial intelligence"),("B2","自動化","automation"),
("B2","區塊鏈","blockchain"),("B2","雲端運算","cloud computing"),("B2","大數據","big data"),
("B2","初創公司","startup"),("B2","獨角獸","unicorn company"),("B2","併購","merger"),
("B2","上市","go public"),("B2","破產","bankruptcy"),("B2","清算","liquidation"),
("B2","股息","dividend"),("B2","本益比","price earnings ratio"),("B2","市值","market cap"),
("B2","牛市","bull market"),("B2","熊市","bear market"),("B2","散戶","retail investor"),
("B2","法人","institutional investor"),("B2","避險基金","hedge fund"),("B2","ETF","ETF"),
("B2","期貨","futures"),("B2","選擇權","option"),("B2","槓桿交易","margin trading"),
("B2","停損","stop loss"),("B2","獲利了結","take profit"),("B2","技術分析","technical analysis"),
("B2","基本面","fundamentals"),("B2","財報","financial report"),("B2","營收","revenue"),
("B2","毛利率","gross margin"),("B2","淨利","net profit"),("B2","現金流","cash flow"),
("B2","資產負債表","balance sheet"),("B2","通膨率","inflation rate"),("B2","利率","interest rate"),
("B2","匯率","exchange rate"),("B2","貶值","devalue"),("B2","升值","appreciate"),
("B2","貿易順差","trade surplus"),("B2","貿易逆差","trade deficit"),("B2","關稅","tariff"),
("B2","供應鏈","supply chain"),("B2","物流","logistics"),("B2","外包","outsource"),
("B2","離岸","offshore"),("B2","在地化","localize"),("B2","市場占有率","market share"),
("B2","寡占","oligopoly"),("B2","壟斷","dominate market"),("B2","反壟斷","antitrust"),
("B2","消費者保護","consumer protection"),("B2","企業社會責任","corporate social responsibility"),
("B2","永續發展","sustainable development"),("B2","碳排放","carbon emission"),
("B2","淨零排放","net zero"),("B2","再生能源","renewable energy"),("B2","核能","nuclear power"),
("B2","地緣政治","geopolitics"),("B2","外交","diplomacy"),("B2","大使","ambassador"),
("B2","難民危機","refugee crisis"),("B2","人道援助","humanitarian aid"),
# C1 batch
("C1","曖昧性","ambivalence"),("C1","悖論","paradox"),("C1","諷刺性","irony"),
("C1","隱喻性","figurative"),("C1","抽象概念","abstraction"),("C1","主觀性","subjectivity"),
("C1","客觀性","objectivity"),("C1","相對性","relativity"),("C1","絕對性","absoluteness"),
("C1","普遍性","universality"),("C1","特殊性","specificity"),("C1","本質上","essentially"),
("C1","表面上","ostensibly"),("C1","深層次","in depth"),("C1","膚淺地","superficially"),
("C1","微妙地","subtly"),("C1","明顯地","manifestly"),("C1","隱含地","tacitly"),
("C1","明確地","explicitly"),("C1","模稜兩可地","ambiguously"),("C1","清晰地","lucidly"),
("C1","系統地","systematically"),("C1","全面地","comprehensively"),("C1","片面地","partially"),
("C1","均衡地","evenly"),("C1","極端地","extremely"),("C1","溫和地","moderately"),
("C1","激進地","radically"),("C1","保守地","conservatively"),("C1","進步地","progressively"),
("C1","傳統上","traditionally"),("C1","現代地","contemporarily"),("C1","過時地","archaically"),
("C1","創新地","innovatively"),("C1","主導地","predominantly"),("C1","從屬地","subordinately"),
("C1","平等地","equally"),("C1","階層地","hierarchically"),("C1","壟斷地","monopolistically"),
("C1","競爭地","competitively"),("C1","波動地","volatilely"),("C1","穩定地","steadily"),
("C1","流動地","fluidly"),("C1","槓桿化","leverage"),("C1","對沖策略","hedging strategy"),
("C1","套利交易","arbitrage trade"),("C1","通膨壓力","inflationary pressure"),
("C1","通縮螺旋","deflationary spiral"),("C1","經濟衰退","economic downturn"),
("C1","蕭條期","depression era"),("C1","復甦期","recovery phase"),
("C1","量化寬鬆","quantitative easing"),("C1","升息","rate hike"),("C1","降息","rate cut"),
("C1","資本管制","capital control"),("C1","外匯存底","foreign reserves"),
("C1","主權基金","sovereign wealth fund"),("C1","風險偏好","risk appetite"),
("C1","避險資產","safe haven asset"),("C1","避險工具","hedging instrument"),
("C1","信用違約","credit default"),("C1","違約風險","default risk"),("C1","流動性風險","liquidity risk"),
("C1","系統性風險","systemic risk"),("C1","黑天鵝","black swan"),("C1","灰犀牛","gray rhino"),
("C1","道德風險","moral hazard"),("C1","逆向選擇","adverse selection"),
("C1","資訊不對稱","information asymmetry"),("C1","代理問題","principal agent problem"),
("C1","激勵相容","incentive compatible"),("C1","機制設計","mechanism design"),
("C1","行為金融","behavioral finance"),("C1","有效市場","efficient market"),
("C1","隨機漫步","random walk"),("C1","資產配置","asset allocation"),
("C1","分散投資","diversification"),("C1","再平衡","rebalancing"),("C1","內在價值","intrinsic value"),
("C1","外在價值","extrinsic value"),("C1","估值模型","valuation model"),
("C1","折現率","discount rate"),("C1","資本成本","cost of capital"),
("C1","股東權益","shareholder equity"),("C1","公司治理","corporate governance"),
("C1","董事會","board of directors"),("C1","稽核","audit"),("C1","內控","internal control"),
("C1","法遵","compliance"),("C1","洗錢","money laundering"),("C1","內線交易","insider trading"),
("C1","市場操縱","market manipulation"),("C1","龐氏騙局","Ponzi scheme"),
("C1","審慎監管","prudential regulation"),("C1","宏觀審慎","macroprudential"),
("C1","財政政策","fiscal policy"),("C1","貨幣政策","monetary policy"),
("C1","結構性改革","structural reform"),("C1","產業政策","industrial policy"),
# C2 batch
("C2","無所不在地","ubiquitously"),("C2","罕見地","seldom"),("C2","獨特地","uniquely"),
("C2","平凡地","ordinarily"),("C2","非凡地","remarkably"),("C2","卓越地","excellently"),
("C2","平庸地","mediocrely"),("C2","傑出地","eminently"),("C2","拙劣地","abysmally"),
("C2","精湛地","exquisitely"),("C2","粗俗地","vulgarly"),("C2","優雅地","elegantly"),
("C2","邋遢地","sloppily"),("C2","謹慎地","circumspectly"),("C2","魯莽地","recklessly"),
("C2","狡猾地","cunningly"),("C2","天真地","naively"),("C2","世故地","sophisticatedly"),
("C2","單純地","ingenuously"),("C2","虛偽地","hypocritically"),("C2","真誠地","sincerely"),
("C2","做作地","affectedly"),("C2","謙遜地","unassumingly"),("C2","傲慢地","arrogantly"),
("C2","頑固地","obstinately"),("C2","隨和地","affably"),("C2","孤僻地","reclusively"),
("C2","外向地","extrovertedly"),("C2","內向地","introvertedly"),("C2","健談地","loquaciously"),
("C2","沉默地","taciturnly"),("C2","冗長地","verbosely"),("C2","簡潔地","laconically"),
("C2","囉嗦地","garrulously"),("C2","誇張地","bombastically"),("C2","含蓄地","understatedly"),
("C2","露骨地","blatantly"),("C2","微妙地","nuancedly"),("C2","直白地","forthrightly"),
("C2","拐彎抹角地","evasively"),("C2","坦率地","candidly"),("C2","含糊地","equivocally"),
("C2","明確地","unequivocally"),("C2","似是而非地","speciously"),("C2","無懈可擊地","impeccably"),
("C2","有破綻地","flawedly"),("C2","有缺陷地","defectively"),("C2","完美地","flawlessly"),
("C2","有瑕疵地","blemishedly"),("C2","純淨地","pristinely"),
("C2","語焉不詳","laconic"),("C2","陰謀論","conspiracy theory"),("C2","頑抗者","recalcitrant"),
("C2","油腔滑調","unctuous"),("C2","盛氣凌人","peremptory"),("C2","吹毛求疵","pedantic"),
("C2","深奧難懂","esoteric"),("C2","老生常談","platitude"),("C2","誇大其詞","hyperbole"),
("C2","頹廢美學","decadent aesthetic"),("C2","詭辯術","sophistry"),("C2","狡辯","quibble"),
("C2","強詞奪理","specious argument"),("C2","不可侵犯","inviolable"),("C2","盛極一時","heyday"),
("C2","盛極而衰","decline after peak"),("C2","物極必反","extreme turns"),("C2","因果報應","karma"),
("C2","宿命論","fatalism"),("C2","存在主義","existentialism"),("C2","虛無主義","nihilism"),
("C2","實用主義","pragmatism"),("C2","理想主義","idealism"),("C2","功利主義","utilitarianism"),
("C2","相對主義","relativism"),("C2","絕對主義","absolutism"),("C2","懷疑論","skepticism"),
("C2","不可知論","agnosticism"),("C2","二元論","dualism"),("C2","一元論","monism"),
("C2","辯證法","dialectic"),("C2","典範轉移","paradigm shift"),("C2","認知偏誤","cognitive bias"),
("C2","確認偏誤","confirmation bias"),("C2","倖存者偏誤","survivorship bias"),
("C2","錨定效應","anchoring effect"),("C2","從眾效應","herd behavior"),
("C2","過度自信","overconfidence"),("C2","損失厭惡","loss aversion"),
("C2","框架效應","framing effect"),("C2","沉沒成本","sunk cost"),
("C2","機會成本","opportunity cost"),("C2","邊際效用","marginal utility"),
("C2","比較優勢","comparative advantage"),("C2","絕對優勢","absolute advantage"),
("C2","博弈論","game theory"),("C2","納許均衡","Nash equilibrium"),
("C2","零和賽局","zero sum game"),("C2","雙贏","win win"),("C2","帕雷托最優","Pareto optimal"),
]

def load_existing():
    with open(WORDS_PATH, "r", encoding="utf-8") as f:
        return json.load(f)

def make_entry(level, chinese, english):
    eng = english if isinstance(english, list) else [english]
    return {"Level": level, "Chinese": chinese, "English": eng}

def dedupe_key(entry):
    w = entry["English"][0].strip().lower()
    if " " in w:
        w = w.split()[0]
    return f"{entry['Level']}|{w}"

def main():
    items = load_existing()
    seen = {dedupe_key(e) for e in items}

    for level, chinese, eng in NEW_WORDS:
        e = make_entry(level, chinese, eng)
        k = dedupe_key(e)
        if k not in seen:
            seen.add(k)
            items.append(e)

    # balance: if still under 500, duplicate-fill from pool with suffix chinese disambiguation - NO, user wants real words
    # shuffle and trim to 500 if over
    random.seed(42)
    if len(items) > 500:
        random.shuffle(items)
        items = items[:500]
    else:
        print(f"Warning: only {len(items)} unique entries (target 500)")

    with open(WORDS_PATH, "w", encoding="utf-8") as f:
        json.dump(items, f, ensure_ascii=False, indent=2)

    from collections import Counter
    c = Counter(e["Level"] for e in items)
    print(f"Total: {len(items)}")
    for lv in ["A1","A2","B1","B2","C1","C2"]:
        print(f"  {lv}: {c.get(lv,0)}")

if __name__ == "__main__":
    main()
