# -*- coding: utf-8 -*-
import json
import os

data = []

def add(cat, items):
    for en, zh in items:
        data.append({
            'id': len(data) + 1,
            'en': en.strip(),
            'zh': zh.strip(),
            'category': cat
        })

# 1. 日常問候與道別 (80)
add('日常問候與道別', [
    ('Good morning! How are you doing today?', '早安！你今天過得如何？'),
    ('Good afternoon! It is nice to see you.', '午安！很高興見到你。'),
    ('Good evening! Did you have a good day?', '晚上好！你今天過得順利嗎？'),
    ('How is everything going with you?', '你最近一切都好嗎？'),
    ('How have you been lately?', '你最近過得怎麼樣？'),
    ('Long time no see! What have you been up to?', '好久不見！你最近都在忙什麼？'),
    ('I have not seen you in ages.', '我好久沒見到你了。'),
    ('It is great to see you again after so long.', '隔了這麼久再次見到你真好。'),
    ('What is new with you?', '最近有什麼新鮮事嗎？'),
    ('Not much, just the usual routine.', '沒什麼特別的，就跟平常一樣。'),
    ('Same old, same old.', '老樣子，都沒變。'),
    ('I could not be better, thank you!', '我好得不能再好了，謝謝！'),
    ('I have been keeping really busy with work.', '我最近工作一直很忙。'),
    ('How is your family doing these days?', '你的家人最近都好嗎？'),
    ('Give my best regards to your parents.', '代我向你的父母問好。'),
    ('Tell everyone I said hello.', '幫我向大家問好。'),
    ('I hope you are having a wonderful day.', '希望你今天過得很美好。'),
    ('Have a fantastic weekend ahead!', '祝你有個愉快的週末！'),
    ('I need to get going now.', '我現在得先離開了。'),
    ('I should probably head home now.', '我想我該回家了。'),
    ('It was really great catching up with you.', '跟你敘舊真的很開心。'),
    ('Thank you for taking the time to meet with me.', '謝謝你抽空與我見面。'),
    ('Let us keep in touch more often.', '我們多保持聯絡喔。'),
    ('Take good care of yourself.', '好好照顧自己，保重。'),
    ('See you tomorrow morning at work.', '明天早上上班見。'),
    ('Catch you later!', '回頭見！'),
    ('Talk to you soon.', '晚點再跟你聊。'),
    ('Have a safe trip home!', '回家路上小心！'),
    ('I hope you have a safe and pleasant flight.', '祝你旅途平安愉快。'),
    ('Welcome back! How was your vacation?', '歡迎回來！假期玩得愉快嗎？'),
    ('How was your weekend? Did you do anything fun?', '週末過得如何？有做什麼好玩的事嗎？'),
    ('I am glad we bumped into each other today.', '很高興今天碰巧遇見你。'),
    ('What a small world to run into you here!', '在這裡遇到你，世界真小！'),
    ('I hope to see you again very soon.', '希望很快能再見到你。'),
    ('Enjoy the rest of your afternoon.', '祝你有個愉快的下午時光。'),
    ('Have a pleasant evening with your family.', '祝你和家人度過一個愉快的夜晚。'),
    ('Good luck with your interview tomorrow!', '祝你明天的面試一切順利！'),
    ('I will see you at the party tonight.', '我們今晚派對上見。'),
    ('Drop by anytime you are in the neighborhood.', '只要你來這附近，隨時過來坐坐。'),
    ('Send me a message whenever you arrive.', '你一抵達就傳個訊息給我。'),
    ('Let me know when you get home safely.', '安全到家後跟我說一聲。'),
    ('I will call you as soon as I am free.', '我有空時會馬上打給你。'),
    ('It has been a pleasure talking with you.', '很高興能與您交談。'),
    ('I am looking forward to our next get-together.', '我很期待我們下次的聚會。'),
    ('Time really flies when you are having fun.', '玩得開心時時間真的過得好快。'),
    ('I must run, or I will be late for my appointment.', '我得趕緊走了，不然約會要遲到了。'),
    ('Do not be a stranger!', '別斷了聯絡喔！'),
    ('Keep me posted on any new developments.', '有任何新進展請隨時通知我。'),
    ('I am so happy that we finally met.', '我很高興我們終於見面了。'),
    ('Please say hi to your sister for me.', '請代我向你妹妹問好。'),
    ('I will be thinking of you during your exam.', '你考試時我會為你加油祈禱的。'),
    ('Stay warm in this cold weather.', '天氣冷，要穿暖和一點喔。'),
    ('Stay safe and take it easy.', '注意安全，放輕鬆。'),
    ('I hope everything turns out well for you.', '希望你的一切都順利。'),
    ('Have fun and enjoy yourself tonight!', '今晚好好玩，玩得盡興！'),
    ('Let us grab lunch sometime next week.', '下週找時間一起吃個午餐吧。'),
    ('I will text you the details later tonight.', '我今晚晚點會把細節傳訊息給你。'),
    ('It is always nice running into you.', '每次遇到你都很高興。'),
    ('I have got to run, but let us talk soon.', '我得先走了，我們很快再聊。'),
    ('Take your time and have a good rest.', '別著急，好好休息一下。'),
    ('Good night! Sleep well and sweet dreams.', '晚安！睡個好覺，祝好夢。'),
    ('Early to bed, early to rise makes a man healthy.', '早睡早起身體好。'),
    ('How are you feeling this morning?', '你今天早上感覺如何？'),
    ('Are you ready for another productive day?', '準備好迎接充實的一天了嗎？'),
    ('May you have a wonderful and fruitful day.', '願你有美好且收穫滿滿的一天。'),
    ('See you next Monday at the office.', '下週一辦公室見。'),
    ('Have a lovely time with your friends.', '和朋友們玩得開心點。'),
    ('Please excuse me, I need to take this phone call.', '不好意思，我需要接這通電話。'),
    ('I am heading out now. See you all later!', '我現在要出發了。待會見大家！'),
    ('It is high time I left for the train station.', '我該出發去火車站了。'),
    ('Thank you for coming all the way to see me.', '謝謝你特地遠道而來看我。'),
    ('I wish you the best of luck in your new job.', '祝你在新工作上一帆風順。'),
    ('Congratulations on your graduation!', '恭喜你順利畢業！'),
    ('Best wishes for a bright and successful future.', '祝你未來光明璀璨、事業成功。'),
    ('Happy birthday! May all your wishes come true.', '生日快樂！願你所有的願望都能成真。'),
    ('Merry Christmas and a Happy New Year!', '聖誕快樂，新年快樂！'),
    ('I will see you right after the holidays.', '假期結束後我們立刻見。'),
    ('Let us meet up again before the month ends.', '我們月底前再聚一次吧。'),
    ('Take care until we meet again.', '在我們下次見面前多保重。'),
    ('Farewell for now, my dear friend.', '暫別了，我親愛的朋友。')
])

# 2. 社交閒聊與介紹 (80)
add('社交閒聊與介紹', [
    ('Allow me to introduce myself. My name is Alex.', '請允許我自我介紹，我叫 Alex。'),
    ('Nice to meet you. I have heard a lot about you.', '很高興認識你，我久仰您的大名。'),
    ('This is my close friend, Sarah from college.', '這是我的大學摯友 Sarah。'),
    ('Where are you from originally?', '你原本是哪裡人呢？'),
    ('I was born and raised in Taipei.', '我在台北土生土長。'),
    ('What do you do for a living?', '你是做什麼行業的？'),
    ('I work as a software engineer at a tech firm.', '我在一家科技公司擔任軟體工程師。'),
    ('How long have you been living in this city?', '你在這座城市住多久了？'),
    ('I have been living here for about three years.', '我在這裡住了大約三年。'),
    ('What do you like to do in your spare time?', '你平時空閒時喜歡做些什麼？'),
    ('I enjoy hiking and photography on weekends.', '我週末喜歡去健行和拍照攝影。'),
    ('Do you have any hobbies or special interests?', '你有什麼興趣愛好或特殊專長嗎？'),
    ('I love reading books and listening to podcasts.', '我喜歡看書和聽播客節目。'),
    ('Are you a coffee person or a tea person?', '你是咖啡派還是喝茶派？'),
    ('I cannot start my morning without a cup of coffee.', '我早上要是沒喝杯咖啡就無法開工。'),
    ('What kind of music do you listen to the most?', '你平時最常聽哪種類型的音樂？'),
    ('I listen to a wide variety of music genres.', '我聽各種類型的音樂，範圍很廣。'),
    ('Have you seen any good movies recently?', '你最近有看過什麼好看的電影嗎？'),
    ('The weather is absolutely gorgeous today, is not it?', '今天的天氣真是棒極了，不是嗎？'),
    ('It looks like it might rain later this afternoon.', '看起來今天下午晚點可能會下雨。'),
    ('Do you have any plans for the upcoming holiday?', '即將到來的連假你有什麼計畫嗎？'),
    ('I plan to travel to Japan with my family.', '我打算和家人一起去日本旅遊。'),
    ('That sounds like an amazing destination.', '那聽起來是個很棒的旅遊地點。'),
    ('Have you ever traveled to Europe before?', '你以前去過歐洲旅遊嗎？'),
    ('Yes, I visited Paris and London two years ago.', '有的，我兩年前去過巴黎和倫敦。'),
    ('What is your favorite type of food?', '你最喜歡吃哪種類型的食物？'),
    ('I am a huge fan of Italian and Japanese cuisine.', '我是義大利料理和日本料理的忠實粉絲。'),
    ('Do you know any good restaurants around here?', '你熟悉這附近有什麼好吃的餐廳嗎？'),
    ('There is a fantastic noodle shop just around the corner.', '轉角就有一家非常棒的麵店。'),
    ('How did you two get to know each other?', '你們兩個當初是怎麼認識的？'),
    ('We actually met through a mutual friend at a party.', '我們其實是在一個派對上透過共同朋友認識的。'),
    ('You look very familiar to me. Have we met before?', '你看起來很面熟，我們以前見過嗎？'),
    ('I think we met at the technology conference last year.', '我想我們去年在科技研討會上見過。'),
    ('How do you find the life in this new neighborhood?', '你覺得新社區的生活適應得如何？'),
    ('It is very convenient and peaceful around here.', '這裡的生活非常便利而且很幽靜。'),
    ('Do you have any pets at home?', '你家裡有養任何寵物嗎？'),
    ('I have a golden retriever named Max.', '我養了一隻名叫 Max 的黃金獵犬。'),
    ('Dogs are always such loyal and joyful companions.', '狗總是這麼忠誠又讓人感到快樂的伴侶。'),
    ('Are you into outdoor activities or staying indoors?', '你喜歡戶外活動還是宅在家裡？'),
    ('I prefer staying at home and watching movies.', '我比較喜歡待在家看電影放鬆。'),
    ('What is your favorite season of the year?', '一年四季中你最喜歡哪個季節？'),
    ('I love autumn because the breeze is cool and pleasant.', '我最愛秋天，因為微風涼爽又舒服。'),
    ('Winter in the mountains can get quite chilly.', '山裡的冬天有時候會變得非常寒冷。'),
    ('Did you watch the basketball game last night?', '你昨晚有看那場籃球比賽嗎？'),
    ('The final two minutes were so thrilling and intense!', '最後兩分鐘實在太扣人心弦、太刺激了！'),
    ('Who is your favorite sports team or player?', '你最支持的運動隊伍或選手是誰？'),
    ('I have been following tennis championships for years.', '我關注網球錦標賽已經很多年了。'),
    ('Do you play any musical instruments?', '你會彈奏任何樂器嗎？'),
    ('I used to play the piano when I was in high school.', '我高中的時候曾經學過彈鋼琴。'),
    ('Playing music is a wonderful way to relieve stress.', '演奏音樂是紓解壓力的極佳方式。'),
    ('Do you follow any interesting content creators online?', '你在網路上有追蹤什麼有趣的創作者嗎？'),
    ('I follow several cooking and travel channels.', '我追蹤了幾個料理烹飪和旅遊頻道。'),
    ('Cooking at home helps me unwind after a long day.', '忙碌了一天後，在家下廚能讓我徹底放鬆。'),
    ('What kind of books do you usually enjoy reading?', '你平時通常喜歡閱讀什麼類型的書？'),
    ('I enjoy biographies and self-development books.', '我喜歡讀傳記和個人成長勵志類的書籍。'),
    ('Reading expands our horizons in unexpected ways.', '閱讀能以意想不到的方式拓展我們的視野。'),
    ('Have you tried the new bakery down the street?', '你吃過這條街走下去那家新開的烘焙坊了嗎？'),
    ('Their freshly baked sourdough bread is delicious.', '他們新鮮出爐的酸種麵包非常美味。'),
    ('I am always on the lookout for good cafes with Wi-Fi.', '我總是在尋找有 Wi-Fi 的好咖啡廳。'),
    ('A quiet workspace can really boost productivity.', '一個安靜的工作環境確實能大幅提升工作效率。'),
    ('How do you manage to balance work and personal life?', '你是如何兼顧工作與個人生活的？'),
    ('Setting clear boundaries after work hours helps a lot.', '下班後設定明確的界線對我很有幫助。'),
    ('Exercise in the morning gives me energy for the day.', '早晨運動能帶給我一整天滿滿的活力。'),
    ('I try to drink at least two liters of water daily.', '我每天盡量喝至少兩公升的水。'),
    ('It is important to stay hydrated throughout the day.', '整天保持充足的水分攝取非常重要。'),
    ('Do you have any brothers or sisters?', '你有兄弟姊妹嗎？'),
    ('I have an elder brother and a younger sister.', '我有一個哥哥和一個妹妹。'),
    ('Having siblings always makes childhood lively.', '有兄弟姊妹總會讓童年充滿熱鬧與樂趣。'),
    ('Where did you grow up during your childhood?', '你小時候是在哪裡長大的？'),
    ('I grew up in a lovely small coastal town.', '我是在一座可愛的沿海小鎮長大的。'),
    ('Living near the ocean must have been relaxing.', '住在海邊身心一定感到非常放鬆。'),
    ('Do you prefer living in big cities or quiet towns?', '你比較偏好住在大都市還是幽靜的小市鎮？'),
    ('I appreciate the convenience that metropolitan cities offer.', '我很欣賞大都會城市所帶來的便利性。'),
    ('Public transportation here is remarkably efficient.', '這裡的大眾運輸系統非常有效率。'),
    ('It only takes twenty minutes to commute to my office.', '我通勤到辦公室只需要花二十分鐘。'),
    ('A short commute definitely saves a lot of energy.', '短暫的通勤時間絕對能節省很多精力。'),
    ('What are your main goals for this year?', '你今年最主要的目標是什麼？'),
    ('I want to master spoken English and get in good shape.', '我想練好英語口說並且維持好體態。'),
    ('Consistency is the key to achieving any ambitious goal.', '持之以恆是達成任何遠大目標的關鍵。'),
    ('I truly believe you can accomplish whatever you set your mind to.', '我深信只要你下定決心，一定能夠達成。')
])

# 3. 感謝致歉與禮貌 (80)
add('感謝致歉與禮貌', [
    ('Thank you so much for your kind assistance.', '非常感謝您親切的協助。'),
    ('I really appreciate everything you have done for me.', '我真的很感激你為我所做的一切。'),
    ('You are more than welcome to stay with us.', '非常歡迎你來和我們一起住。'),
    ('Do not mention it; it was truly my pleasure.', '別客氣，這真的是我的榮幸。'),
    ('It is no trouble at all, please do not hesitate to ask.', '一點也不麻煩，請隨時開口。'),
    ('I am deeply grateful for your continuous encouragement.', '我對你不斷的鼓勵深表感激。'),
    ('I truly owe you a huge favor for this.', '因為這件事我真的欠你一個大人情。'),
    ('I cannot thank you enough for saving my presentation.', '我真不知道該如何感謝你拯救了我的簡報。'),
    ('That is extremely thoughtful and kind of you.', '你真是太體貼、太善解人意了。'),
    ('I apologize for interrupting your conversation.', '很抱歉打擾了你們的對話。'),
    ('Excuse me, could you please point me in the right direction?', '不好意思，能請您指引我正確的方向嗎？'),
    ('I am terribly sorry for keeping you waiting so long.', '讓您等了這麼久，我真的感到非常抱歉。'),
    ('Please accept my sincere apologies for the oversight.', '對於這次的疏失，請接受我誠摯的歉意。'),
    ('I promise this kind of mistake will not occur again.', '我保證這種錯誤不會再次發生。'),
    ('No worries at all; mistakes happen to everyone.', '完全沒關係，每個人都會犯錯的。'),
    ('Never mind, everything worked out fine in the end.', '沒關係，最後一切都很順利解決了。'),
    ('Could you possibly do me a small favor?', '能請你幫我一個小忙嗎？'),
    ('Would you mind passing the salt and pepper, please?', '能否請你把鹽和胡椒粉遞給我呢？'),
    ('Of course not, here you go.', '當然可以，拿去吧。'),
    ('Thank you for being so patient and understanding with me.', '感謝您對我如此有耐心與體諒。'),
    ('Pardon me, did you drop this wallet on the floor?', '不好意思，這個掉在地上的皮夾是您的嗎？'),
    ('I am sorry to take up so much of your valuable time.', '很抱歉佔用了您這麼多寶貴的時間。'),
    ('You have been a tremendous help during this project.', '在這個專案進行期間，你給了我極大的幫助。'),
    ('I cannot tell you how much your support means to me.', '我無法言語你的支持對我有多麼重要。'),
    ('Thanks a million for lending me your car yesterday.', '萬分感謝你昨天把車子借給我開。'),
    ('Please excuse my late reply; my inbox was flooded.', '請原諒我晚回信，我的收件匣信件滿了。'),
    ('I hope I did not cause you any inconvenience.', '希望我沒有造成您的任何困擾或不便。'),
    ('It was entirely my fault, and I take full responsibility.', '這完全是我的錯，我會承擔全部責任。'),
    ('Let me make it up to you by treating you to dinner.', '讓我請你吃頓晚餐來補償你吧。'),
    ('You really did not have to bring a gift, but thank you!', '你真的不必特地帶禮物來的，但還是非常感謝！'),
    ('That is very generous of you to offer such help.', '你能提供這樣的幫助實在是太慷慨了。'),
    ('I am so glad I could be of some service to you.', '很高興能為您提供一些微薄的協助。'),
    ('May I trouble you to repeat what you just said?', '能麻煩您重複一下剛剛說的話嗎？'),
    ('Excuse me, is this seat taken by anyone?', '不好意思，請問這個座位有人坐嗎？'),
    ('Not at all, please feel free to sit down.', '沒有人坐，請隨意坐下。'),
    ('I am deeply sorry for any misunderstanding between us.', '對於我們之間的任何誤會，我深表歉意。'),
    ('Thank you for reminding me about the deadline.', '謝謝你提醒我關於截止日期的事。'),
    ('Your timely feedback was invaluable to our success.', '你及時的回饋對我們的成功至關重要。'),
    ('I appreciate your honesty and candid feedback.', '我很感謝你的誠實與坦率的意見反饋。'),
    ('Sorry for the mess; I am currently reorganizing my room.', '不好意思家裡有點亂，我目前正在整理房間。'),
    ('Thank you for hosting such a wonderful dinner party.', '謝謝你舉辦了這麼棒的晚餐派對招待我們。'),
    ('Your hospitality was beyond what we could have hoped for.', '您的熱情好客遠遠超乎我們的預期。'),
    ('I hope I am not intruding on your private time.', '希望我沒有侵犯到您的私人時間。'),
    ('Please allow me to carry that heavy bag for you.', '請讓我幫您提那個沉重的袋子吧。'),
    ('That is very sweet of you, thank you so much.', '你真是太貼心了，非常感謝你。'),
    ('I am sorry for speaking out of turn during the meeting.', '很抱歉剛才開會時我未依序發言。'),
    ('Thank you for guiding me step by step through the process.', '謝謝你一步一步引導我完成整個流程。'),
    ('I will forever cherish your words of wisdom.', '我會永遠珍藏您充滿智慧的教誨。'),
    ('Please forgive me for not replying to your message earlier.', '請原諒我沒有更早回覆你的訊息。'),
    ('I appreciate your flexibility in adjusting the schedule.', '非常感謝您在調整行程時間上的彈性配合。'),
    ('Thank you for taking care of my plants while I was away.', '謝謝你在我出遠門時幫忙照顧我的盆栽。'),
    ('It was the least I could do for a good neighbor like you.', '對你這樣的好鄰居來說，這是我微不足道的心意。'),
    ('Excuse me, do you have a minute to answer a quick question?', '不好意思，請問您有一分鐘能回答個簡短問題嗎？'),
    ('Sure, I would be happy to answer your question.', '當然可以，我很樂意回答你的問題。'),
    ('I am grateful for the opportunity to work alongside you.', '我非常感激能有機會與您一同共事。'),
    ('Thank you for sharing your expertise with our team.', '感謝您與我們團隊分享您的專業知識。'),
    ('I apologize if my tone sounded harsh earlier.', '如果我剛才的語氣聽起來有些嚴厲，我向您致歉。'),
    ('No offense taken at all; we were just debating ideas.', '完全沒放在心上，我們只是在討論不同的想法。'),
    ('Thank you for standing by me when times were tough.', '謝謝你在艱難的時刻依然陪在我的身邊。'),
    ('Your loyalty and friendship mean the world to me.', '你的忠誠與友誼對我而言意味著一切。'),
    ('Please accept our condolences during this difficult time.', '在這艱難的時刻，請接受我們誠摯的哀悼與慰問。'),
    ('Thank you for your warm words of comfort.', '謝謝你溫暖而撫慰人心的話語。'),
    ('I am sorry to hear that your vacation was canceled.', '聽說你的假期取消了，我感到很遺憾。'),
    ('Thank you for looking after my dog during the holidays.', '謝謝你在假期期間幫忙照看我的愛犬。'),
    ('It was no trouble at all; he was well behaved.', '一點都不麻煩，牠表現得非常乖巧。'),
    ('I appreciate your willingness to compromise on this issue.', '我非常欣賞您在這個議題上願意做出妥協的態度。'),
    ('Thank you for recommending such a wonderful book to me.', '謝謝你向我推薦了這麼一本精彩的好書。'),
    ('I am glad you found the reading enjoyable.', '很高興你覺得這本書讀起來很享受。'),
    ('Excuse me for arriving a few minutes behind schedule.', '很抱歉我比預定時間晚到了幾分鐘。'),
    ('Do not worry about it; we just started a moment ago.', '別擔心，我們也才剛剛開始一會兒。'),
    ('Thank you for your cooperation and timely response.', '感謝您的合作與及時的回覆。'),
    ('We could not have met the deadline without your contribution.', '若沒有您的貢獻，我們無法及時趕上截止日。'),
    ('I am grateful for your constructive criticism.', '我由衷感謝您提出建設性的批評與建議。'),
    ('It will definitely help me improve my work.', '這絕對會幫助我在工作表現上更進一步。'),
    ('Thank you for believing in me when I doubted myself.', '謝謝你在我自我懷疑時依然選擇相信我。'),
    ('Your encouraging words gave me the courage to move forward.', '你鼓勵的話語給了我繼續向前邁進的勇氣。'),
    ('I apologize for any confusion caused by my instructions.', '對於我的指示所造成的任何困惑，我深感抱歉。'),
    ('Let me clarify the steps so everyone is on the same page.', '讓我重新說明步驟，好讓大家的理解保持一致。'),
    ('Thank you for being such an extraordinary role model.', '謝謝您成為如此傑出的模範榜樣。'),
    ('I truly appreciate the time and effort you invested.', '我真的非常感謝您所投入的時間與心力。')
])

# 4. 情感感受與心情 (80)
add('情感感受與心情', [
    ('I am over the moon about getting accepted into my dream university.', '得知被理想的大學錄取，我簡直欣喜若狂。'),
    ('I feel so exhausted and completely burned out from overworking.', '過度加班讓我感到身心俱疲，徹底燃燒殆盡。'),
    ('I have been under an immense amount of pressure lately.', '我最近一直承受著巨大的壓力。'),
    ('Do not let minor setbacks discourage you from trying.', '別讓微小的挫折阻止你繼續嘗試的腳步。'),
    ('Keep your chin up; brighter days are just around the corner.', '振作起來，美好的日子就在前方不遠處。'),
    ('I am so proud of how far you have come this year.', '我為你今年所取得的進步深感驕傲。'),
    ('That concert was an unforgettable and exhilarating experience.', '那場演唱會是一次令人難忘又心潮澎湃的體驗。'),
    ('I felt a tremendous wave of relief after hearing the test results.', '聽到檢驗結果後，我感到如釋重負。'),
    ('Her heartfelt speech brought tears of joy to my eyes.', '她發自內心的感人演講讓我流下了喜悅的淚水。'),
    ('I always get butterflies in my stomach before a big presentation.', '重大簡報之前，我心裡總是會七上八下緊張不已。'),
    ('Take a slow, deep breath to calm your racing nerves.', '慢慢深呼吸，平復你緊繃急促的神經。'),
    ('I am eagerly anticipating our upcoming summer road trip.', '我滿懷期待著我們即將到來的夏日公路旅行。'),
    ('I could hardly believe my eyes when I saw the spectacular view.', '當我看到那壯麗絕倫的景色時，簡直不敢相信自己的眼睛。'),
    ('What a delightful surprise to find a present on my desk!', '在辦公桌上發現禮物，真是個令人驚喜的巧思！'),
    ('I am feeling a little under the weather with a sore throat.', '我今天喉嚨有點痛，感覺身體不太舒服。'),
    ('I am sick and tired of staying indoors on rainy weekends.', '我受夠了下雨的週末只能一直待在室內。'),
    ('It is such a comfort to know that true friends have your back.', '知道有真摯的朋友在背後支持你，是多麼令人心安的事。'),
    ('The loud thunderclaps startled me out of my deep sleep.', '巨大的雷聲把剛陷入熟睡的我猛然嚇醒。'),
    ('I woke up feeling energetic and ready to conquer the world.', '我一早醒來感到活力充沛，準備好征服世界。'),
    ('Do not dwell on past mistakes that you cannot change.', '不要老是糾結在那些已經無法改變的過往錯誤上。'),
    ('I feel so grateful for all the blessings in my daily life.', '我對日常生活中所擁有的一切恩惠心懷感激。'),
    ('Loneliness can sometimes feel heavy, but it also allows self-reflection.', '孤獨有時顯得沉重，但也給了我們自我反思的空間。'),
    ('I was absolutely astonished by the magician impressive tricks.', '我被魔術師那令人驚嘆的魔術徹底震懾住了。'),
    ('She was visibly shaken after witnessing the car accident.', '目睹了那場車禍後，她明顯受到了極大的驚嚇。'),
    ('Hearing my favorite childhood song filled me with nostalgia.', '聽到童年最愛的歌曲，讓我心中泛起滿滿的懷舊之情。'),
    ('I am so thrilled that we won the regional championship trophy.', '贏得區域錦標賽冠軍獎盃，我們大家都興奮極了。'),
    ('He felt deeply humiliated by the unfair criticism.', '面對那種不公的批評，他感到非常難堪與受辱。'),
    ('It breaks my heart to see stray animals suffering in the cold.', '看見流浪動物在寒冬中受苦受難，令我心碎不已。'),
    ('Her infectious laughter always brightens up the entire room.', '她富有感染力的笑聲總是能點亮整間房間的氛圍。'),
    ('I am so annoyed by the constant construction noise outside.', '窗外持續不斷的施工噪音讓我煩躁不已。'),
    ('Peace of mind is far more valuable than material possessions.', '心靈的平靜遠比物質的財富來得更有價值。'),
    ('I felt a sudden surge of inspiration to write a new poem.', '我心中突然湧起一股想要創作新詩的靈感衝動。'),
    ('We were overwhelmed with gratitude by the community generous donations.', '社區慷慨解囊的善心捐款讓我們感激得不知所措。'),
    ('I am curious to learn how this intricate machine operates.', '我對這台精密複雜的機器是如何運轉的感到非常好奇。'),
    ('He was consumed by jealousy when his rival received the promotion.', '當競爭對手獲得升遷時，他內心充滿了嫉妒。'),
    ('Nothing beats the sheer joy of adopting a playful puppy.', '沒有什麼比領養一隻活潑愛玩的小狗更能帶來純粹的快樂了。'),
    ('I felt awkward when I forgot my new colleague name.', '當我忘記新同事的名字時，場面瞬間顯得有些尷尬。'),
    ('She looked radiant and glowing on her memorable wedding day.', '在難忘的婚禮當天，她看起來容光煥發、光彩照人。'),
    ('I am anxious about moving to a foreign country all alone.', '獨自一人搬到異國他鄉生活讓我感到相當焦慮。'),
    ('Surrounding yourself with positive people makes a tremendous difference.', '讓自己身處積極樂觀的人群身邊會帶來巨大的轉變。'),
    ('His words gave me a deep sense of security and belonging.', '他的話語給予了我深沉的安全感與歸屬感。'),
    ('I feel bitter about the unfair treatment I received at work.', '對於在職場上遭遇的不公對待，我內心感到憤憤不平。'),
    ('Gratitude turns what we have into more than enough.', '懂得感恩能讓我們所擁有的變得綽綽有餘。'),
    ('I felt helpless when my computer crashed with unsaved work.', '電腦在未存檔的情況下當機時，我感到無比的無助。'),
    ('Seeing the sunset over the horizon filled my heart with peace.', '看著地平線上緩緩落下的夕陽，我的內心充滿了平靜。'),
    ('She was terrified of heights, yet she climbed to the peak.', '她雖然非常懼高，但依然憑著毅力登上了頂峰。'),
    ('I feel so content sitting by the fireplace with a hot cocoa.', '捧著一杯熱可可坐在壁爐旁，讓我感到無比的滿足與愜意。'),
    ('Disappointment is inevitable, but resilience helps us bounce back.', '失望在所難免，但堅韌的毅力能幫助我們重新振作。'),
    ('I felt deeply sympathetic toward his unfortunate situation.', '對於他不幸的處境，我深表同情與體恤。'),
    ('He was overflowing with enthusiasm for the brand-new startup project.', '他對這個全新的創業專案充滿了無窮的熱情與幹勁。'),
    ('A sense of wonder washed over me as I gazed at the starry sky.', '當我仰望繁星點點的夜空時，心中湧現出一股驚奇之感。'),
    ('I am tired of pretending everything is okay when it is not.', '我受夠了在明明不順心時還要假裝一切都很好的樣子。'),
    ('Finding a kind stranger returning my lost phone restored my faith in humanity.', '好心的陌生人送還我遺失的手機，讓我重拾對人性的信心。'),
    ('She felt heartbroken when her favorite pet passed away.', '當心愛的寵物離世時，她感到肝腸寸斷。'),
    ('A warm shower at night melts away all the accumulated stress.', '夜晚洗個熱水澡能融化一整天累積的所有壓力。'),
    ('I am fascinated by how different cultures celebrate traditional holidays.', '我對不同文化如何慶祝傳統節日感到深深著迷。'),
    ('He felt guilty for forgetting his mother birthday celebration.', '因為忘記了母親的生日慶祝，他內心充滿了內疚。'),
    ('The beauty of cherry blossoms blooming in spring is breathtaking.', '春天櫻花盛開的唯美景致令人屏息讚嘆。'),
    ('I was filled with apprehension before hearing the medical diagnosis.', '在聽取醫師的醫療診斷前，我心中充滿了忐忑不安。'),
    ('Laughter is truly the best medicine for a troubled mind.', '笑聲確實是治癒煩悶心靈的最佳良藥。'),
    ('I feel completely rejuvenated after a week-long nature retreat.', '經過一週的大自然靜修後，我感覺整個人煥然一新。'),
    ('His constant complaints are beginning to drain my energy.', '他沒完沒了的抱怨已經開始消耗我的正能量了。'),
    ('I was touched by the generous support shown by my neighbors.', '鄰居們展現出的慷慨支持深深打動了我的心。'),
    ('Fear is only as deep as your mind allows it to be.', '恐懼的深度，完全取決於你的心靈給予它多少空間。'),
    ('I feel ecstatic about winning two tickets to the world tour.', '抽中世界巡迴演唱會的兩張門票，我簡直高興瘋了。'),
    ('He had mixed feelings about leaving his hometown for college.', '離鄉背井去念大學，他內心充滿了五味雜陳的複雜情緒。'),
    ('A sincere smile can instantly break down barriers between strangers.', '一個真誠的微笑能瞬間打破陌生人間的隔閡與防備。'),
    ('I am amazed at how rapidly children learn new languages.', '看著孩子們學習新語言的速度如此飛快，我感到驚奇不已。'),
    ('She was distressed by the news of impending job cuts.', '聽到即將裁員的消息，她感到十分焦慮與憂心忡忡。'),
    ('Cultivating patience is an essential virtue for personal peace.', '培養耐心是獲得內心平靜不可或缺的美德。'),
    ('I felt a rush of adrenaline as the rollercoaster dropped.', '雲霄飛車俯衝直下時，我感到腎上腺素瞬間狂飆。'),
    ('He was full of remorse for his thoughtless remarks.', '他為自己未經深思熟慮的輕率言論深表悔恨。'),
    ('There is immense satisfaction in completing a difficult puzzle.', '完成一幅難度極高的拼圖會帶來莫大的成就感與滿足。'),
    ('I felt uneasy walking through the dimly lit alley alone.', '獨自走過昏暗的小巷讓我心裡感到有些不安。'),
    ('Hope is the anchor of the soul during turbulent storms.', '在狂風暴雨中，希望是心靈最穩固的錨。'),
    ('Her encouraging compliment gave me a massive boost in self-confidence.', '她鼓勵的讚美給了我的自信心極大的提升。'),
    ('I am disgusted by dishonesty and deceit in relationships.', '我極度厭惡人際關係中的不誠實與欺騙行為。'),
    ('He felt triumphant after crossing the marathon finish line.', '跨越馬拉松終點線的那一刻，他感到無比的勝利與自豪。'),
    ('A grateful heart is a magnet for miracles and joy.', '一顆常懷感恩的心，是吸引奇蹟與喜悅的磁鐵。'),
    ('May you always find peace and serenity in your daily journey.', '願你在日常的旅程中總能尋得平靜與安詳。')
])

# 5. 觀點看法與贊同 (80)
add('觀點看法與贊同', [
    ('In my opinion, investing in renewable energy is essential.', '依我看，投資再生能源至關重要。'),
    ('From my point of view, communication is the foundation of any team.', '從我的觀點來看，溝通是任何團隊協作的基石。'),
    ('I completely agree with what you just pointed out.', '我完全贊同你剛剛所指出的觀點。'),
    ('You took the words right out of my mouth!', '你正好說出了我想說的話！'),
    ('I could not agree with you more on this matter.', '在這件事上我完全不能同意你更多了。'),
    ('That is a very valid point that deserves careful consideration.', '那是個非常合理的論點，值得仔細考量。'),
    ('I see what you mean, but look at it from another angle.', '我懂你的意思，但換個角度看呢？'),
    ('I am afraid I have to respectfully disagree with that idea.', '恐怕我必須帶著敬意對這個想法持不同意見。'),
    ('I have mixed feelings about implementing that new company policy.', '對於推行那項新公司政策，我內心抱持著複雜的看法。'),
    ('To be completely honest, I have some serious doubts about the proposal.', '老實說，我對這份提案存有相當大的疑慮。'),
    ('As far as I am concerned, quality should always come before speed.', '就我而言，品質永遠應該放在速度之前。'),
    ('There is no doubt that artificial intelligence is transforming society.', '毫無疑問，人工智慧正在重塑整個社會架構。'),
    ('It is obvious that we need to adjust our marketing strategy.', '很顯然地，我們需要調整我們的行銷策略。'),
    ('I think we should weigh the pros and cons before deciding.', '我認為在做決定之前，我們應該權衡利弊得失。'),
    ('That makes a whole lot of sense to me.', '這對我來說非常合乎邏輯、很有道理。'),
    ('I believe everyone has the right to express their own opinion.', '我相信每個人都有權利表達自己的意見看法。'),
    ('Let us agree to disagree and move on to the next topic.', '讓我們保留各自的歧見，進入下一個討論主題吧。'),
    ('You hit the nail right on the head with that summary.', '你的總結真是一針見血、切中要害。'),
    ('I am inclined to believe that this method is more efficient.', '我比較傾向相信這種方法更有效率。'),
    ('What are your thoughts regarding the newly proposed timeline?', '針對新提出的時間表，你有什麼想法或看法？'),
    ('I think it is a step in the right direction.', '我認為這朝著正確的方向邁出了一步。'),
    ('We need to look at the bigger picture here.', '在這種情況下，我們需要著眼於更宏觀的大局。'),
    ('I understand your perspective, but cost is a major constraint.', '我理解你的觀點，但預算成本是一大主要限制。'),
    ('That sounds reasonable in theory, but how about in practice?', '這在理論上聽起來很合理，但在實務上可行嗎？'),
    ('I am on the fence about whether we should expand overseas.', '對於我們是否該拓展海外業務，我目前抱持中立觀望。'),
    ('My gut feeling tells me that this is a golden opportunity.', '我的直覺告訴我這是一個千載難逢的絕佳機會。'),
    ('It goes without saying that health is our greatest wealth.', '不言而喻，健康是我們最大的財富。'),
    ('I am convinced that hard work and perseverance always pay off.', '我堅信努力工作與堅持不懈終究會帶來回報。'),
    ('That is exactly how I feel about the current situation.', '那正是我對目前現況的真實感受與看法。'),
    ('We cannot ignore the potential risks involved in this venture.', '我們絕不能忽視這項投資冒險所蘊含的潛在風險。'),
    ('I support your decision one hundred percent.', '我百分之百全力支持你所做的決定。'),
    ('Let us take a step back and re-evaluate our main priorities.', '讓我們退一步，重新評估我們最重要的優先事項。'),
    ('It seems to me that we are overlooking a critical detail.', '在我看來，我們似乎忽略了一個至關重要的細節。'),
    ('I share your optimism about the future of green technology.', '我同你一樣對綠色科技的未來抱持著樂觀態度。'),
    ('That is not necessarily true in all circumstances.', '在所有情況下，那倒也不見得一定是對的。'),
    ('I think we should keep an open mind to novel ideas.', '我認為我們應該對新穎的想法保持開放包容的心態。'),
    ('His argument is backed up by solid empirical evidence.', '他的論點有著扎實的實證數據作為強力後盾。'),
    ('I think you are overestimating the difficulty of the task.', '我認為你過度高估了這項任務的困難程度。'),
    ('We are definitely on the same page regarding core values.', '在核心價值觀方面，我們的想法絕對是高度一致的。'),
    ('I would argue that prevention is always better than cure.', '我認為預防永遠勝於治療。'),
    ('That is a brilliant suggestion that solves our bottleneck.', '那是個絕妙的建議，解決了我們目前的瓶頸難題。'),
    ('I am skeptical about the promises made in the advertisement.', '我對廣告中所做出的誇大承諾抱持懷疑態度。'),
    ('In summary, the benefits far outweigh the initial disadvantages.', '總結而言，其帶來的效益遠遠大於最初的缺點。'),
    ('I am completely with you on that particular argument.', '在那個特定的論點上，我完全站在你這邊。'),
    ('We must base our judgment on verified facts rather than rumors.', '我們必須依據查證過的事實而非謠言做出判斷。'),
    ('I hold a completely different view on this controversial issue.', '在這個充滿爭議的議題上，我持有截然不同的觀點。'),
    ('That is a matter of personal preference and taste.', '那純粹是個人偏好與品味的問題。'),
    ('We should encourage constructive dialogue among all stakeholders.', '我們應當鼓勵所有利害關係人間進行建設性的對話。'),
    ('I think we should give his creative idea a fair chance.', '我認為我們應該給他富含創意的點子一個公平嘗試的機會。'),
    ('Experience has taught me that patience yields the best results.', '經驗教會了我：耐心往往能產出最豐碩的成果。'),
    ('You have brought up a crucial aspect that we missed.', '你提出了一個我們之前所遺漏的關鍵面向。'),
    ('I believe mutual respect is the key to lasting partnerships.', '我相信相互尊重是建立長久夥伴關係的關鍵。'),
    ('That is an interesting viewpoint that I had not considered before.', '那是個很有意思的觀點，我之前完全沒想到過。'),
    ('We should strive for a win-win outcome for both parties.', '我們應當致力於為雙方爭取創造雙贏的局面。'),
    ('I do not think blaming each other will solve the problem.', '我不認為互相指責埋怨能解決眼前的問題。'),
    ('Actions speak much louder than empty promises.', '化為實際的行動遠比空洞的承諾來得更有說服力。'),
    ('I am confident that we will find a sensible solution soon.', '我有信心我們很快就能找到一個合情合理的解決方案。'),
    ('His perspective is heavily influenced by his personal background.', '他的觀點很大程度受到了他個人生長背景的影響。'),
    ('We need to remain objective and unbiased during this review.', '在本次審查過程中，我們需要保持客觀與公正無私。'),
    ('I endorse the recommendations made by the advisory committee.', '我完全認可諮詢委員會所提出的各項改善建議。'),
    ('That sounds like a fair compromise for everyone involved.', '這對所有參與其中的人來說聽起來是個公平的折衷方案。'),
    ('I think we are making a mountain out of a molehill.', '我認為我們現在是有點小題大作、大驚小怪了。'),
    ('Honesty and transparency build unshakable trust.', '誠實與公開透明能建立起牢不可破的信任基石。'),
    ('I am in favor of adopting more flexible working arrangements.', '我贊成公司採取更具彈性的混合工作模式。'),
    ('We should take his valuable advice into deep consideration.', '我們應該將他寶貴的忠告納入深入考量。'),
    ('It is crucial that we maintain high ethical standards.', '我們維持嚴謹崇高的道德標準至關重要。'),
    ('I appreciate you pointing out that subtle flaw in my logic.', '很感謝你指出了我邏輯中那個微小不易察覺的漏洞。'),
    ('Education is the most powerful tool to change the world.', '教育是改變世界最強大有力的工具。'),
    ('I believe simplicity is the ultimate sophistication.', '我相信化繁為簡才是極致精妙的精髓所在。'),
    ('We need to adapt quickly to changing market conditions.', '我們必須迅速適應不斷瞬息萬變的市場環境條件。'),
    ('Your feedback has been instrumental in refining our design.', '您的回饋意見在完善我們設計方案的過程中起到了關鍵作用。'),
    ('I disagree with the notion that success is measured only by wealth.', '我不贊同衡量成功與否僅能以財富作為唯一標準的說法。'),
    ('We must cultivate critical thinking skills from an early age.', '我們必須從小就注重培養批判性獨立思考的能力。'),
    ('That approach seems unnecessarily complicated and tedious.', '那種處理方式看起來有些繁瑣複雜且耗時費力。'),
    ('I admire his courage to speak truth to power.', '我非常欽佩他勇於對掌權者直言不諱的道德勇氣。'),
    ('Team cohesion is what propelled us to achieve our milestones.', '團隊強大的凝聚力正是推動我們達成里程碑的動力。'),
    ('We should learn from our failures rather than fear them.', '我們應當從失敗中汲取教訓，而非一味畏懼失敗。'),
    ('A positive attitude can transform a daunting obstacle into an opportunity.', '積極正向的態度能將令人怯步的障礙轉化為絕佳良機。'),
    ('I am firmly convinced of the viability of our business model.', '我對我們商業模式的可行性與前景深信不疑。'),
    ('Let us join forces and make this ambitious vision a reality.', '讓我們齊心協力，將這個宏偉的願景化為現實。')
])

# 6. 餐廳用餐與點餐 (80)
add('餐廳用餐與點餐', [
    ('Good evening. A table for two, please.', '晚安，請幫我們安排兩位的座位。'),
    ('Do you have a reservation under the name Chang?', '請問有訂位紀錄嗎？登記的名字是 Chang。'),
    ('How long is the estimated wait time for a table?', '請問現在等候帶位大約需要多久時間？'),
    ('Could we please have a table near the window?', '能幫我們安排靠窗戶旁邊的座位嗎？'),
    ('May I see the food and drinks menu, please?', '可以請您提供餐點和飲料的菜單給我們看嗎？'),
    ('What are the chef special recommendations today?', '請問主廚今天的特選推薦餐點是什麼？'),
    ('Could you recommend a popular local dish for us?', '能為我們推薦一道道地受歡迎的在地特色菜嗎？'),
    ('I am ready to order my dinner now.', '我現在準備好可以點餐了。'),
    ('I will have the grilled salmon with roasted vegetables.', '我要一份烤鮭魚搭配烘烤時蔬。'),
    ('How would you like your steak cooked? Medium, please.', '請問您的牛排想要幾分熟？請給我五分熟。'),
    ('Does this pasta dish contain any dairy or peanuts?', '這道義大利麵料理含有任何乳製品或花生嗎？'),
    ('I am allergic to shellfish, so please make sure it is safe.', '我對甲殼類海鮮嚴重過敏，請務必幫我確認安全。'),
    ('Could I get the dressing on the side for the salad?', '沙拉的沾醬可以幫我另外分開裝在旁邊嗎？'),
    ('Can I substitute French fries with a fresh green salad?', '我可以把炸薯條更換成新鮮生菜沙拉嗎？'),
    ('What kind of soup do you have available today?', '請問你們今天供應哪種例湯？'),
    ('I will take a glass of red wine and sparkling water.', '我要一杯紅葡萄酒和一杯氣泡水。'),
    ('Could we please have some extra napkins and water?', '可以請您多拿一些餐巾紙和飲用水給我們嗎？'),
    ('Excuse me, this soup is a bit lukewarm; could you heat it?', '不好意思，這碗湯有點溫涼，能幫我加熱一下嗎？'),
    ('This steak is cooked to absolute perfection; compliments to the chef.', '這塊牛排煎得恰到好處、完美無瑕，請轉達我對主廚的讚美。'),
    ('Are you ready for dessert, or would you like coffee?', '您準備好要享用甜點了嗎，還是想來杯咖啡？'),
    ('I will have the chocolate lava cake with vanilla ice cream.', '我要一份熔岩巧克力蛋糕搭配香草冰淇淋。'),
    ('Could we please get the check when you have a moment?', '您有空時，能請幫我們買單結帳嗎？'),
    ('Can we split the bill evenly among the four of us?', '我們四個人可以平均分攤這筆帳單嗎？'),
    ('Do you accept major credit cards or mobile payments?', '請問你們接受主流信用卡或是行動支付嗎？'),
    ('Is service charge or tip already included in the total?', '請問服務費或小費已經包含在總金額裡了嗎？'),
    ('Keep the change; thank you for the wonderful service!', '不用找零錢了，謝謝您優質貼心的服務！'),
    ('The food here is always authentic and flavorful.', '這裡的料理總是非常道地且風味十足。'),
    ('Could I get a refill on my iced black tea, please?', '能請您幫我的冰紅茶續杯一下嗎？'),
    ('Excuse me, I think there is an extra charge on our bill.', '不好意思，我想我們的帳單上似乎多算了一筆費用。'),
    ('We would like to order some appetizers to share first.', '我們想先點幾道開胃前菜大家一起分著吃。'),
    ('What is your house specialty cocktail?', '請問你們店裡的招牌特調雞尾酒是什麼？'),
    ('I will just take tap water with a slice of lemon.', '我只要一般自來水加一片檸檬角就可以了。'),
    ('Is this dish very spicy? Can you make it mild?', '這道菜會很辣嗎？可以幫我做成微辣嗎？'),
    ('I am a vegetarian; what options do you have for me?', '我是素食者，請問菜單上有哪些素食餐點可供選擇？'),
    ('Could you bring an extra set of cutlery and small plates?', '能幫我們多帶一副餐具和小分食盤嗎？'),
    ('We have been waiting for our main courses for forty minutes.', '我們的主餐已經等了四十分鐘了，能否幫忙催一下？'),
    ('I will check on your order in the kitchen immediately.', '我立刻去後方廚房為您確認出餐進度。'),
    ('Would you like your coffee with whole milk or oat milk?', '請問您的咖啡想要加全脂鮮乳還是燕麥奶？'),
    ('Please bring the bill to our table whenever convenient.', '方便的時候，請把帳單送到我們的桌邊。'),
    ('Everything tasted extraordinary; we will definitely come back.', '每樣餐點嚐起來都非凡美味，我們一定會再光顧的。'),
    ('Can we sit outside on the patio to enjoy the sunset?', '我們可以坐在戶外露天陽台區欣賞落日夕陽嗎？'),
    ('I would like to make a reservation for Friday at seven.', '我想預約本週五晚上七點的四人用餐訂位。'),
    ('We are celebrating a birthday tonight; do you offer cake service?', '我們今晚慶祝生日，請問店裡有提供代切蛋糕或慶生服務嗎？'),
    ('What kind of beer do you have on draft right now?', '請問你們目前吧檯供應哪些現壓生啤酒？'),
    ('Could you pack the leftovers in a takeout container, please?', '能麻煩您把剩餘的餐點打包外帶嗎？'),
    ('The seafood risotto is rich, creamy, and satisfying.', '這道海鮮燉飯濃郁滑順，吃起來令人心滿意足。'),
    ('I prefer my burger without mayonnaise and onions.', '我的漢堡請不要放美乃滋和洋蔥。'),
    ('Is the bakery bread freshly made in-house every morning?', '這家烘焙坊的麵包是每天早晨在店內現烤出爐的嗎？'),
    ('May I have some olive oil and balsamic vinegar for the bread?', '能給我一些橄欖油和巴薩米克醋來沾麵包吃嗎？'),
    ('The garlic butter shrimp appetizer was phenomenal.', '那道大蒜奶油蝦開胃菜的味道實在太驚艷了。'),
    ('Could you please clear the empty plates from our table?', '能請您幫我們收走桌上的空盤子嗎？'),
    ('Do you have high chairs available for toddlers?', '請問店內有提供幼兒專用的兒童高腳椅嗎？'),
    ('We are running a bit late for our reservation; please hold our table.', '我們的訂位會稍微晚到十分鐘，請幫我們保留座位。'),
    ('What ingredients are used in this homemade sauce?', '這道自製秘調醬汁裡面使用了哪些食材原料？'),
    ('I would like a medium-rare sirloin steak with mashed potatoes.', '我要一份五分熟的沙朗牛排佐綿密馬鈴薯泥。'),
    ('Could we get two separate bills for our table?', '能幫我們這桌拆成兩張分開結帳的帳單嗎？'),
    ('This coffee has a delightfully smooth and nutty flavor.', '這杯咖啡帶有令人愉悅的滑順口感與堅果香氣。'),
    ('We need five more minutes to look over the menu.', '我們還需要五分鐘的時間看一下菜單。'),
    ('Take all the time you need; I will come back shortly.', '請慢慢看不用急，我稍後再過來為您點餐。'),
    ('Is there a minimum spending requirement per person?', '請問店內每個人有最低消費金額限制嗎？'),
    ('The pizza crust is wonderfully thin, crispy, and fresh.', '這份披薩的餅皮烤得非常薄脆、口感極佳。'),
    ('Could you recommend a light white wine to pair with fish?', '能推薦一款適合搭配魚肉料理的清爽白葡萄酒嗎？'),
    ('Please make sure the soup is piping hot when served.', '上菜時請務必確保熱湯是熱氣騰騰的。'),
    ('I am stuffed; I could not eat another single bite.', '我吃得好撐啊，一口都再也吃不下了。'),
    ('The portions here are very generous for the price.', '以這個價格來說，這裡每道菜的分量非常慷慨大方。'),
    ('Can I order a decaf cappuccino with cinnamon powder?', '我可以點一杯撒上肉桂粉的無咖啡因卡布奇諾嗎？'),
    ('Let us grab a quick bite to eat before the movie starts.', '電影開演前，我們先去隨便吃點簡餐填填肚子吧。'),
    ('Do you offer breakfast sets before ten in the morning?', '請問早上十點前有供應超值早餐特惠套餐嗎？'),
    ('The aroma coming from the kitchen makes my mouth water.', '廚房飄散出來的陣陣香氣讓我垂涎欲滴。'),
    ('I would like to cancel my drink order if it has not been made.', '如果飲料還沒做的話，我想先取消那杯飲品。'),
    ('Is there an outdoor smoking area available at the restaurant?', '請問餐廳有設立戶外的吸菸專區嗎？'),
    ('Can we move to a quieter booth over in the corner?', '我們可以換到角落那張比較安靜的卡座沙發嗎？'),
    ('The service here is prompt, friendly, and attentive.', '這裡的服務迅速敏捷、親切友善又非常細心周到。'),
    ('We had an extraordinary dining experience this evening.', '我們今晚在這裡度過了一次極棒的用餐體驗。'),
    ('Could you please bring us the dessert menu again?', '能請您再把甜點菜單拿過來給我們看一下嗎？'),
    ('Their signature tiramisu is definitely worth trying.', '他們家的招牌提拉米蘇絕對值得親自一試。'),
    ('I would like to order a takeaway iced latte with soy milk.', '我要外帶一杯換燕麥奶/豆奶的冰拿鐵。'),
    ('Is there an elevator to access the second-floor dining area?', '請問有電梯可以通往二樓的用餐區嗎？'),
    ('Thank you for accommodating our dietary restrictions.', '非常感謝您貼心配合我們的飲食特殊禁忌。'),
    ('We look forward to enjoying our next meal at your restaurant.', '我們非常期待下次再度光臨貴餐廳享用美食。')
])

# 7. 購物消費與結帳 (80)
add('購物消費與結帳', [
    ('Excuse me, how much is this winter wool jacket?', '不好意思，請問這件冬季羊毛外套多少錢？'),
    ('Do you have this stylish shirt in a medium size?', '請問這件好看的襯衫有 M 號中碼的尺寸嗎？'),
    ('Can I try this pair of denim jeans on in the fitting room?', '我可以去試衣間試穿這條牛仔褲嗎？'),
    ('Where are the fitting rooms located in this department?', '請問這個專櫃樓層的試衣間位在哪裡？'),
    ('These leather shoes are a little too tight on my feet.', '這雙皮鞋穿在我的腳上稍微有點太緊了。'),
    ('Do you have these running sneakers in a size ten?', '這款慢跑運動鞋有美規十號的尺寸嗎？'),
    ('Is this merchandise currently on sale or discounted?', '這件商品目前有在做特價促銷或打折嗎？'),
    ('There is a twenty percent discount on all outerwear today.', '今天店內所有的外衣外套一律享有八折優惠。'),
    ('Buy one get one free on all selected summer items.', '所有精選夏季商品享有買一送一的優惠活動。'),
    ('Do you offer any student or military discounts?', '請問你們有提供任何學生證或是軍人優惠折扣嗎？'),
    ('Can you give me a better deal or discount if I buy two?', '如果我買兩件的話，能算我便宜一點或給點折扣嗎？'),
    ('I am just browsing around, thank you very much.', '我只是先隨便逛逛看看，非常謝謝你。'),
    ('Let me know if you need any assistance finding sizes.', '如果您需要找特定尺寸，請隨時告訴我一聲。'),
    ('I will take this elegant black dress, please.', '我要買下這件優雅的高雅黑色洋裝。'),
    ('Where is the cashier checkout counter for payment?', '請問結帳付款的收銀櫃檯位在哪裡？'),
    ('Do you accept contactless payments like Apple Pay?', '請問你們接受 Apple Pay 等感應式行動支付嗎？'),
    ('Can I pay with a foreign credit card or foreign currency?', '我可以使用外國信用卡或外幣進行付款結帳嗎？'),
    ('Please insert your chip card and enter your secret PIN.', '請插入您的晶片卡並在螢幕上輸入密碼。'),
    ('Could you please wrap this item up as a gift for me?', '能麻煩您幫我把這個商品包裝成禮物包裝嗎？'),
    ('Would you like a shopping paper bag for five dollars?', '請問您需要花五元加購一個紙製購物提袋嗎？'),
    ('Here is your receipt and itemized change. Have a nice day!', '這是您的發票明細與找零，祝您有美好的一天！'),
    ('What is your exchange and return policy for unworn clothes?', '請問未穿過的衣物退換貨政策規定是什麼？'),
    ('You can return items within thirty days with original receipt.', '憑原始購買發票明細，三十天內皆可辦理退換貨。'),
    ('I would like to exchange this sweater for a larger size.', '我想把這件毛衣更換成再大一號的尺寸。'),
    ('I would like to return this defective toaster for a refund.', '我想把這台有瑕疵的烤麵包機退貨並申請全額退款。'),
    ('Do you have this electronic gadget in stock in the warehouse?', '請問這款電子產品在倉庫裡還有現貨庫存嗎？'),
    ('I am sorry, but that popular model is completely sold out.', '非常抱歉，那款熱門型號目前已經全數售罄缺貨。'),
    ('When do you expect the next shipment of items to arrive?', '請問預計下一批補貨商品大約什麼時候會到貨？'),
    ('Can you put this exclusive handbag on hold for an hour?', '能幫我把這款限量手提包保留保留一個小時嗎？'),
    ('Is there an official manufacturer warranty for this watch?', '請問這支手錶有附原廠的官方保固服務嗎？'),
    ('It comes with a comprehensive two-year international warranty.', '這款產品享有長達兩年的全球國際原廠保固。'),
    ('This fabric is made of one hundred percent organic cotton.', '這種布料是由百分之百天然有機純棉製造而成的。'),
    ('Does this winter coat provide good protection against rain?', '這件冬季大衣有提供良好的防風防水防雨效果嗎？'),
    ('Are there other color options available for this backpack?', '請問這款後背包還有其他顏色的款式可供挑選嗎？'),
    ('We also have this sleek bag in navy blue, charcoal, and beige.', '這款俐落的包包我們還有海軍藍、炭灰色和米色。'),
    ('This color matches your skin tone and eyes wonderfully.', '這個顏色非常襯托你的膚色，跟你超搭的。'),
    ('I think the smaller size fits your frame much better.', '我認為小一點的那個尺寸穿在你身上身形好看多了。'),
    ('How does this tailored suit look on me from behind?', '這套剪裁西裝從我背後看起來版型如何？'),
    ('It looks extremely sharp, professional, and flattering on you.', '穿在你身上看起來非常筆挺俐落、專業又修身。'),
    ('I am looking for a durable laptop sleeve for my device.', '我正在尋找一個耐磨防摔的筆記型電腦保護套。'),
    ('Where can I find cosmetic products and skin skincare?', '請問美妝護膚與保養品專區位在哪個樓層呢？'),
    ('They are on the ground floor right next to the entrance.', '它們位在一樓正門入口處的右手邊。'),
    ('Can I claim a duty-free tax refund on these purchases?', '我購買的這些免稅商品可以在這裡辦理退稅嗎？'),
    ('The tax refund desk is located on the sixth floor.', '免稅退稅服務櫃檯位在百貨公司的六樓。'),
    ('Please remember to present your original passport at checkout.', '結帳辦理時請務必記得出示您的護照正本。'),
    ('Is there an ATM nearby inside this shopping mall?', '請問這間購物商場內部附近有自動提款機嗎？'),
    ('There is an ATM right by the customer service center.', '在顧客服務中心的旁邊就有一台自動提款機。'),
    ('Can I test out the noise-canceling headphones before buying?', '在購買之前我可以先親自試戴試聽這款降噪耳機嗎？'),
    ('Feel free to connect your phone to the sample unit.', '請隨意將您的智慧型手機連接到展示樣機進行試聽。'),
    ('This store offers free nationwide delivery on orders over fifty.', '這家店凡消費滿五十元即可享有全島免費宅配到府。'),
    ('I would like to sign up for your store membership program.', '我想免費註冊加入你們商店的會員集點積點計畫。'),
    ('Members earn points that can be redeemed for future discounts.', '會員消費可累積紅利點數，未來可用於折抵現金消費。'),
    ('Is this price inclusive of value-added sales tax?', '請問標籤上的這個標價已經包含加值營業稅了嗎？'),
    ('The zipper on this jacket seems to be stuck; can you check it?', '這件夾克的外套拉鍊好像卡住了，能幫我檢查一下嗎？'),
    ('Let me grab a brand new one from our stockroom for you.', '請稍候，我立刻去庫房為您拿一件全新未拆封的。'),
    ('Are these handmade ceramic mugs dishwasher safe?', '這些手工製作的陶瓷馬克杯可以用洗碗機清洗嗎？'),
    ('Yes, they are completely dishwasher and microwave safe.', '是的，它們完全適用於洗碗機清洗和微波爐加熱。'),
    ('I love the vintage design and texture of this leather belt.', '我非常喜歡這條真皮皮帶的復古設計風格與質感。'),
    ('It is crafted with genuine full-grain Italian leather.', '它是採用義大利進口頂級頭層真皮精心手工打造的。'),
    ('Could you help me find a pair of polarized sunglasses?', '能請您幫我找一副抗眩光的偏光太陽眼鏡嗎？'),
    ('These sunglasses block one hundred percent of harmful UV rays.', '這款太陽眼鏡能百分之百阻隔有害的紫外線傷害。'),
    ('I am shopping for a housewarming present for my good friend.', '我正在挑選一份送給好朋友的喬遷新居賀禮。'),
    ('A scented candle set or an aroma diffuser would be ideal.', '一組香氛香薰蠟燭或是香氛水氧機都是極佳的選擇。'),
    ('Do you sell gift certificates or digital gift cards here?', '請問你們店裡有販售實體禮券或是數位禮品卡嗎？'),
    ('Yes, you can load any amount starting from twenty dollars.', '有的，您可以自由儲值從二十元起跳的任何面額。'),
    ('This pair of running socks is moisture-wicking and breathable.', '這雙專業慢跑襪具備吸濕排汗且透氣乾爽的特性。'),
    ('Can I see the display watch in the glass showcase?', '我可以看一下玻璃展示櫃裡的那款展示手錶嗎？'),
    ('Certainly, let me unlock the glass cabinet for you.', '當然可以，讓我為您把玻璃展示櫃的鎖打開。'),
    ('Is this luggage suitcase within carry-on cabin size limits?', '這款隨身行李箱符合隨身登機箱的尺寸規定限制嗎？'),
    ('It fits standard international airline overhead bin dimensions.', '它完全符合國際航空公司標準的客艙機上置物箱尺寸。'),
    ('I am looking for a lightweight, compact folding umbrella.', '我正在尋找一把輕巧好收納的防風摺疊雨傘。'),
    ('This sturdy umbrella has a reinforced carbon fiber frame.', '這把堅固的雨傘採用了強化碳纖維骨架抗風設計。'),
    ('Do you offer custom engraving services on jewelry?', '請問你們有在飾品首飾上提供客製化刻字服務嗎？'),
    ('We offer free laser engraving on all gold and silver rings.', '我們為所有的金戒指和銀戒指提供免費雷射刻字服務。'),
    ('This material is wrinkle-resistant and iron-free for easy care.', '這種高級材質具備防皺免燙特性，保養打理非常輕鬆。'),
    ('Could you please give me a separate itemized receipt?', '能請您另外多印一張條列分明的購買收據明細給我嗎？'),
    ('Thank you for shopping with us today; please come back soon!', '感謝您今日蒞臨本店購物消費，期待您再次光臨！'),
    ('I found exactly what I was searching for all afternoon.', '我終於找到了我整個下午一直在尋找的夢幻商品。'),
    ('Shopping during holiday clearance sales saves so much money.', '在節慶季末出清特賣會期間購物真的能省下大筆金錢。'),
    ('Online shopping is convenient, but trying items in store is best.', '網購固然方便，但能在實體門市親自試穿試用還是最棒的。')
])

# 8. 旅遊觀光與問路 (90)
add('旅遊觀光與問路', [
    ('Excuse me, could you tell me how to get to Central Station?', '不好意思，請問中央火車站應該要怎麼走？'),
    ('Go straight for two blocks, then turn left at the traffic light.', '直走過兩個街區，然後在紅綠燈路口左轉。'),
    ('Is it within walking distance, or should I take a taxi?', '走路走得到嗎，還是我應該搭乘計程車比較好？'),
    ('It takes about ten minutes on foot from this intersection.', '從這個十字路口步行大約需要十分鐘左右的時間。'),
    ('Where is the nearest underground metro subway station?', '請問距離這裡最近的地鐵站位在哪個方向？'),
    ('Which subway line should I take to reach the Art Museum?', '去國立市立美術館的話，我應該搭乘哪一條地鐵線？'),
    ('Take the Blue Line going northbound and get off at City Hall.', '搭乘往北行駛的藍線地鐵，並在市政府站下車即可。'),
    ('Do I need to transfer to another train line along the way?', '沿途路上我需要在任何車站轉乘其他路線列車嗎？'),
    ('You will need to transfer to the Red Line at Central Plaza.', '您需要在中央廣場站換乘換搭紅色線地鐵列車。'),
    ('Where can I purchase a single-journey subway token or ticket?', '請問我在哪裡可以購買單程地鐵代幣或乘車票？'),
    ('You can buy tickets at the automated vending machines over there.', '您可以在那邊的那幾台自動售票機購買乘車票。'),
    ('How much is the one-way adult fare to the international airport?', '請問前往國際機場的成人單程票價是多少錢？'),
    ('Is there a multi-day tourist transit pass available for visitors?', '請問有針對觀光旅客販售的多日大眾運輸暢遊周遊券嗎？'),
    ('A three-day unlimited pass gives you great value for travel.', '三日無限次搭乘通行券非常划算超值、省時省錢。'),
    ('Where is the bus stop for bus route number twenty-four?', '請問二十四號公車路線的站牌設立在什麼位置？'),
    ('Does this express bus go directly to the famous night market?', '請問這班直達快捷公車有直達著名熱鬧的觀光夜市嗎？'),
    ('Please alert me when we arrive at the National Monument stop.', '當公車抵達國家紀念碑站牌時，能否麻煩提醒我一聲？'),
    ('Excuse me, am I heading in the right direction for the harbor?', '不好意思，請問我往這個方向走是去港口海濱的路嗎？'),
    ('No, you are going the wrong way; turn around and walk back.', '不對，您走反方向了，請回頭往回走兩個路口。'),
    ('Could you please show me our current location on Google Maps?', '能請您在 Google 地圖上指給我看我們目前所在的位置嗎？'),
    ('We are right here near the historical cathedral square.', '我們目前就位在這座歷史悠久的大教堂廣場旁邊。'),
    ('What are the must-see tourist attractions in this historic city?', '這座歷史文化名城有哪些絕對不容錯過的必遊觀光景點？'),
    ('You definitely should not miss the ancient royal palace and gardens.', '您絕對不能錯過參觀古代皇宮與那座精緻的皇家花園。'),
    ('Are there guided walking tours available in fluent English?', '請問有提供全程使用流利英語解說的專人導覽步行團嗎？'),
    ('The English guided tour departs daily at ten in the morning.', '英語專人導覽團每天上午十點整在遊客中心準時出發。'),
    ('Where can I pick up a free city sightseeing map and brochure?', '請問我在哪裡可以免費索取一份城市觀光地圖與旅遊簡介？'),
    ('The tourist information visitor center is inside the train station.', '觀光旅遊諮詢服務中心就設立在火車站大廳內部。'),
    ('What are the opening and closing hours of the National Gallery?', '請問國家美術館每天的開館與閉館開放時間是幾點？'),
    ('It is open Tuesday through Sunday from nine to five in the evening.', '每週二至週日上午九點至下午五點對外開放參觀。'),
    ('Is admission free, or do we need to purchase entrance tickets?', '請問是免費開放入場，還是我們必須購買參觀門票？'),
    ('Admission to the permanent collection gallery is completely free.', '常設展覽館的入場門票是完全免費開放大眾參觀的。'),
    ('Can I take photos and videos inside the exhibition halls?', '在展覽廳內部我可以拍照攝影或錄製短影片嗎？'),
    ('Photography without flash is permitted in designated galleries.', '在指定展廳內部允許在不開啟閃光燈的前提下進行拍照。'),
    ('Could you take a quick photo of our group with the landmark?', '能請您以這個著名地標為背景幫我們全體拍張合照嗎？'),
    ('Say cheese! One, two, three, smile everyone!', '笑一個！一、二、三，大家看鏡頭微笑！'),
    ('Let me take one more photo just in case someone blinked.', '我再幫你們多拍一張，以防有人剛才剛好眨了眼睛。'),
    ('How do I rent a public bicycle or electric scooter in the city?', '請問在這座城市我要如何租借公共自行車或共享電動滑板車？'),
    ('You can easily download the transit app and scan the QR code.', '您只需要下載交通專用 App 並掃描車身上的 QR Code 即可。'),
    ('Are there scenic bike lanes along the riverside promenade?', '沿著河岸景觀步道有規劃專用的自行車觀光車道嗎？'),
    ('The riverside bike path offers panoramic views of the skyline.', '這條河濱自行車道能將整座城市天際線的壯麗全景盡收眼底。'),
    ('Where can I catch a scenic cruise boat ride on the river?', '請問我在哪裡可以搭乘遊覽觀光船欣賞沿河的風光？'),
    ('The main ferry terminal pier is five minutes south of here.', '主要的渡輪觀光碼頭就在往南走五分鐘路程的地方。'),
    ('Is there an audio guide available in Mandarin Chinese?', '請問現場有提供繁體中文或華語的語音導覽機租借嗎？'),
    ('Yes, audio guides are available in ten different languages.', '有的，現場語音導覽機共提供十種不同語言供遊客選擇。'),
    ('What is the best scenic viewpoint to photograph the sunset?', '請問拍攝這座城市日落夕陽的最佳觀景制高點在哪裡？'),
    ('The hilltop observation deck offers a stunning sunset view.', '山頂景觀展望台能欣賞到令人屏息讚嘆的落日絕景。'),
    ('How steep is the mountain hiking trail to reach the summit?', '爬到山頂的那條登山健行步道坡度會非常陡峭難爬嗎？'),
    ('It is a paved trail with gentle stairs, suitable for all ages.', '那是一條鋪設平整且階梯坡度緩和的步道，老少咸宜。'),
    ('Be sure to carry plenty of drinking water and sunscreen.', '出發前請務必隨身攜帶充足的飲用水並做好防曬措施。'),
    ('Where is the best traditional marketplace to sample street food?', '請問想品嚐最道地的街頭在地小吃，哪座傳統市場最推薦？'),
    ('The central old market has over two hundred delicious food stalls.', '中央老市場聚集了超過兩百多個各式各樣的美味特色小吃攤。'),
    ('What local specialty souvenir do you recommend taking home?', '您推薦買什麼在地最具代表性的特色伴手禮帶回家送人？'),
    ('Handcrafted tea leaves and pineapple pastries are very famous.', '精緻的手工高山茶葉與酥香鳳梨酥在當地極具盛名。'),
    ('Are there public restrooms available inside this historical park?', '請問這座歷史古蹟公園內部有提供公共洗手間化妝室嗎？'),
    ('The clean restrooms are located behind the fountain pavilion.', '乾淨整潔的洗手間就位在噴水池涼亭後方的通道旁。'),
    ('Can I drink the tap water safely in this region?', '請問在這個地區自來水水質可以直接生飲安全無虞嗎？'),
    ('It is recommended to boil tap water or buy bottled spring water.', '建議將自來水煮沸後再飲用，或是購買瓶裝礦泉水。'),
    ('Is it safe to walk around this neighborhood late at night?', '深夜在這個社區周邊街道獨自散步安全嗎？治安好嗎？'),
    ('It is generally very safe and well illuminated by streetlights.', '這裡治安普遍非常良好，且整條街道路燈照明充足。'),
    ('What should I do if I accidentally lose my foreign passport?', '如果我不小心遺失了外國護照，我應該怎麼處理才好？'),
    ('Report to the nearest police station and contact your embassy.', '請立刻前往最近的警察局報案並儘速聯繫您的代表處使館。'),
    ('Where is the local police station located from here?', '請問從這裡出發，最近的在地警察局派出所位在哪裡？'),
    ('Keep your valuables and passport secured in an inner pocket.', '請將您的貴重物品與護照證件妥善收在衣服內側暗袋中。'),
    ('Be mindful of pickpockets in crowded tourist spots and subways.', '在人潮擁擠的觀光熱門景點與地鐵車廂內要格外提防扒手。'),
    ('How far is the sandy ocean beach from the downtown center?', '請問從市中心繁華地帶到金黃沙灘海邊大約有多遠距離？'),
    ('It is only a fifteen-minute scenic tram ride to the beach.', '搭乘觀光路面電車前往海灘只需要十五分鐘的宜人車程。'),
    ('Can we rent beach umbrellas and lounge chairs for the afternoon?', '我們可以在海灘租借遮陽遮陽傘和沙灘躺椅度過下午嗎？'),
    ('Lifeguards are on active duty along the designated swimming zone.', '在指定的安全游泳戲水區域內，隨時都有專業救生員在現場值勤。'),
    ('The ocean water is pleasantly refreshing and crystal clear today.', '今天的海水溫度清涼舒適，而且水質清澈見底。'),
    ('Where can we book a scuba diving or snorkeling day tour?', '請問我們在哪裡可以報名預訂水肺潛水或浮潛一日遊行程？'),
    ('The dive shop right on the marina offers daily excursions.', '位在遊艇碼頭正前方的那間潛水專門店每天都有出海行程。'),
    ('Are there boat trips to see wild dolphins in their habitat?', '請問有出海前往野生海豚棲息地觀賞海豚的觀光船行程嗎？'),
    ('Morning boat tours offer the highest chance of spotting dolphins.', '清晨出海的船班能看到野生海豚躍出海面的機率是最高的。'),
    ('This ancient castle was constructed more than six centuries ago.', '這座宏偉的古老城堡早在六百多年前就已經建造完成了。'),
    ('The architectural details reflect a rich and storied heritage.', '這些精緻的建築雕刻細節展現了豐富而深遠的歷史文化遺產。'),
    ('I am fascinated by the legendary stories surrounding this palace.', '我對這座宮殿周圍流傳的各種傳奇歷史故事感到深深著迷。'),
    ('Let us take a quiet stroll through the peaceful botanical gardens.', '讓我們在寧靜悠閒的市立植物園中悠閒漫步散心吧。'),
    ('The vibrant roses and orchids are blooming in full glory.', '盛開的鮮豔玫瑰花與嬌豔蘭花正展現著它們最美的姿態。'),
    ('Traveling opens our minds and introduces us to diverse cultures.', '出門旅行能開闊我們的心胸眼界，並讓我們接觸多元文化。'),
    ('Every journey creates unforgettable memories that last a lifetime.', '每一次的旅程都能締造出值得珍藏一輩子、難以忘懷的回憶。'),
    ('I cannot wait to explore every hidden corner of this city.', '我迫不及待想親自探索這座城市裡每一個隱藏的私房角落。'),
    ('Let us check into our hotel and freshen up before dinner.', '我們先去飯店辦理入住手續、梳洗一番，然後再出門吃晚餐。'),
    ('Where can I find an authorized currency exchange counter?', '請問我在哪裡可以找到政府合法授權的外幣兌換匯兌處？'),
    ('Banks and airport kiosks offer safe foreign currency exchange.', '當地的各大銀行與機場專屬櫃檯皆提供安全的外幣兌換服務。'),
    ('What is the current official exchange rate for US dollars?', '請問目前美金兌換當地貨幣的官方公告匯率是多少？'),
    ('Always keep a small amount of local cash for street vendors.', '出門時請隨身備妥少量當地現金零錢，以便在街頭小販消費。'),
    ('The local people here are genuinely welcoming, warm, and helpful.', '這裡的在地居民為人真誠親切熱情，而且非常樂於助人。'),
    ('I have fallen in love with the captivating charm of this town.', '我已經深深愛上了這座迷人城鎮所散發出的迷人魅力。'),
    ('I will definitely recommend this breathtaking destination to all my friends.', '我一定會把這個美得令人屏息的絕佳旅遊勝地大力推薦給朋友們。'),
    ('May your travels be filled with joyful discovery and safe passages.', '願您的每一趟旅途都充滿驚奇的新發現，一路順風平安！')
])

# 9. 住宿搭機與機場 (80)
add('住宿搭機與機場', [
    ('I would like to check in for my flight to Los Angeles.', '我想辦理搭乘前往洛杉磯航班的登機手續。'),
    ('May I see your valid passport and electronic booking confirmation?', '可以請您出示您的有效護照與電子機票訂位確認單嗎？'),
    ('How many pieces of checked baggage will you be checking today?', '請問您今天總共有幾件行李需要辦理託運托運呢？'),
    ('I have one large suitcase to check and one backpack to carry on.', '我有一件大行李箱要託運，以及一個隨身後背包帶上飛機。'),
    ('Please place your luggage suitcase onto the weighing scale.', '請將您的行李箱放置在行李磅秤輸送帶上秤重。'),
    ('Your checked bag is two kilograms over the allowable weight limit.', '您的託運行李超出了免費行李限額兩公斤的重量限制。'),
    ('Would you prefer an aisle seat or a window seat near the front?', '請問您偏好靠走道的座位還是靠近前排靠窗戶的座位？'),
    ('I would love a window seat if there is one still available.', '如果還有空位的話，我很希望能劃一個靠窗的位置。'),
    ('Here is your official boarding pass; your boarding gate is B12.', '這是您的登機證，您的登機門位在 B12 號登機口。'),
    ('Boarding will commence precisely forty minutes before departure.', '飛機將在預定起飛時間前四十分鐘準時開始進行登機。'),
    ('Where is the designated airport security screening checkpoint?', '請問機場旅客出境安全檢查通道位在哪個區域？'),
    ('Please remove your laptop, liquids, and belt for inspection.', '安檢時請從隨身包中取出您的筆記型電腦、液體瓶罐與腰帶。'),
    ('All liquids in carry-on bags must be under one hundred milliliters.', '隨身行李內的所有液體容量皆不得超過一百毫升的瓶裝上限。'),
    ('Is my international connecting flight running on schedule?', '請問我下一段銜接的國際轉機航班目前是否維持準點？'),
    ('Your flight is on time and scheduled to depart at four thirty.', '您的班機目前一切準點，預計將於下午四點三十分準時起飛。'),
    ('Attention passengers, flight 302 to Tokyo is now boarding.', '各位旅客請注意，飛往東京的 302 號班機現在開始登機。'),
    ('Please have your boarding pass and passport ready in hand.', '請各位旅客提前將您的登機證與護照正本拿在手上以備查驗。'),
    ('Could you please help me put this carry-on bag in the bin?', '能請您幫忙把這個隨身登機袋放進上方的行李置物櫃嗎？'),
    ('Please fasten your seatbelt and return your seat to the upright position.', '請繫好您的安全帶，並將座椅靠背調整回豎直垂直位置。'),
    ('Turn off all electronic devices or switch them into airplane mode.', '請關閉所有電子設備，或將其切換至飛行飛航模式。'),
    ('Would you care for chicken and rice or beef with mashed potatoes?', '請問餐點您想選雞肉飯還是牛肉搭配馬鈴薯泥？'),
    ('Could I have a hot cup of black tea and an extra blanket?', '可以給我一杯熱紅茶以及一件額外的機上毛毯嗎？'),
    ('Please fill out the customs declaration form before landing.', '在飛機降落入境之前，請如實填寫好海關入境申報單。'),
    ('We have arrived at our destination; thank you for flying with us.', '我們已經順利抵達目的地，感謝您選擇搭乘本航空公司。'),
    ('Where can I collect my checked luggage from the baggage carousel?', '請問我在哪一個行李轉盤輸送帶提取我的託運行李？'),
    ('My checked bag has not appeared; where is the lost luggage counter?', '我的託運行李還沒出來，請問行李遺失申訴櫃檯在哪裡？'),
    ('Please file a property irregularity report with your baggage tag.', '請出示您的行李票收據條碼，在此填寫行李異常申報單。'),
    ('I have a reservation for a deluxe queen room for three nights.', '我有預訂一間豪華雙人床房型，預計入住三個晚上。'),
    ('Welcome to the Grand Hotel! Check-in time starts at three in the afternoon.', '歡迎光臨大飯店！飯店每日下午三點開始辦理入住手續。'),
    ('Could I request an early check-in or store my luggage here?', '我可以申請提早辦理入住，或是先將行李寄放在櫃檯嗎？'),
    ('Certainly, we would be delighted to store your bags in the luggage room.', '當然可以，我們非常樂意先將您的行李妥善寄放在行李室。'),
    ('Here are your magnetic room keycards; you are in room 805.', '這是您的磁卡房卡鑰匙，您的房間位在 805 號房。'),
    ('What time is the complimentary buffet breakfast served in the morning?', '請問每天早晨的免費自助式早餐供應時間是幾點到幾點？'),
    ('Breakfast is served on the second floor from six thirty to ten.', '自助早餐在二樓餐廳供應，時間為清晨六點半至上午十點。'),
    ('What is the Wi-Fi network name and password for hotel guests?', '請問房客專用的無線網路 Wi-Fi 名稱與登入密碼是什麼？'),
    ('The Wi-Fi password is your room number combined with your last name.', 'Wi-Fi 連線密碼是您的房間號碼加上您的英文姓氏。'),
    ('Could we get extra bath towels and shampoo delivered to our room?', '能請房務部送幾條額外的大浴巾和洗髮精到我們房間嗎？'),
    ('The air conditioner in our room is making an unusual buzzing noise.', '我們房間裡的空調冷氣機一直發出一種異常的嗡嗡運轉噪音。'),
    ('I will send our maintenance engineer up to inspect it immediately.', '我立刻派維修工程師前往您的客房為您詳細檢查排除。'),
    ('Can I arrange a wake-up call for six in the morning tomorrow?', '我可以預約設定明天早晨六點整的客房電話叫醒晨喚服務嗎？'),
    ('Consider it done; our system will ring your room at six sharp.', '已經為您設定完成，系統將在早晨六點整準時撥通您的客房電話。'),
    ('Is there a fitness center gym and swimming pool on the premises?', '請問飯店設施內有附設健身房與溫水游泳池可供使用嗎？'),
    ('The gym and indoor pool are on the top floor, open until ten.', '健身房與室內泳池位在頂樓，每日開放至晚間十點整。'),
    ('What is the standard check-out time in the morning?', '請問飯店規定的標準退房離店時間是上午幾點呢？'),
    ('Check-out is at eleven; late check-out is subject to availability.', '退房時間為上午十一點，延遲退房須視當天客房預訂情況而定。'),
    ('I would like to check out now and settle my final room bill.', '我現在想要辦理退房手續，並結清我房間的所有帳單費用。'),
    ('Did you consume any drinks or snacks from the in-room mini bar?', '請問您在入住期間有享用客房內迷你吧的小吃或飲品嗎？'),
    ('Could you help us call a reliable taxi to the international airport?', '能請櫃檯幫我們代叫一輛前往國際機場的合法計程車嗎？'),
    ('We hope you had a pleasant and relaxing stay with us.', '由衷希望您在我們飯店度過了一段愉悅放鬆的美好住宿時光。'),
    ('Do you offer laundry and dry cleaning services for hotel guests?', '請問飯店有為房客提供衣物送洗或乾洗熨燙服務嗎？'),
    ('Please place your garments in the laundry bag inside the closet.', '請將您需要換洗的衣物放入衣櫃內專用的客房洗衣袋中。'),
    ('Is there room service available for late-night meals?', '請問飯店有提供深夜時段的客房送餐客房服務嗎？'),
    ('Room service operates twenty-four hours a day, seven days a week.', '客房餐飲送餐服務全天候二十四小時全年無休為您提供服務。'),
    ('Could you recommend a quiet spot in the hotel lobby to read?', '能推薦飯店大廳內哪處角落比較安靜適合閱讀沉思嗎？'),
    ('The lounge near the back garden is exceptionally quiet and bright.', '後花園旁的那處貴賓休息區環境特別幽靜而且採光極佳。'),
    ('I accidentally left my phone charger in the room after checkout.', '退房離開後，我不小心把手機充電器遺忘在客房插座上了。'),
    ('Our housekeeping team found it, and it is safe at the front desk.', '我們的房務清潔團隊已經拾獲，目前已妥善保管在櫃檯。'),
    ('Can I request non-smoking rooms on higher floors next time?', '下次預訂時我可以特別指定安排高樓層的無菸客房嗎？'),
    ('We will make a permanent note of your preferences in our database.', '我們已將您的個人住房偏好永久記錄在我們的會員系統中。'),
    ('Is there a convenience store or pharmacy within walking distance?', '請問飯店周邊步行範圍內有便利商店或藥局嗎？'),
    ('There is a 24-hour convenience mart just across the street.', '正門對面馬路正對面就有一間二十四小時營業的便利超商。'),
    ('Can I exchange foreign currency at the hotel front desk?', '我可以直接在飯店前台櫃檯兌換外幣現鈔嗎？'),
    ('We offer basic currency exchange for major currencies like USD and EUR.', '我們櫃檯提供美元與歐元等主要國際貨幣的基礎兌換服務。'),
    ('Could you provide us with extra pillows and a hypoallergenic duvet?', '能請你們多提供兩顆枕頭以及一件防過敏羽絨被嗎？'),
    ('We will deliver them to your suite within ten minutes.', '我們將在十分鐘之內將備品親自送至您的豪華套房。'),
    ('The panoramic view from our balcony was truly spectacular.', '從我們客房獨立陽台眺望出去的城市全景真是美得令人驚嘆。'),
    ('I would like to extend my hotel stay for two additional nights.', '我想將我在飯店的住宿時間再延長辦理續住兩個晚上。'),
    ('Let me check our room availability for those extended dates.', '讓我立刻為您查詢那幾天飯店是否有相同房型的空房可供續住。'),
    ('You can keep the same room without needing to move your bags.', '您可以繼續住在原來的房間，不需要搬移您的個人行李。'),
    ('Is there an airport shuttle bus service departing from the lobby?', '請問飯店大廳門口有提供直達機場的接駁專車巴士嗎？'),
    ('The airport shuttle runs every hour on the hour from six to nine.', '機場接駁專車每日上午六點至晚上九點每逢整點發出一班車。'),
    ('Please reserve two seats on the morning airport shuttle bus.', '請幫我們預先登記預約明天早晨八點那班機場接駁車的兩個座位。'),
    ('The hot water shower in our bathroom has excellent water pressure.', '我們浴室裡的熱水淋浴設備水壓充足、水溫非常穩定舒適。'),
    ('Thank you for making our wedding anniversary celebration so special.', '謝謝你們的精心安排，讓我們的結婚紀念日慶祝如此難忘特別。'),
    ('It was an absolute pleasure hosting you and your lovely family.', '能夠接待您與您可愛幸福的家人，是我們莫大的榮幸。'),
    ('We hope to have the honor of welcoming you back soon.', '由衷期盼在不久的將來能再次有榮幸接待您的光臨。'),
    ('Safe travels on the rest of your international journey!', '祝您接下來的所有國際航程旅途一路平安、萬事順心！'),
    ('Keep your luggage tags handy until you safely leave the terminal.', '在您平安走出機場航廈大廳之前，請妥善收好行李票收據。'),
    ('Traveling smoothly requires thoughtful preparation and patience.', '出門旅遊要能順暢無阻，需要周全細緻的行前準備與耐心。'),
    ('May every flight bring you to exciting new horizons and adventures.', '願每一次的起飛降落，都帶領你探索嶄新而刺激的冒險視界。')
])

# 10. 職場商務與會議 (90)
add('職場商務與會議', [
    ('Good morning everyone; let us get started with today agenda.', '大家早安，讓我們正式開始討論今天會議的各項議程。'),
    ('Thank you all for joining this quarterly project review meeting.', '感謝各位同仁準時出席本次的季度專案進度審查會議。'),
    ('The main objective of today discussion is to finalize the budget.', '今天會議討論的最核心目標是敲定並定案年度預算編列。'),
    ('Could you please give us a brief update on the client feedback?', '能請您向大家簡短匯報一下客戶端目前的最新回饋意見嗎？'),
    ('Our sales performance in the third quarter exceeded our targets.', '我們第三季度的整體業務銷售業績表現遠超出了原先設定的目標。'),
    ('We need to address the supply chain bottlenecks as soon as possible.', '我們必須儘快設法解決供應鏈上目前所面臨的各項瓶頸問題。'),
    ('What are the key takeaways from the market research analysis?', '從這份市場研究調查分析報告中，我們能得到哪些關鍵結論？'),
    ('Let us brainstorm creative solutions to tackle this design issue.', '讓我們集思廣益，腦力激盪出解決這個設計難題的創意方案。'),
    ('I would like to pass the floor to our lead product manager.', '現在我想把發言權交給我們的主導產品經理進行深入說明。'),
    ('Could everyone please turn to page four of the handout report?', '請大家將手邊的書面報告資料翻閱到第四頁進行對照。'),
    ('As you can clearly see from the sales chart, demand is rising.', '正如各位從銷售趨勢圖表上所能清楚看見的，市場需求正在持續攀升。'),
    ('We need to streamline our operational processes to boost efficiency.', '我們需要精簡並優化各項內部作業流程，以全面提升工作效率。'),
    ('What is the realistic timeline for delivering the beta software?', '對於交付測試版軟體的時程規劃，最切合實際的時間表是什麼？'),
    ('We are currently on track to launch the project before October.', '我們目前的專案進度完全在軌道掌控之中，預計十月前正式上線。'),
    ('Are there any unforeseen risks or obstacles we should prepare for?', '是否有任何我們應當提前防範未然的不可預見風險或潛在障礙？'),
    ('We have developed comprehensive contingency plans to mitigate risks.', '我們已經制定了周全詳盡的應變備案計畫，以有效降低可能風險。'),
    ('Let us assign clear action items and accountability for each task.', '讓我們為每一項待辦工作事項指派明確的負責人與執行權責。'),
    ('Who will be responsible for following up with the external vendor?', '請問後續與外部協力廠商進行追蹤對接的工作由誰主要負責？'),
    ('I will take ownership of coordinating with the design agency.', '我會全權承擔並負責與外部設計顧問公司進行密切協調對接。'),
    ('Could you summarize the main action points before we adjourn?', '在我們散會之前，能請您為大家總結一下幾項核心執行重點嗎？'),
    ('Our next weekly follow-up meeting is scheduled for next Tuesday.', '我們下一次的每週進度追蹤例會預定於下週二上午同一時間舉行。'),
    ('Thank you all for your active participation and great ideas.', '非常感謝大家的積極踴躍參與以及提出的各項寶貴建設性構想。'),
    ('Please send the meeting minutes and recordings to all participants.', '請將本次會議的會議紀錄與錄音檔寄送給所有與會成員參閱。'),
    ('I would like to schedule a one-on-one check-in with you tomorrow.', '我想與你預約明天下午進行一次一對一的個人工作進度面談。'),
    ('Do you have fifteen minutes available on your calendar afternoon?', '請問你明天下午的行事曆上有空檔能抽出一刻鐘時間聊聊嗎？'),
    ('Let me check my calendar schedule and send you a calendar invite.', '讓我確認一下我的行事曆行程，並寄送會議邀請函給您。'),
    ('I am currently swamped with multiple urgent project deadlines.', '我目前手頭上正被好幾個緊急的專案截止期限壓得喘不過氣。'),
    ('Can we push back the deliverable deadline by two working days?', '我們是否能將最終交付成果的截止時間往後順延兩個工作天？'),
    ('Let us negotiate with the stakeholder to manage their expectations.', '讓我們主動與關鍵利害關係人進行溝通協商，以管理好他們的期望值。'),
    ('Effective cross-functional collaboration is critical to our delivery.', '跨部門跨領域的有效通力協作對於我們如期交付成果至關重要。'),
    ('We should establish transparent communication across all departments.', '我們應該在所有部門組織之間建立起公開透明的溝通橋樑。'),
    ('Customer satisfaction and retention are our top business priorities.', '顧客滿意度與客戶留存率是我們企業當前最重要的營運核心重點。'),
    ('We received positive feedback from our beta testing users.', '我們從參與先導測試的種子用戶群中收到了非常正面熱烈的反饋。'),
    ('Let us iterate on the user interface based on user insights.', '讓我們根據真實用戶的研究洞察，持續反覆迭代打磨使用者介面。'),
    ('The new feature deployment went smoothly without any downtime.', '新功能的正式部署上線過程十分順利，完全沒有造成任何系統停機。'),
    ('We should conduct a post-mortem review to capture lessons learned.', '我們應該召開一次專案事後檢討會，以梳理並記錄寶貴的經驗教訓。'),
    ('Continuous improvement is an integral part of our team culture.', '持續精進與追求卓越是我們團隊文化中不可或缺的核心價值。'),
    ('Congratulations on closing that major enterprise contract deal!', '熱烈恭喜你成功簽下了那筆重大的大型企業級年度合作合約！'),
    ('Your hard work and dedication have truly paid off for the company.', '你的辛勤付出與無私奉獻確實為公司帶來了無比豐碩的實質成果。'),
    ('We need to recruit top engineering talent to expand our team.', '我們需要招募頂尖的資深工程技術人才，以擴充我們的研發團隊。'),
    ('The job posting will be published on professional networking platforms.', '這則招募職缺訊息將會同步刊登在各大專業職場社群平台上。'),
    ('Let us screen the applicant resumes and schedule video interviews.', '讓我們開始篩選應徵者的履歷表，並安排初階段的視訊面試。'),
    ('What qualities do you value most in a potential job candidate?', '在評估潛在的求職候選人時，你最看重對方的哪些特質與能力？'),
    ('Problem-solving ability and cultural fit are paramount to us.', '解決問題的實戰能力以及與團隊文化的契合度對我們來說最為關鍵。'),
    ('We offer competitive compensation packages and comprehensive benefits.', '我們提供極具市場競爭力的薪酬待遇與完善優渥的員工福利制度。'),
    ('Professional development and mentorship are provided to all hires.', '我們為所有新進員工提供完善的專業在職培訓與資深導師輔導制度。'),
    ('Please submit your quarterly expense reports before Friday afternoon.', '請各位同仁務必於本週五下午之前提交個人的季度費用報銷單。'),
    ('All receipts must be scanned and attached for accounting audit.', '所有發票單據皆必須掃描成電子檔並附在申請表後以供會計審核。'),
    ('Let us review our annual operational budget and resource allocation.', '讓我們重新審視公司的年度營運預算編列與各部門人力資源分配。'),
    ('Cost optimization should not compromise the quality of our service.', '在進行成本優化節流的同時，絕不能犧牲或損及我們的服務品質。'),
    ('We are exploring strategic partnerships with industry leaders.', '我們目前正在積極探索與各領域業界領頭羊建立策略合作夥伴關係。'),
    ('A mutual non-disclosure agreement has been signed by both legal teams.', '雙方的法務團隊已經正式審閱並簽署了具有法律效力的保密協定。'),
    ('Let us draft a comprehensive memorandum of understanding together.', '讓我們共同起草一份內容周詳嚴謹的雙邊合作備忘錄。'),
    ('The contract terms must be thoroughly vetted by our legal counsel.', '所有合約條款在正式簽署前，必須經由我們的法律顧問嚴格把關審核。'),
    ('Compliance with international regulatory standards is mandatory.', '嚴格遵守國際各項法規監管標準是我們經營不可妥協的基本底線。'),
    ('Data privacy and cybersecurity are strictly safeguarded in our system.', '資料隱私保護與網路資訊安全在我們的系統架構中受到最嚴密的捍衛。'),
    ('We must conduct regular vulnerability assessments and audits.', '我們必須定期針對系統執行弱點掃描評估與全面的資安合規稽核。'),
    ('Our executive leadership team has approved the proposed restructuring.', '公司高層領導團隊已經正式核准通過了本次所提出的組織架構重整案。'),
    ('The organizational changes will enhance agility and responsiveness.', '這次的組織架構調整將能大幅強化企業的敏捷度與市場快速反應力。'),
    ('We are committed to fostering an inclusive and diverse workspace.', '我們堅定致力於打造一個包容多元、互相尊重的友善職場工作環境。'),
    ('Employee wellbeing and mental health are top organizational priorities.', '員工的身心健康與心理福祉是企業組織治理中最為重視的優先要務。'),
    ('Let us celebrate our collective milestones at the company annual gala.', '讓我們在即將到來的公司年終尾牙盛會上共同慶祝大家攜手創造的里程碑。'),
    ('I am truly grateful to work alongside such talented professionals.', '能與這麼多才華洋溢又敬業的專業菁英並肩作戰，我由衷感到自豪。'),
    ('Leadership is about empowering others to reach their full potential.', '領導力的真諦，在於賦能並啟發他人充分發揮其內在的無限潛能。'),
    ('Clear communication prevents costly rework and misunderstandings.', '清晰準確的溝通能夠有效避免昂貴的重工浪費與不必要的認知歧見。'),
    ('Let us maintain high professional integrity in every transaction.', '讓我們在每一筆商業往來與交易中，始終恪守最高的專業誠信原則。'),
    ('Innovation thrives when teams feel safe to take calculated risks.', '當團隊在心理上感到安全且敢於承擔合理的創新風險時，創新便會蓬勃發展。'),
    ('We should always strive to deliver value that exceeds expectations.', '我們應當時刻自我勉勵，致力於為客戶提供超越其原先預期的非凡價值。'),
    ('Please review the attached proposal and share your detailed thoughts.', '請仔細審閱附件中的商業提案企劃書，並請不吝分享您的深入見解。'),
    ('I am confident that our concerted efforts will yield immense success.', '我深信在大家同心協力的齊心努力下，我們必將迎來巨大的豐碩成果。'),
    ('Let us stay focused on our key performance indicators this quarter.', '讓我們在這一季度始終緊盯並專注於我們的核心關鍵績效指標上。'),
    ('Adaptability in the face of market disruption is our competitive edge.', '面對市場顛覆性變革時所展現出的高度適應力，正是我們的核心競爭優勢。'),
    ('The keynote presentation at the global tech summit was inspiring.', '在全球科技領袖高峰會上的主題專題演講內容極具前瞻性與啟發性。'),
    ('We must build sustainable practices into our core business model.', '我們必須將永續發展的綠色理念深植並融入到我們的核心商業模式中。'),
    ('Let us draft the executive summary for the board of directors.', '讓我們為即將召開的董事會會議起草一份言簡意賅的高階主管執行摘要。'),
    ('The board unanimously approved our expansion into the Asian market.', '董事會全體董事一致無異議投票通過了我們進軍亞洲市場的擴張計畫。'),
    ('We are launching a comprehensive branding campaign next month.', '我們預計將於下個月正式全面啟動一場規模龐大的全新品牌行銷戰役。'),
    ('Tracking return on investment is crucial for optimizing our spend.', '精準追蹤投資報酬率對於我們持續優化行銷與營運支出至關重要。'),
    ('Customer loyalty is built through consistent, reliable service.', '客戶對品牌的忠誠度是透過每一次始終如一且值得信賴的優質服務所累積的。'),
    ('Let us schedule a retrospective session after completing the project.', '在專案圓滿落幕後，讓我們安排一場深入的專案回顧總結分享會。'),
    ('Every team member contribution was vital to reaching this milestone.', '每一位團隊夥伴的默默付出與辛勞貢獻都是達成此一里程碑不可或缺的力量。'),
    ('We should recognize and reward outstanding performance across teams.', '我們應當公開表彰並獎勵在各個部門領域中表現卓越出色的優秀同仁。'),
    ('A positive work environment encourages creativity and dedication.', '一個充滿正能量的友善工作環境能夠極大激發團隊的創造力與敬業奉獻精神。'),
    ('Let us keep our eyes on long-term vision while executing daily tasks.', '在穩健執行日常各項業務的同時，讓我們時刻牢記並著眼於長遠的戰略願景。'),
    ('Success is the sum of small efforts repeated day in and day out.', '所謂成功，正是那些日復一日、持之以恆堅持不懈的微小努力所匯聚而成的成果。'),
    ('Thank you all for your extraordinary commitment to excellence.', '由衷感謝大家為了追求卓越品質所展現出的非凡敬業精神與承諾！'),
    ('Let us wrap up today meeting and get back to our work.', '讓我們在此圓滿結束今天的會議，大家各自回到工作崗位上繼續努力。'),
    ('If you have any further questions, please do not hesitate to email me.', '如果您後續還有任何疑問，請隨時直接寄電子郵件與我聯繫。'),
    ('Wishing you all a very productive and rewarding working week ahead!', '祝願大家在接下來的這一週工作充實順利、收穫滿滿、成果豐碩！'),
    ('Together as a united team, there is nothing we cannot achieve.', '只要我們全體團隊上下團結一心，就沒有任何我們無法攻克的艱鉅目標！')
])

# 11. 電話通訊與約定 (80)
add('電話通訊與約定', [
    ('Hello, this is David calling from Apex Global Solutions.', '您好，我是頂尖環球科技公司的 David。'),
    ('May I please speak with Ms. Jennifer Anderson in Marketing?', '請問我可以與行銷部的 Jennifer Anderson 小姐通話嗎？'),
    ('I am afraid she is currently in a meeting; would you like to leave a message?', '恐怕她目前正在開會中，請問您想為她留下一段留言訊息嗎？'),
    ('Could you please ask her to call me back as soon as she is available?', '能請您轉告她，等她會議結束有空時儘快回電給我嗎？'),
    ('Could you please tell me your telephone number and extension?', '能請您留下您的聯絡電話號碼以及分機號碼嗎？'),
    ('My phone number is 555-0199, and my extension is 204.', '我的聯絡電話是 555-0199，分機號碼是 204。'),
    ('Let me read that back to you just to ensure I have it right.', '讓我向您覆誦一次號碼，以確保我記錄得完全正確。'),
    ('I am calling to confirm our scheduled business lunch appointment.', '我致電是為了再次確認我們原先預定的商務午餐約會。'),
    ('Would Thursday afternoon at two thirty work well for you?', '請問這週四下午兩點三十分的時間對您方便合適嗎？'),
    ('Let me check my schedule; yes, that time slot is open.', '讓我看一下我的行程表；沒問題，那個時段我是有空的。'),
    ('I look forward to meeting you at our headquarters on Thursday.', '我非常期待週四在我們公司總部與您正式會面。'),
    ('Something unexpected has come up, and I need to reschedule.', '我臨時遇到了一些突發緊急狀況，需要向您重新預約改期。'),
    ('Could we possibly push our meeting to next Monday morning?', '我們能否把會面時間順延推遲到下週一上午呢？'),
    ('No problem at all; let us lock in Monday at ten oclock.', '完全沒問題，那我們就敲定在下週一上午十點整。'),
    ('I apologize sincerely for any inconvenience this change caused.', '對於這次臨時改期給您造成的任何不便，我深感抱歉。'),
    ('You are breaking up a bit; the connection is rather unstable.', '你的聲音聽起來有點斷斷續續的，通話訊號似乎不太穩定。'),
    ('Could you please repeat that last sentence more clearly?', '能麻煩你把剛才說的那最後一句話再清楚重複一次嗎？'),
    ('Let me hang up and dial your number again right away.', '讓我先掛斷電話，然後立刻重新撥打給您。'),
    ('Can you hear my voice clearly now on this line?', '請問您現在在電話線上能夠聽得清楚我的聲音了嗎？'),
    ('Yes, the line is crystal clear now; please go ahead.', '是的，現在通話非常清晰流暢，請繼續說明。'),
    ('I am calling in regard to the invoice sent last Wednesday.', '我打這通電話是想詢問關於上週三寄出的請款發票事宜。'),
    ('Has your finance accounting team processed the payment yet?', '請問貴公司的財務會計團隊已經處理那筆款項的匯款了嗎？'),
    ('The wire transfer was completed this morning; here is the transaction code.', '電匯手續已於今天上午順利完成，這是交易轉帳序號。'),
    ('I will send you a formal confirmation email immediately.', '我會立刻發送一封正式的確認電子郵件至您的信箱。'),
    ('Please check your spam or junk folder if you do not receive it.', '如果您在收件匣沒有收到，請順便檢查一下垃圾郵件匣。'),
    ('Thank you for returning my phone call so promptly today.', '非常感謝您今天如此迅速及時地回覆我的電話。'),
    ('It is always a genuine pleasure doing business with your team.', '與您優秀的專業團隊進行商業合作始終是一件無比愉快的事。'),
    ('If you need anything else, do not hesitate to contact me.', '若您後續有任何其他需要協助之處，請隨時直接與我聯繫。'),
    ('Have a wonderful afternoon and a great rest of your week!', '祝您度過一個美好的下午，並祝您本週接下來的一切順心！'),
    ('I will follow up with you early next week with more details.', '我將於下週初主動與您聯繫並提供更詳盡的細節資料。'),
    ('Could you spell your last name for our official guest records?', '能請您拼寫一下您的英文姓氏，以便我們登記訪客紀錄嗎？'),
    ('It is spelled C-H-A-N-G, as in Charles, Hotel, Alpha, November, Golf.', '拼寫是 C-H-A-N-G。'),
    ('Thank you, I have recorded your full name in our system.', '謝謝您，我已經在系統中完整記錄了您的全名。'),
    ('Please hold the line for a moment while I transfer your call.', '請在線上稍候片刻，我立刻為您將電話轉接到相關部門。'),
    ('I am connecting you to customer service; please stay on the line.', '我正在為您轉接至顧客服務部門，請不要掛斷電話。'),
    ('All of our customer representatives are currently busy assisting callers.', '目前我們所有的客服專員皆在通話忙線服務其他客戶中。'),
    ('Your call is important to us; please hold for the next agent.', '您的來電對我們至關重要，請繼續在線上等候下一位專員。'),
    ('Press one for sales, press two for technical support assistance.', '如需業務諮詢請按一，如需技術支援與售後協助請按二。'),
    ('To leave a voicemail message, please speak after the beep tone.', '如欲留下語音信箱留言，請在嗶聲提示音響起後開始說話。'),
    ('I am leaving a message regarding my recent online merchandise order.', '我留言是想詢問關於我最近在線上訂購的商品訂單狀況。'),
    ('My order confirmation tracking number is US-88392.', '我的線上訂單確認追蹤物流編號是 US-88392。'),
    ('Please call me back at your earliest possible convenience.', '請在您方便的時候儘早回撥電話給我，非常感謝。'),
    ('I will be out of the office starting tomorrow until next Friday.', '我將從明天起開始休假不在辦公室，直到下週五才返回。'),
    ('For urgent matters during my absence, please contact my deputy.', '在我休假離公期間若有緊急要務，請聯繫我的職務代理人。'),
    ('I will have limited access to my work email while traveling.', '出差旅行期間我查閱工作電子郵件的頻率與權限將受到限制。'),
    ('Let us set up a virtual video conference call via Zoom.', '讓我們透過 Zoom 軟體安排一場線上的視訊視訊會議。'),
    ('I have sent the meeting link and passcode to your calendar.', '我已經將視訊會議的專屬連結與通關密碼寄至您的行事曆。'),
    ('Please make sure your microphone and webcam are functional.', '會議開始前請務必先確認您的麥克風與視訊鏡頭運作正常。'),
    ('You are currently on mute; please click the unmute microphone icon.', '你目前處於靜音狀態，請點擊螢幕下方的解除靜音麥克風圖示。'),
    ('Can everyone see my shared presentation slides on the screen?', '請問螢幕前所有與會者都能清楚看見我所共享的簡報畫面嗎？'),
    ('Yes, your screen is clearly visible and your audio sounds great.', '是的，你的螢幕畫面非常清晰，聲音傳遞也相當清晰清楚。'),
    ('Let us record this online session for team members who could not attend.', '讓我們將這場線上會議錄製下來，供無法出席的同仁事後觀看。'),
    ('Please type your questions in the chat box during the talk.', '在演講進行期間，歡迎大家隨時將問題打在聊天室留言框內。'),
    ('We will dedicate the final fifteen minutes to open Q and A.', '我們將把會議最後十五分鐘的時間專門留作公開問答交流時間。'),
    ('Thank you for organizing this seamless virtual product demonstration.', '感謝您用心籌辦這場流程流暢無比的線上產品功能展示會。'),
    ('I will email the presentation slide deck to all registered attendees.', '我會把本次簡報的完整投影片檔案寄送給所有報名的參與者。'),
    ('Let us stay aligned on our communication channels like Slack.', '讓我們在 Slack 等即時內部通訊管道上隨時保持步調與資訊一致。'),
    ('Please tag me with an at mention if anything urgent arises.', '如果出現任何緊急狀況，請直接在訊息中標註我的帳號通知我。'),
    ('I usually reply to all direct messages within two hours.', '所有的私人即時訊息，我通常都會在兩個小時內給予回覆。'),
    ('Let us avoid sending non-urgent messages outside business hours.', '非緊急要事，讓我們盡量避免在非上班工作時段發送訊息打擾。'),
    ('Respecting work-life boundaries fosters long-term employee well-being.', '尊重工作與生活的界線，有助於維護員工長期的身心健康與福祉。'),
    ('I have added the project milestones to our shared collaboration board.', '我已經將專案的所有重大里程碑新增到我們的共享協作看板上了。'),
    ('Please update the status of your assigned cards by end of day.', '請各位同仁在今天下班前更新各自負責的任務卡片最新狀態。'),
    ('Transparency in project tracking ensures accountability and trust.', '專案進度追蹤的公開透明是確保執行責任心與建立信任的基石。'),
    ('I will send a summary email recapping our key agreements today.', '我會發送一封總結郵件，梳理歸納我們今天達成的各項核心共識。'),
    ('Please reply with your explicit approval so we can proceed.', '請回信給予您明確的正式核准，以便我們能立即著手推進下一步。'),
    ('We are ready to kick off the project immediately upon sign-off.', '一旦獲得正式簽署核准，我們隨時準備好立即全面啟動該專案。'),
    ('Thank you for your swift cooperation and seamless coordination.', '非常感謝您迅速高效的通力合作與毫無障礙的無縫對接協調。'),
    ('It is a real pleasure collaborating with true professionals like you.', '能與像您這樣真正卓越專業的菁英人才攜手合作真是莫大的榮幸。'),
    ('Let us maintain this momentum throughout the entire project lifecycle.', '讓我們在整個專案的生命週期中，始終保持這股高昂的衝勁與動力。'),
    ('I will notify you immediately if there are any changes to plans.', '如果計畫有任何突發變動，我會在第一時間立即主動通知您知悉。'),
    ('Feel free to reach out anytime if you require further clarification.', '如果您後續需要任何進一步的澄清或說明，歡迎隨時與我聯繫。'),
    ('Our dedicated customer support hotline is available around the clock.', '我們專屬的客戶服務支援熱線全年無休、二十四小時隨時為您待命。'),
    ('We value your feedback and strive to continually improve our communication.', '我們無比重視您的寶貴回饋，並持續致力於不斷優化我們的溝通品質。'),
    ('Thank you once again for your partnership and enduring trust.', '再次誠摯感謝您長期以來的卓越合作夥伴關係與始終如一的信任。'),
    ('Wishing you continued prosperity, growth, and resounding success ahead!', '預祝您的事業蒸蒸日上、蓬勃發展，未來取得更加輝煌耀眼的成功！'),
    ('Looking forward to speaking with you again in the near future.', '由衷期待在不久的將來能再次與您通話交流、共商合作。'),
    ('Take care, and have a safe and wonderful rest of the week.', '請多保重，並祝您在本週接下來的日子裡平安順遂、萬事如意。'),
    ('Goodbye for now, and speak to you again very soon.', '先告一段落了，期待很快能再次與您對話交流，再會！'),
    ('Thank you for calling; we look forward to serving you again.', '感謝您的來電洽詢，我們熱切期盼未來能有機會再次竭誠為您服務。')
])

# 12. 生活健康與日常 (100)
add('生活健康與日常', [
    ('Maintaining a balanced diet and regular exercise is vital for health.', '維持均衡的飲食與規律的運動對身體健康至關重要。'),
    ('I try to drink at least eight glasses of clean water every day.', '我每天盡量喝足至少八杯純淨的飲用水以保持水分。'),
    ('Getting seven to eight hours of sound sleep restores vital energy.', '每晚維持七到八小時優質深層睡眠能恢復身體充沛精力。'),
    ('I have a severe headache and feel a little dizzy this morning.', '我今天早上偏頭痛得很厲害，而且感到有些頭暈目眩。'),
    ('You look pale; you should probably go home and rest.', '你的臉色看起來很蒼白，你可能應該早點回家躺著休息。'),
    ('I think I caught a common cold with a runny nose and cough.', '我想我可能是不小心著涼感冒了，一直流鼻水而且咳嗽。'),
    ('Drink plenty of warm lemon water and take vitamin C supplements.', '多喝溫熱的檸檬水，並且適量補充一些維他命 C 營養品。'),
    ('I would like to make an appointment to see Dr. Smith on Friday.', '我想預約預訂本週五上午看 Smith 醫師的門診門診。'),
    ('What symptoms are you experiencing, and how long have they lasted?', '請問您目前出現了哪些不適症狀？這些症狀持續了多久？'),
    ('I have had a mild fever and body aches for two straight days.', '我已經連續兩天出現輕微發燒以及全身肌肉痠痛的症狀了。'),
    ('Please take this prescribed medication three times daily after meals.', '請依照處方指示於三餐飯後服用這款開立的藥物，每日三次。'),
    ('Are there any common side effects like drowsiness or dry mouth?', '請問服用這種藥物會產生嗜睡或口乾舌燥等常見副作用嗎？'),
    ('Do not operate heavy machinery or drive after taking this medicine.', '服用本藥品之後，請切勿操作重型機械設備或親自開車駕駛。'),
    ('My annual comprehensive health checkup showed excellent physical results.', '我的年度全面健康檢查報告出爐了，各項生理數值都非常健康優良。'),
    ('Regular dental checkups and teeth cleaning prevent gum disease.', '定期進行牙科口腔檢查與洗牙能夠有效預防牙周病與蛀牙。'),
    ('I brush my teeth twice a day and use dental floss every night.', '我每天早晚各刷牙一次，並且每晚睡前都會使用牙線清潔齒縫。'),
    ('Wearing sunglasses protects your delicate eyes from damaging ultraviolet rays.', '外出配戴太陽眼鏡能有效保護脆弱的雙眼免受紫外線傷害。'),
    ('Remember to apply sunscreen before engaging in outdoor summer sports.', '在進行夏季戶外運動之前，請務必記得全身塗抹防曬乳液。'),
    ('Daily meditation and mindfulness practice reduce stress and improve focus.', '每天練習冥想靜心與正念練習能夠舒緩壓力並提升專注力。'),
    ('Taking short walking breaks during long working hours relieves back pain.', '長時間久坐工作期間起身短暫散步走動能有效減輕腰酸背痛。'),
    ('Cooking wholesome meals at home is healthier and more cost-effective.', '在家親自烹調營養健康的家常菜餚既健康又能節省開銷。'),
    ('Fresh fruits, leafy greens, and whole grains should fill your plate.', '新鮮水果、深綠色蔬菜與全穀根莖類食物應佔據餐盤的大半。'),
    ('Limit your daily consumption of refined sugar, sodium, and saturated fats.', '日常生活中應儘量限制精緻糖分、鈉鹽以及飽和脂肪的攝取量。'),
    ('I love starting my morning with a refreshing thirty-minute jogging routine.', '我非常喜歡以三十分鐘清爽暢快的慢跑晨跑開啟充滿活力的一天。'),
    ('Yoga enhances flexibility, muscle strength, and inner mental calmness.', '練習瑜珈能增強身體柔軟度、鍛鍊核心肌群並帶來內心平靜。'),
    ('Always perform proper warm-up stretching exercises before rigorous workouts.', '在進行高強度激烈運動之前，請務必做好充足正確的暖身伸展。'),
    ('Staying well hydrated during exercise prevents painful muscle cramps.', '運動過程中隨時補充充足的水分能有效預防痛苦的肌肉抽筋。'),
    ('I feel so refreshed and revitalized after my morning workout.', '完成晨間運動鍛鍊之後，我感到整個人神清氣爽、脫胎換骨。'),
    ('A hot herbal chamomile tea before bedtime promotes deep, restful sleep.', '睡前半小時喝一杯溫熱的洋甘菊草本花茶能促進深層安穩入眠。'),
    ('Avoid staring at digital screens right before falling asleep in bed.', '在床上準備入睡前，應盡量避免緊盯著智慧手機或平板螢幕。'),
    ('Creating a cozy and dark bedroom environment improves overall sleep quality.', '營造一個舒適溫馨且遮光良好的臥室環境能顯著提升睡眠品質。'),
    ('Household chores like vacuuming and laundry keep living spaces tidy.', '吸塵吸地、洗衣服等日常家事雜務能讓居家生活空間維持整潔。'),
    ('I enjoy doing a deep spring cleaning of my apartment on weekends.', '我喜歡在週末休假時為自己的公寓進行一次徹底的大掃除整理。'),
    ('Decluttering unused belongings brings a refreshing sense of spacious clarity.', '斷捨離清除家中長年不用的雜物能為心靈帶來清爽開闊的空間感。'),
    ('Recycling plastic, glass, and paper protects our shared global environment.', '做好塑膠、玻璃與紙類的資源回收分類能守護我們共同的地球環境。'),
    ('Conserving water and electricity at home reduces our carbon footprint.', '在日常生活中隨手節約用水與用電能實質減少我們的個人碳足跡。'),
    ('I always carry a reusable shopping tote bag and a stainless water bottle.', '我出門時總是會隨身自備環保購物提袋以及不鏽鋼環保水壺。'),
    ('Adopting sustainable green habits makes a positive impact on our planet.', '在日常養成永續環保的生活好習慣能對我們的地球產生正面影響。'),
    ('Spending quality time in natural parks reduces mental fatigue and anxiety.', '多抽空身處大自然綠色公園之中能有效減輕心理疲勞與焦慮情緒。'),
    ('Gardening and tending to blooming potted plants is a peaceful therapeutic hobby.', '在陽台園藝植栽、照顧開花盆栽是一項寧靜療癒的舒壓興趣嗜好。'),
    ('Listening to soothing classical music helps me concentrate while studying.', '在專心讀書溫習功課時，聆聽舒緩悠揚的古典音樂有助於集中專注力。'),
    ('I set aside thirty minutes every evening to read inspiring literature.', '我每天晚上都會特地保留三十分鐘的悠閒時光閱讀啟迪心靈的文學名著。'),
    ('Continuous learning throughout adulthood keeps the human mind sharp and agile.', '在成年生活中保持終身持續學習的熱忱能讓大腦思維保持敏銳敏捷。'),
    ('Learning a foreign language opens doors to fascinating cultures and friendships.', '學習一門外國語言能為你開啟通往迷人異國文化與跨國友誼的大門。'),
    ('Practicing spoken conversation with native speakers builds real fluency quickly.', '常與外語母語人士進行口語對話練習能以最快速度建立起流利度。'),
    ('Do not be afraid of making grammatical errors; communication is the goal.', '開口練習時千萬別害怕犯文法錯誤，達成有效溝通才是真正的目的。'),
    ('Listening to English podcasts on your daily commute turns idle time into learning.', '在每天上下班通勤途中收聽英語播客節目能將瑣碎時間化為學習良機。'),
    ('Watching foreign films with English subtitles trains your listening comprehension.', '觀賞外語電影時搭配英文字幕觀看能循序漸進鍛鍊你的英語聽力理解。'),
    ('Reviewing flashcards daily reinforces new vocabulary words in long-term memory.', '每天規律複習單字記憶卡能將新學到的詞彙牢牢鞏固在長期記憶中。'),
    ('Celebrate small daily progress; consistency is the secret sauce to mastery.', '要為每天取得的微小進步感到欣喜自豪，堅持不懈正是精通的終極秘訣。'),
    ('I love baking fresh homemade whole wheat sourdough bread on Sunday mornings.', '我熱愛在週日清晨親自動手烘焙新鮮現烤的自製全麥酸種麵包。'),
    ('The mouthwatering smell of freshly brewed coffee fills the whole kitchen.', '剛沖煮好熱咖啡所飄散出的誘人醇厚香氣瞬間瀰漫了整個廚房空間。'),
    ('A hearty, nourishing breakfast fuels your body for an active, demanding day.', '一份豐盛且營養滿分的早餐能為你一整天忙碌充實的行程注入滿滿動力。'),
    ('I enjoy strolling through the local weekend farmers market for organic produce.', '我喜歡在週末漫步逛逛當地的農夫市集，採買新鮮產地直送的有機蔬果。'),
    ('Locally sourced ingredients are fresher, tastier, and support local farmers.', '在地採購的農特產食材更加新鮮美味，同時也能實質支持在地小農。'),
    ('Meal prepping healthy lunches for the week saves precious time and money.', '在週末提前備好未來一整週的健康午餐便當既能省下寶貴時間又能省錢。'),
    ('Drinking a warm mug of ginger tea with honey soothes an irritated throat.', '喝一杯加了天然蜂蜜的溫熱生薑茶能溫和舒緩發炎紅腫的喉嚨不適。'),
    ('Taking a relaxing bubble bath with lavender essential oil melts away tension.', '在浴缸裡滴入幾滴薰衣草精油泡個放鬆的泡泡浴能徹底融化緊繃情緒。'),
    ('Writing down three things you are grateful for daily cultivates optimism.', '每天在日記本裡寫下三件心存感激的事物，能持續培養積極樂觀的人生觀。'),
    ('Maintaining strong, meaningful bonds with close friends enriches our lives.', '與身邊知心好友維持深厚真摯的情感連結能極大豐富我們的人生滋味。'),
    ('Never hesitate to reach out to loved ones when you feel overwhelmed.', '當你感到生活中壓力過大承受不住時，千萬不要猶豫主動向至親好友傾訴。'),
    ('Compassion, kindness, and empathy make the world a warmer, gentler place.', '常懷慈悲同理心、友善待人與善解人意，會讓這個世界變得更溫暖柔和。'),
    ('Taking responsibility for your own happiness empowers you to thrive.', '對自己的幸福快樂負起全然責任，將賦予你茁壯成長、綻放光芒的力量。'),
    ('Life is a beautiful journey filled with endless opportunities to grow.', '人生是一趟無比美妙的精彩旅程，處處充滿著讓我們學習成長的無限契機。'),
    ('Embrace changes with an open heart and a curious, adventurous spirit.', '請敞開寬廣的心胸，帶著充滿好奇與勇敢冒險的探索精神去擁抱各項改變。'),
    ('Every single sunrise brings a brand new chance to start afresh and shine.', '每一道升起的清晨曙光都帶來了嶄新的契機，讓你重新出發、散發光芒。'),
    ('Believe in your unique talents and never underestimate your inner strength.', '堅定相信自己獨一無二的天賦才華，永遠不要低估你內心深處的強大力量。'),
    ('May good health, enduring joy, and abundant peace accompany you always.', '願健康的體魄、長久的喜悅與豐盛的內心平安，永遠伴隨在你的左右。'),
    ('Take good care of your body, mind, and spirit each and every single day.', '在未來的每一天裡，請都要好好溫柔呵護照顧你的身體、心靈與精神。'),
    ('I like taking deep breaths of crisp fresh air on mountain hiking paths.', '在山間登山健行步道上大口呼吸清脆新鮮的大自然空氣，令人心曠神怡。'),
    ('Walking barefoot on morning grass connects our spirit with Mother Earth.', '清晨赤腳踩在沾滿露水的青草地上漫步，能讓心靈與大地之母緊密相連。'),
    ('Remember to stretch your legs and stay hydrated on long-distance flights.', '在搭乘長途長程飛行航班時，請記得定時起身活動雙腿並多喝水補充水分。'),
    ('Healthy boundaries protect your personal energy and nurture self-respect.', '在人際中建立健康明確的界線能保護個人的正能量，並滋養內在的自尊自信。'),
    ('A clean and organized work desk sparks creative thoughts and efficiency.', '一張乾淨整潔且井井有條的辦公書桌能激發無限的創意思維並大幅提升效率。'),
    ('I find immense tranquility in watching waves gently lap against the shore.', '靜靜凝望著海浪溫柔拍打著海灘沿岸，讓我內心體會到無比的寧靜與安詳。'),
    ('Laughter shared with cherished family members is life most precious treasure.', '與最摯愛的家人共同開懷大笑的幸福時光，是人生中最彌足珍貴的無價之寶。'),
    ('Stay curious, keep exploring new passions, and never stop learning.', '時刻保持好奇心，持續勇敢探索新的熱情所在，並且終生永不停止學習前進。'),
    ('You are capable of overcoming any challenge with patience and dedication.', '只要你懷抱著無比的耐心與專注投入，你絕對有能力克服任何艱難的挑戰。'),
    ('Celebrate how far you have already come while keeping your eyes forward.', '在堅定注視前方道路的同時，也別忘了為自己一路走來的成長與進步喝采。'),
    ('May your life be illuminated with endless warmth, wonder, and profound happiness.', '願你漫長的人生旅程中，處處被無盡的溫暖、驚奇的美好與深沉的幸福所照亮。')
])

# Save and verify
total = len(data)
print(f'Total sentences generated: {total}')

# Ensure uniqueness of English sentences
seen = set()
duplicates = []
for item in data:
    if item['en'] in seen:
        duplicates.append(item['en'])
    seen.add(item['en'])

if duplicates:
    print(f'WARNING: Found {len(duplicates)} duplicates: {duplicates[:5]}')
else:
    print('All sentences are completely unique!')

# Write output files
os.makedirs('web/data', exist_ok=True)
os.makedirs('data', exist_ok=True)

with open('web/data/sentences_1000.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

with open('data/sentences_1000.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print('Successfully exported web/data/sentences_1000.json and data/sentences_1000.json')
