# -*- coding: utf-8 -*-
import json
import os

data = []

def add(cat, items):
    for en, zh in items:
        data.append({
            'id': len(data) + 1,
            'en': en.strip(),
            'zh': zh.strip(),
            'category': cat
        })

# ==========================================
# 1. 日常問候與道別 (100)
# ==========================================
add('日常問候與道別', [
    ("Good morning! How are you doing today?", "早安！你今天過得好嗎？"),
    ("Good afternoon! How is your day going so far?", "午安！今天到目前為止順利嗎？"),
    ("Good evening! Did you have a good day?", "晚上好！今天過得好嗎？"),
    ("How's everything going with you?", "你一切都還順利嗎？"),
    ("How have you been lately?", "你最近過得怎麼樣？"),
    ("What's up? Anything new?", "嗨！最近有什麼新鮮事嗎？"),
    ("How's life treating you these days?", "最近日子過得還好嗎？"),
    ("Long time no see! What have you been up to?", "好久不見！你最近都在忙什麼？"),
    ("It's been a while, hasn't it?", "好一陣子沒見了，對吧？"),
    ("I haven't seen you in ages!", "我好久沒見到你了！"),
    ("It's so great to see you again.", "能再見到你真是太好了。"),
    ("What's new with you?", "最近有什麼新消息嗎？"),
    ("Not much, just the usual routine.", "沒什麼特別的，就跟平常一樣。"),
    ("Same old, same old.", "老樣子，沒什麼變。"),
    ("Couldn't be better, thanks!", "好得不能再好了，謝謝！"),
    ("I'm doing pretty well, thanks for asking.", "我過得蠻好的，謝謝你的關心。"),
    ("I've been keeping busy with work.", "我最近工作一直蠻忙的。"),
    ("I'm just hanging in there.", "就還過得去／還在撐著。"),
    ("How's your morning going?", "你今天早上過得好嗎？"),
    ("Morning! Did you sleep well last night?", "早安！昨晚睡得好嗎？"),
    ("How was your weekend?", "你週末過得如何？"),
    ("Did you do anything fun over the weekend?", "你週末有去哪裡玩嗎？"),
    ("Are you having a good day today?", "你今天過得開心嗎？"),
    ("I hope you're having a wonderful day.", "希望你今天過得很順心。"),
    ("Have a great day ahead!", "祝你有個美好順利的一天！"),
    ("Enjoy the rest of your day!", "好好享受今天剩下的時間！"),
    ("Have a good one!", "祝你今天愉快！"),
    ("Have a fantastic weekend!", "祝你有個超棒的週末！"),
    ("I've got to get going now.", "我現在得動身先走了。"),
    ("I need to head out soon.", "我等等得準備出發了。"),
    ("I should probably head home now.", "我想我該回家了。"),
    ("I have to run, or I'll be late.", "我得趕緊走了，不然要遲到了。"),
    ("I must be off now. See you later!", "我該先告辭了，晚點見！"),
    ("Catch you later!", "晚點再聊！／回頭見！"),
    ("Talk to you soon!", "下次再聊囉！"),
    ("I'll see you tomorrow morning.", "明天早上見。"),
    ("See you next Monday!", "下週一見！"),
    ("I'll catch up with you later today.", "今天晚點再找你聊。"),
    ("It was so nice catching up with you.", "今天跟你敘舊真的很開心。"),
    ("I'm really glad we bumped into each other.", "真高興今天能遇到你。"),
    ("What a small world to run into you here!", "在這裡巧遇你，世界真小！"),
    ("Let's keep in touch more often.", "我們以後多保持聯絡喔。"),
    ("Take care of yourself!", "好好照顧自己，保重喔！"),
    ("Stay safe and healthy!", "注意安全，保持健康！"),
    ("Have a safe trip home!", "回家路上小心喔！"),
    ("Get home safe!", "平安到家喔！"),
    ("Let me know when you get home safely.", "安全到家後傳個訊息跟我說一聲。"),
    ("Text me when you get there.", "你到了之後傳訊息給我。"),
    ("Say hi to your family for me.", "替我向你的家人問好。"),
    ("Give my best to everyone at home.", "替我向家裡的大家問好。"),
    ("Drop by anytime you're around here.", "只要你來這附近，隨時過來坐坐。"),
    ("I hope to see you again real soon.", "希望很快能再見到你。"),
    ("Enjoy your vacation!", "祝你假期玩得開心！"),
    ("Have a safe flight!", "祝你飛行旅途平安！"),
    ("Welcome back! How was your trip?", "歡迎回來！這趟旅行好玩嗎？"),
    ("Good luck with your interview today!", "祝你今天的面試一切順利！"),
    ("Fingers crossed for your test!", "為你的考試祈求好運！加油！"),
    ("I'll see you at the party tonight.", "我們今晚派對上見。"),
    ("Let's grab lunch sometime next week.", "下週找時間一起吃個午餐吧。"),
    ("I'll text you the details later.", "我晚點把細節傳訊息給你。"),
    ("Take your time and get some rest.", "別著急，好好休息一下。"),
    ("Good night! Sleep tight and sweet dreams.", "晚安！睡個好覺，祝好夢。"),
    ("How are you feeling this morning?", "你今天早上感覺好點了嗎？"),
    ("Are you ready for the day?", "準備好迎接今天了嗎？"),
    ("I'm heading out to grab some coffee. Want anything?", "我要去買杯咖啡，你有要帶什麼嗎？"),
    ("Sorry, I have to take this call real quick.", "抱歉，我需要緊急接一下這通電話。"),
    ("I'm on my way out the door now.", "我現在正準備出門了。"),
    ("Thanks for coming all the way over.", "謝謝你特地大老遠跑一趟過來。"),
    ("Happy birthday! I hope you have a great one.", "生日快樂！希望你今天玩得開心。"),
    ("Congratulations on your new job!", "恭喜你找到新工作！"),
    ("I'm so happy for you!", "我真替你感到高興！"),
    ("I'll see you right after work.", "下班後我們立刻碰面。"),
    ("Let's meet up again before the weekend.", "週末前我們再約出來聚聚吧。"),
    ("Have fun tonight!", "今晚好好玩，盡情享受！"),
    ("Stay warm! It's really chilly outside.", "穿暖和點！外面真的蠻冷的。"),
    ("Stay cool in this heat!", "天氣這麼熱，注意防暑降溫！"),
    ("I'm leaving now. Have a good night!", "我要先離開了，祝你有個愉快的夜晚！"),
    ("I'll talk to you first thing tomorrow.", "明天一早我第一件事就聯絡你。"),
    ("Keep me posted, okay?", "有任何最新消息隨時跟我說喔！"),
    ("Don't be a stranger!", "常保持聯絡，別搞失蹤喔！"),
    ("Hey there, how's your week going?", "嗨，你這週過得還順利嗎？"),
    ("Just checking in to see how you are.", "只是想打個招呼，關心一下你最近如何。"),
    ("Hope you're having a relaxing Sunday.", "希望你有個輕鬆愜意的週日。"),
    ("Glad I caught you before you left.", "真高興在你離開前剛好遇到你。"),
    ("Are you heading out already?", "你這就要走了嗎？"),
    ("Time really flies when we're chatting.", "我們聊著聊著，時間過得真快。"),
    ("I'll let you get back to what you were doing.", "我就不打擾你了，你繼續忙吧。"),
    ("Thanks for the chat, it was really nice.", "謝謝陪我聊天，真的很開心。"),
    ("See you in a couple of days.", "過兩天見囉。"),
    ("Take it easy and enjoy your evening.", "放輕鬆，好好享受今晚的時光。"),
    ("Hope to bump into you again soon.", "希望很快能再巧遇你。"),
    ("I'm about to sign off for the night.", "我差不多要離線去睡覺了。"),
    ("Let's catch up properly over the weekend.", "週末我們找時間好好坐下來聊聊。"),
    ("Have a safe drive home in this rain.", "下雨天開車回家路上小心點。"),
    ("Wishing you the best with your presentation.", "祝你今天的簡報順利成功。"),
    ("Hope you have a quick recovery!", "祝你早日康復！"),
    ("Catch you on the flip side!", "回頭再見囉！"),
    ("I'm off! See you guys tomorrow.", "我閃人囉！大家明天見。"),
    ("Thanks for dropping by!", "謝謝你特地過來坐坐！"),
    ("Take care and talk soon!", "多保重，很快再聊！")
])

# ==========================================
# 2. 社交閒聊與近況 (100)
# ==========================================
add('社交閒聊與介紹', [
    ("Hi! I'm Alex. Nice to meet you!", "嗨！我是 Alex，很高興認識你！"),
    ("Nice to meet you too! Where are you from?", "也很高興認識你！你是哪裡人呢？"),
    ("I grew up in Taipei, but I live here now.", "我在台北長大，但現在住在這邊。"),
    ("How long have you lived around here?", "你在這附近住多久了呀？"),
    ("What do you usually do in your free time?", "你休閒時通常都喜歡做些什麼？"),
    ("I love watching movies and trying new food.", "我喜歡看電影和到處吃美食。"),
    ("Have you seen any good movies lately?", "你最近有看過什麼好看的電影嗎？"),
    ("I just finished watching a great series on Netflix.", "我剛在 Netflix 上追完一部超好看的影集。"),
    ("What kind of music are you into?", "你平時都聽哪種類型的音樂？"),
    ("I listen to a lot of pop and indie music.", "我蠻常聽流行音樂和獨立樂團的。"),
    ("Have you been to that new cafe down the street?", "你有去過街角新開的那家咖啡廳嗎？"),
    ("Not yet! Is the coffee there any good?", "還沒耶！那裡的咖啡好喝嗎？"),
    ("Yeah, their iced latte is amazing!", "超好喝的，他們的冰拿鐵很讚！"),
    ("We should definitely check it out together.", "我們改天一定要一起去朝聖看看。"),
    ("Are you free this Saturday afternoon?", "你這週六下午有空嗎？"),
    ("What are your plans for the upcoming holiday?", "接下來的連假你有什麼安排嗎？"),
    ("I'm just planning to relax at home and sleep in.", "我只打算待在家好好放鬆、睡到自然醒。"),
    ("Are you doing anything special for your birthday?", "你生日有打算做什麼特別的慶祝嗎？"),
    ("The weather is so nice and sunny today!", "今天天氣真好，陽光好舒服！"),
    ("I know, right? Perfect day for a walk.", "對啊！超適合出門散步的。"),
    ("It's supposed to rain tomorrow, so bring an umbrella.", "聽說明天會下雨，記得帶把傘。"),
    ("I can't stand this hot and humid weather.", "我真受不了這種又悶又熱的天氣。"),
    ("Are you a morning person or a night owl?", "你是早起型的人還是夜貓子呀？"),
    ("I'm definitely a night owl. I can't wake up early.", "我絕對是夜貓子，早上完全起不來。"),
    ("Do you have any pets at home?", "你有養任何寵物嗎？"),
    ("Yes! I have a golden retriever and a cat.", "有啊！我養了一隻黃金獵犬和一隻貓。"),
    ("That's so adorable! How old are they?", "太可愛了吧！牠們幾歲了？"),
    ("Do you like to cook, or do you prefer eating out?", "你喜歡自己煮飯，還是比較喜歡外食？"),
    ("I usually cook on weekdays to save some money.", "我平日通常自己煮，比較省錢。"),
    ("What's your absolute favorite food?", "你最愛吃的食物是什麼？"),
    ("I could eat pizza and pasta every single day.", "我每天吃披薩和義大利麵都吃不膩。"),
    ("Have you ever traveled abroad alone?", "你曾經一個人出國自助旅行過嗎？"),
    ("Yeah, I went to Japan by myself last year.", "有啊，我去年自己一個人去日本玩。"),
    ("That sounds like such a great adventure!", "聽起來是一趟很棒的冒險體驗！"),
    ("Where do you want to travel next?", "你下次最想去哪裡旅遊？"),
    ("I've always wanted to visit Europe.", "我一直很想去歐洲走走。"),
    ("How is work going for you these days?", "你最近工作上一切都還順利嗎？"),
    ("It's been pretty busy, but I'm managing.", "蠻忙碌的，但還應付得過來。"),
    ("Do you like your current job?", "你喜歡你現在這份工作嗎？"),
    ("My team is great, so that makes a big difference.", "我的團隊同事很棒，這差很多。"),
    ("I really need a vacation right now.", "我現在真的很需要放個大假。"),
    ("Tell me about it! I feel the exact same way.", "完全同意！我也有同感。"),
    ("How do you usually commute to work?", "你平時都怎麼通勤上班？"),
    ("I just take the subway; it's fast and easy.", "我都搭捷運／地鐵，又快又方便。"),
    ("Do you play any sports or work out regularly?", "你有在做什麼運動或定期去健身房嗎？"),
    ("I try to go to the gym three times a week.", "我盡量每週去健身房三次。"),
    ("Good for you! I need to start working out too.", "真厲害！我也得開始運動了。"),
    ("What do you like to do on rainy days?", "下雨天你通常喜歡做些什麼？"),
    ("I like staying in bed, reading, and drinking tea.", "我喜歡窩在床上看書、喝杯熱茶。"),
    ("Have you tried that new restaurant near the station?", "你有吃過車站附近那家新開的餐廳嗎？"),
    ("I heard the food is great, but the line is so long.", "我聽說很好吃，但排隊排好長。"),
    ("Yeah, we should book a table in advance.", "對啊，我們應該要先提前訂位。"),
    ("Are you watching the game tonight?", "你今晚會看那場球賽嗎？"),
    ("Of course! My whole family is watching it.", "當然！我們全家都要一起看。"),
    ("Who do you think is going to win?", "你覺得哪一隊會贏？"),
    ("It's hard to say, both teams are really strong.", "很難說耶，兩隊實力都很強。"),
    ("Do you follow any podcasts?", "你有在聽什麼 Podcast 節目嗎？"),
    ("I listen to comedy and tech podcasts during my commute.", "我通勤時都聽一些搞笑或科技類的 Podcast。"),
    ("Can you recommend a good place for brunch around here?", "你能推薦這附近哪裡有不錯的早午餐嗎？"),
    ("There's a cozy little spot just two blocks away.", "走兩個街區就有一家很溫馨的小店喔。"),
    ("Let's go there together this weekend.", "那我們這週末一起去吃吧。"),
    ("How did you two first meet?", "你們兩個當初是怎麼認識的啊？"),
    ("We were classmates back in college.", "我們以前大學時是同班同學。"),
    ("No way! That's such a cool coincidence.", "真的假的！也太巧了吧。"),
    ("What are you drinking? Is it good?", "你喝的是什麼呀？好喝嗎？"),
    ("It's a mango smoothie, super refreshing!", "是芒果冰沙，超級消暑清爽！"),
    ("Mind if I sit here with you?", "你介意我坐在這裡跟你一起嗎？"),
    ("Not at all! Please take a seat.", "完全不介意！請坐請坐。"),
    ("So, how was your day today?", "話說回來，你今天過得如何？"),
    ("Pretty good! Just finished my project on time.", "蠻不錯的！剛剛剛好按時把專案做完。"),
    ("That must be such a relief!", "那一定鬆了一大口氣吧！"),
    ("Are you doing anything after this?", "等等結束後你有要去做什麼嗎？"),
    ("I'm meeting up with a friend for dinner.", "我要跟一個朋友約吃晚餐。"),
    ("Sounds fun! Have a great time.", "聽起來真棒！好好享受喔。"),
    ("I love your jacket! Where did you get it?", "我很喜歡你的外套！你在哪裡買的？"),
    ("Thanks! I got it on sale online.", "謝謝！我是在網路上打折時買的。"),
    ("It looks really good on you.", "穿在你身上真的超好看。"),
    ("Have you ever been to New York?", "你曾經去過紐約嗎？"),
    ("Yeah, I went there two years ago for vacation.", "有啊，我兩年前去那裡度假過。"),
    ("What was your favorite part of the city?", "那座城市你最喜歡的部分是什麼？"),
    ("Central Park was definitely my favorite.", "中央公園絕對是我最喜歡的地方。"),
    ("Are you taking any fun classes right now?", "你最近有在修什麼有趣的課程嗎？"),
    ("I just started learning conversational Spanish.", "我最近剛開始學西語日常會話。"),
    ("That's awesome! Is it hard to learn?", "太酷了！學起來會很難嗎？"),
    ("A bit, but it's really fun so far.", "有一點，但目前為止覺得很有趣。"),
    ("How do you drink your coffee?", "你的咖啡都喝什麼口味的？"),
    ("Just black coffee with no sugar.", "黑咖啡不加糖。"),
    ("I can't drink coffee without milk and sugar.", "我沒辦法喝黑咖啡，一定要加奶加糖。"),
    ("Do you have any brothers or sisters?", "你有兄弟姐妹嗎？"),
    ("I have an older brother and a younger sister.", "我有一個哥哥和一個妹妹。"),
    ("Are you close with them?", "你們感情好嗎？"),
    ("Yeah, we hang out all the time.", "很好啊，我們常常一起出來玩。"),
    ("What's the best concert you've ever been to?", "你看過最棒的演唱會是哪一場？"),
    ("Coldplay! The energy was incredible.", "Coldplay！現場氣氛真的太狂熱了。"),
    ("I'm so jealous, I wish I could go!", "好羨慕喔，我也好想去！"),
    ("Let's definitely buy tickets together next time.", "下次有機會我們一定要一起買票去。"),
    ("It was really nice talking with you today.", "今天能和你聊天真的很愉快。"),
    ("Same here! We should do this again soon.", "我也是！我們近期一定要再聚聚。"),
    ("Don't forget to send me that link later.", "晚點別忘了把那個連結傳給我喔。"),
    ("Will do! Have a wonderful evening.", "沒問題！祝你有個愉快的夜晚。")
])

# ==========================================
# 3. 感謝致歉與禮貌 (100)
# ==========================================
add('感謝致歉與禮貌', [
    ("Thank you so much for your help!", "非常感謝你的幫忙！"),
    ("Thanks a million! I really appreciate it.", "萬分感謝！我真的很感激。"),
    ("I can't thank you enough.", "我真的不知道該怎麼感謝你才好。"),
    ("Thanks for the heads up!", "謝謝你提前提醒／通報我！"),
    ("Thanks for letting me know.", "謝謝你告訴我這件事。"),
    ("Thank you for having me over.", "謝謝你今天邀請我來做客。"),
    ("Thanks for buying me lunch today!", "謝謝你今天請我吃午餐！"),
    ("You're the best! I owe you one.", "你人太好了！我欠你一次人情。"),
    ("I truly appreciate your time and patience.", "我真心感謝你的時間與耐心。"),
    ("Thanks for taking care of that for me.", "謝謝你幫我處理好那件事。"),
    ("You're very welcome!", "不客氣！"),
    ("No problem at all!", "完全沒問題／小事一樁！"),
    ("Don't mention it.", "別客氣／不用掛在心上。"),
    ("Anytime! Glad I could help.", "隨時樂意幫忙！很高興能幫上忙。"),
    ("It's no big deal, really.", "真的沒什麼大不了的啦。"),
    ("My pleasure!", "這是我的榮幸／我很樂意。"),
    ("I'm so sorry, my bad!", "真不好意思，是我的錯！"),
    ("Sorry about that! I didn't mean to.", "不好意思！我不是故意的。"),
    ("I'm really sorry to keep you waiting.", "真的很抱歉讓你久等了。"),
    ("Sorry for being late, traffic was terrible.", "抱歉遲到了，路上塞車塞得很嚴重。"),
    ("I apologize for the misunderstanding.", "對於造成的誤會，我深表歉意。"),
    ("I'm sorry, I totally forgot about it.", "抱歉，我完全把這件事給忘了。"),
    ("Sorry to bother you, but do you have a second?", "不好意思打擾你一下，你有空檔嗎？"),
    ("I didn't mean to cut you off. Go ahead.", "我不是故意打斷你的，你請繼續說。"),
    ("Excuse me, is this seat taken?", "不好意思，請問這個位子有人坐嗎？"),
    ("Excuse me, could you please tell me the time?", "不好意思，能請教一下現在幾點了嗎？"),
    ("Pardon me, I didn't catch that last part.", "不好意思，我剛剛最後那句沒聽清楚。"),
    ("Could you please repeat that one more time?", "可以麻煩你再重複說一次嗎？"),
    ("Could you speak a little slower, please?", "可以請您說得稍微慢一點點嗎？"),
    ("Would you mind opening the window?", "你介意開一下窗戶嗎？"),
    ("Would you mind if I turned down the music?", "你介意我把音樂音量調小一點嗎？"),
    ("Could you do me a quick favor?", "能請你幫我一個小忙嗎？"),
    ("Could you give me a hand with this box?", "可以幫我一起搬這個箱子嗎？"),
    ("Could you pass me the salt, please?", "可以麻煩把鹽巴遞給我嗎？"),
    ("Can I borrow your pen for a second?", "我可以借用一下你的筆嗎？"),
    ("Here you go!", "拿去吧！／給您！"),
    ("After you, please.", "您先請。"),
    ("Go right ahead!", "請便／你請說／你先請！"),
    ("Please make yourself at home.", "請把這裡當自己家，別客氣。"),
    ("Help yourself to some snacks and drinks.", "點心和飲料請自便，儘管享用。"),
    ("I'm really grateful for your kind advice.", "我非常感激你提供的寶貴建議。"),
    ("Thank you for understanding my situation.", "謝謝你能體諒我的處境。"),
    ("Sorry for the late reply, I was tied up all day.", "抱歉這麼晚才回覆，我今天一整天都在忙。"),
    ("No worries, take your time!", "沒關係，你慢慢來不用急！"),
    ("That's totally fine, don't worry about it.", "完全沒關係的，別放在心上。"),
    ("It happens to the best of us.", "這種事大家都會遇到／在所難免啦。"),
    ("Forget about it, it's all good!", "沒事沒事，別想太多！"),
    ("I really appreciate you checking in on me.", "真的很感謝你特地來關心我。"),
    ("Thanks for being so flexible with the schedule.", "謝謝你願意在時間安排上這麼配合與彈性。"),
    ("I appreciate your quick response.", "非常感謝你迅速的回信與回覆。"),
    ("Thank you for looking out for me.", "謝謝你一直以來這麼照顧我。"),
    ("I owe you a cup of coffee for this!", "因為這件事，我一定要請你喝杯咖啡！"),
    ("I can't tell you how much this means to me.", "你不知道這對我來說有多重要，太感謝了。"),
    ("Sorry, I didn't see you there!", "抱歉，我剛剛沒注意到你在那裡！"),
    ("I apologize for the delay in sending this file.", "對於延遲寄出這份檔案，我深感抱歉。"),
    ("Sorry, I didn't mean to startle you.", "抱歉，我不是故意要嚇到你的。"),
    ("Excuse me, could you step aside a little bit?", "不好意思，可以借過／稍微往旁邊站一點嗎？"),
    ("Excuse me, where is the elevator?", "不好意思，請問電梯在哪裡？"),
    ("Could you hold the door for a second, please?", "可以麻煩幫忙按住電梯門一下嗎？"),
    ("Thank you, that was very kind of you.", "謝謝你，你人真好。"),
    ("I really appreciate your hospitality.", "非常感謝您的熱情款待。"),
    ("Thanks for inviting me, I had a blast!", "謝謝你的邀請，我今天玩得超開心的！"),
    ("Thank you for keeping this confidential.", "謝謝你幫我對這件事保守秘密。"),
    ("Sorry, I couldn't hear what you just said.", "抱歉，我剛剛沒聽清楚你說的話。"),
    ("I'm sorry to interrupt your conversation.", "不好意思打擾你們聊天了。"),
    ("Please forgive me for arriving so late.", "請原諒我這麼晚才趕到。"),
    ("It won't happen again, I promise.", "我保證下次絕不會再發生了。"),
    ("Could you possibly help me check this line?", "能麻煩你幫我看一下這一行嗎？"),
    ("Would it be okay if I left a bit early today?", "請問我今天可以稍微早一點點離開嗎？"),
    ("Is it alright if I use your phone charger?", "我可以借用一下你的手機充電器嗎？"),
    ("Sure, go ahead! It's plugged in over there.", "當然可以，拿去用吧！插在那個角落。"),
    ("Thank you for walking me to my car.", "謝謝你陪我走去牽車。"),
    ("Thanks for picking me up at the station.", "謝謝你特地開車來車站接我。"),
    ("I'm sorry for causing you so much trouble.", "很抱歉給你添了這麼多麻煩。"),
    ("It's no trouble at all, happy to help!", "完全不會麻煩，很高興能幫上忙！"),
    ("Thanks for listening to me vent.", "謝謝你願意聽我吐苦水、發牢騷。"),
    ("Anytime, that's what friends are for!", "隨時都行，朋友本來就是用來互相支持的！"),
    ("Thank you for stepping in when I needed help.", "謝謝你在我最需要的時候挺身相助。"),
    ("I really appreciate your thoughtful gesture.", "我真的很感動你的貼心舉動。"),
    ("Sorry, I didn't mean to hurt your feelings.", "對不起，我不是故意要傷害你的感受。"),
    ("I accept your apology, let's move on.", "我接受你的道歉，我們翻篇吧。"),
    ("No hard feelings at all!", "完全沒有芥蒂／我一點都沒生氣！"),
    ("Could you keep an eye on my bag for a minute?", "可以幫我顧一下包包一分鐘嗎？"),
    ("Sure thing, I'll watch it for you.", "沒問題，我會幫你看著。"),
    ("Thanks for holding my place in line.", "謝謝你幫我排隊佔位子。"),
    ("Sorry for calling so late at night.", "抱歉這麼晚了還打電話給你。"),
    ("Don't worry, I was still wide awake.", "別擔心，我本來就還醒著。"),
    ("Could you please lower your voice slightly?", "可以請您稍微放低一下說話音量嗎？"),
    ("Of course, sorry about that!", "當然可以，真是不好意思！"),
    ("Thanks for the sweet compliment!", "謝謝你的誇獎，聽了真開心！"),
    ("Thank you for being so patient with me.", "謝謝你對我這麼有耐心。"),
    ("I couldn't have done it without your guidance.", "要是沒有你的指點，我一個人肯定搞不定。"),
    ("Thanks for the ride, I really appreciate it.", "謝謝你順路載我一程，太感謝了。"),
    ("Drop me off right here, thank you!", "讓我在這裡下車就可以了，謝謝！"),
    ("Sorry to keep you waiting on the line.", "抱歉讓您在電話線上久等了。"),
    ("Thanks for bearing with me today.", "感謝你今天對我的包容與體諒。"),
    ("Thank you for taking the time to meet with me.", "非常感謝你抽空與我見面。"),
    ("I'm so sorry for mixing up the dates.", "真抱歉，我把日期給搞混了。"),
    ("All is forgiven, don't worry about it.", "沒事啦，完全原諒你，別擔心！"),
    ("Thanks again for everything today!", "今天的一切再次向你道謝！")
])

# ==========================================
# 4. 心情感受與抒發 (100)
# ==========================================
add('情感感受與心情', [
    ("I'm so happy and excited right now!", "我現在超開心、超級興奮的！"),
    ("I feel completely exhausted after work today.", "今天下班後我覺得整個人快累癱了。"),
    ("I'm running on four hours of sleep.", "我昨晚只睡了四個小時，快撐不住了。"),
    ("I'm so burned out from this busy week.", "這忙碌的一週真的讓我身心俱疲。"),
    ("I have so much on my plate right now.", "我目前手頭上的事情多到快忙不過來。"),
    ("I'm feeling really stressed out lately.", "我最近壓力真的蠻大的。"),
    ("Take a deep breath and take it easy.", "深呼吸一下，放輕鬆慢慢來。"),
    ("I feel so relieved that the exam is over.", "考完試了我整個人如釋重負！"),
    ("I can finally relax this weekend.", "這週末我終於可以好好放鬆了。"),
    ("I'm super thrilled about our road trip!", "我對我們接下來的公路旅行超級期待！"),
    ("I can't wait for Friday night!", "我迫不及待想迎接週五晚上了！"),
    ("I'm feeling a little under the weather today.", "我今天身體有點不太舒服。"),
    ("I think I'm catching a cold.", "我想我可能是要感冒了。"),
    ("I woke up on the wrong side of the bed today.", "我今天起床心情很差／諸事不順。"),
    ("I'm in such a good mood this morning!", "我今天早上心情特別好！"),
    ("That coffee really made my day.", "那杯咖啡真的點亮了我的一整天。"),
    ("Your kind words made my day, thank you!", "你溫暖的話讓我一整天都心情大好，謝謝！"),
    ("I feel so awkward when I forget names.", "當我忘記別人的名字時，真的超尷尬。"),
    ("I was so embarrassed I wanted to hide.", "我當時尷尬到恨不得找個地洞鑽進去。"),
    ("I'm so proud of what you've achieved!", "我真為你取得的成就感到無比驕傲！"),
    ("You did an amazing job today!", "你今天表現得太出色了！"),
    ("I'm getting really nervous about the speech.", "我對等等要上台演講感到越來越緊張了。"),
    ("I always get butterflies in my stomach before tests.", "考試前我心裡總是會七上八下緊張不已。"),
    ("Don't worry, you're going to do great!", "別擔心，你一定會表現得超棒的！"),
    ("I'm so annoyed by that loud noise outside.", "外面的噪音吵得我真的很心煩。"),
    ("It's driving me crazy!", "這簡直快把我逼瘋了！"),
    ("I'm sick and tired of eating takeout every day.", "我受夠了每天都在吃外食便當。"),
    ("I feel so grateful to have you as a friend.", "能有你這樣的朋友，我真的很感恩。"),
    ("I feel a bit lonely living on my own sometimes.", "有時候一個人住難免會覺得有點孤單。"),
    ("I'm bored out of my mind right now.", "我現在無聊到發慌。"),
    ("Let's go out and do something fun!", "我們出門找點好玩的樂子吧！"),
    ("I was totally shocked when I heard the news.", "聽到那個消息時我徹底震驚了。"),
    ("I couldn't believe my own eyes!", "我簡直不敢相信自己的眼睛！"),
    ("That was such a pleasant surprise!", "那真是個令人又驚又喜的意外！"),
    ("I felt so bad for breaking your favorite mug.", "摔破你最喜歡的馬克杯，我心裡真的很過意不去。"),
    ("I feel much better after talking to you.", "和你聊過之後，我心情好多了。"),
    ("I'm feeling hopeful about this new project.", "我對這個新專案充滿了希望與期待。"),
    ("I'm really disappointed with the final result.", "我對最後的結果感到蠻失望的。"),
    ("Cheer up! Things will get better soon.", "振作起來！事情很快就會好轉的。"),
    ("Hang in there! You're almost at the finish line.", "再堅持一下！你已經快要到達終點了。"),
    ("I'm so jealous that you get to travel to Hawaii!", "你要去夏威夷玩，我真的超羨慕的！"),
    ("I'm feeling so lazy today, I don't want to move.", "我今天整個人好懶散，一步都不想動。"),
    ("I'm so impatient, I want to know the answer now.", "我性子急，我現在就想知道答案。"),
    ("I feel confident that we can win this game.", "我很有信心我們一定能贏下這場比賽。"),
    ("I feel overwhelmed with all these emails.", "看到這麼多待回的郵件，我感到快被淹沒了。"),
    ("Let's tackle them one step at a time.", "我們一步一步慢慢處理就好。"),
    ("I was terrified when the lights went out.", "剛剛突然停電時，我真的嚇壞了。"),
    ("I'm so touched by your sweet message.", "看到你貼心的訊息，我心裡好感動。"),
    ("I can't stop laughing at this funny video.", "看這個搞笑短片，我笑到完全停不下來。"),
    ("That really cracked me up!", "那真的把我逗樂到不行！"),
    ("I feel so relaxed after taking a warm bath.", "泡完熱水澡後，整個人感覺好放鬆。"),
    ("I'm feeling restless, I need to go for a walk.", "我坐立難安，我需要出去走一走。"),
    ("I'm so confused, I don't get this at all.", "我一頭霧水，我完全搞不懂這是什麼意思。"),
    ("I'm glad that we sorted everything out.", "真高興我們把所有事情都釐清解決了。"),
    ("I feel bad that I couldn't make it to your party.", "我很過意不去沒能趕去參加你的派對。"),
    ("Don't feel bad, we'll hang out next time!", "別放在心上，我們下次再聚就好！"),
    ("I'm deeply impressed by your presentation.", "我對你的簡報表現印象非常深刻。"),
    ("I feel uneasy about going home in the dark alone.", "天這麼黑一個人走回家，我心裡有點毛毛的。"),
    ("I'll walk with you so you feel safe.", "我陪你一起走，這樣比較安全。"),
    ("I'm feeling super motivated to work out today.", "我今天充滿幹勁，超想去運動健身。"),
    ("I'm so upset about losing my wallet.", "弄丟了皮夾，我真的難過又懊惱。"),
    ("Did you check under your car seat?", "你有檢查過車子座位底下嗎？"),
    ("I feel so relieved! It was in my backpack all along.", "我鬆了一大口氣！原來一直都在我後背包裡。"),
    ("I'm so sick of this endless traffic jam.", "我真的受夠了這沒完沒了的塞車。"),
    ("Put on some music to help pass the time.", "放點音樂來打發時間吧。"),
    ("I feel nostalgic whenever I hear this old song.", "每次聽到這首老歌，我都湧上一陣懷舊感傷。"),
    ("I feel like celebrating tonight!", "我今天晚上好想好好慶祝一番！"),
    ("Drinks are on me tonight!", "今晚的飲料和酒錢全算我的！"),
    ("I'm frustrated because my computer keeps crashing.", "我的電腦一直當機，真的快把我氣瘋了。"),
    ("Did you remember to back up your files?", "你有記得把檔案存檔備份嗎？"),
    ("I'm so grateful for all your support.", "非常感激你一路以來給予我的支持。"),
    ("I felt helpless when my car broke down.", "車子拋錨在半路上時，我感到無比無助。"),
    ("I'm so glad someone stopped to help you.", "真好，幸好有好心人停下來幫你。"),
    ("I feel energized after drinking my morning coffee.", "喝完早晨的第一杯咖啡後，我精神百倍。"),
    ("I feel like I'm finally getting the hang of this.", "我感覺我終於掌握到這個訣竅了。"),
    ("See? I told you that you could do it!", "你看吧？我就說你一定可以做到的！"),
    ("I'm so drained, I need to sleep for ten hours.", "我能量快耗盡了，我需要狂睡十個小時。"),
    ("Sleep in tomorrow, you deserve the rest.", "明天睡到自然醒吧，你該好好休息了。"),
    ("I'm so thrilled to be a part of this team.", "能成為這個團隊的一份子，我感到非常榮幸與興奮。"),
    ("I was hesitant at first, but now I love it.", "我一開始有點猶豫，但現在我超愛的。"),
    ("I feel a little homesick these days.", "我最近這陣子有點想家。"),
    ("Give your parents a quick call tonight.", "今晚打通電話回家跟爸媽聊聊天吧。"),
    ("I feel silly for worrying so much about nothing.", "為了根本沒發生的事白擔心一場，我覺得自己好傻。"),
    ("We all do that sometimes, don't worry about it.", "我們有時候也都會這樣啦，別在意。"),
    ("I'm feeling so happy and content right now.", "我現在覺得心滿意足、非常幸福。"),
    ("Enjoy this wonderful moment!", "好好享受這個美好的當下吧！"),
    ("I'm heartbroken that my cat is sick.", "我的貓咪生病了，我真的好心疼難過。"),
    ("I hope she gets better really fast.", "希望牠很快就能好起來。"),
    ("I'm looking forward to a cozy night in.", "我很期待今晚在家度過舒適溫馨的夜晚。"),
    ("Get some popcorn and watch a good movie.", "準備點爆米花，看部好電影吧。"),
    ("I'm so eager to hear all about your trip.", "我超想趕快聽你分享旅行的所有趣事！"),
    ("I have so many funny stories to tell you!", "我有好多好笑的故事要講給你聽！"),
    ("I'm terrified of spiders and bugs.", "我超級害怕蜘蛛和各種蟲子。"),
    ("Don't worry, I'll get rid of it for you.", "別怕，我來幫你把牠弄走。"),
    ("I felt so welcomed by everyone here.", "這裡的每個人都好熱情，讓我感到非常受歡迎。"),
    ("We're all super glad that you're here.", "我們大家都非常高興你的到來。"),
    ("I'm losing my mind trying to fix this bug.", "為了解這個程式錯誤，我快要抓狂了。"),
    ("Step away for ten minutes, it usually helps.", "先離開螢幕走動十分鐘，通常很有幫助。"),
    ("I feel refreshed and ready to go again.", "我現在清醒多了，準備好再次出發！"),
    ("That's the spirit! Keep up the good work.", "這就對了！繼續保持這股衝勁！")
])

# ==========================================
# 5. 觀點看法與贊同 (100)
# ==========================================
add('觀點看法與贊同', [
    ("I totally agree with you on that.", "在那一點上我完全同意你的看法。"),
    ("You can say that again!", "你說得太對了！／完全贊同！"),
    ("I couldn't agree more.", "我完全不能同意你更多了／說得真好。"),
    ("That makes a lot of sense.", "那樣說非常有道理。"),
    ("That's a very good point.", "那是個很棒的觀點。"),
    ("You took the words right out of my mouth!", "你剛好把我心裡想說的話說出來了！"),
    ("I feel the exact same way.", "我的感受和你一模一樣。"),
    ("Exactly! That's what I was thinking.", "沒錯！我剛剛心裡想的正是這樣。"),
    ("I see what you mean, but let's consider the cost.", "我懂你的意思，但我們也得考量成本。"),
    ("I see your point, but I have a different opinion.", "我明白你的看法，但我有不同的觀點。"),
    ("To be honest, I'm not so sure about that.", "老實說，我對那件事並不是很確定。"),
    ("I don't think that's a good idea.", "我覺得那個點子可能不太行。"),
    ("I have mixed feelings about this decision.", "對於這個決定，我內心情緒蠻複雜的。"),
    ("If you ask me, we should do it right away.", "如果你問我的意見，我認為我們該立刻去做。"),
    ("From my experience, this method works best.", "依我的經驗，這個方法效果最顯著。"),
    ("As far as I know, they haven't decided yet.", "據我所知，他們目前還沒有做最後決定。"),
    ("In my opinion, we need more time to prepare.", "依我看，我們需要更多的準備時間。"),
    ("What do you think about this proposal?", "你覺得這份提議方案怎麼樣？"),
    ("How do you feel about moving the meeting to Friday?", "把會議改到週五，你覺得如何？"),
    ("Do you have any thoughts on this topic?", "關於這個話題，你有什麼想法嗎？"),
    ("I think it really depends on the situation.", "我認為這很大程度要視情況而定。"),
    ("That depends on how much budget we have.", "那取決於我們手頭上有多少預算。"),
    ("That sounds like a solid plan to me.", "對我來說，這聽起來是個很可靠的計畫。"),
    ("I'm totally on board with this idea.", "我百分之百贊成並支持這個點子。"),
    ("Count me in! That sounds amazing.", "算我一份！聽起來超棒的。"),
    ("I'd rather wait and see what happens.", "我比較想先靜觀其變，看看後續發展。"),
    ("Let's look at it from another angle.", "我們換個角度來看這件事吧。"),
    ("Fair enough, that sounds reasonable.", "說得也是，那樣聽起來蠻合理的。"),
    ("You have a point there.", "你在這一點上說得確實有理。"),
    ("I doubt that will actually work in practice.", "我很懷疑那樣在實際操作上到底行不行得通。"),
    ("Are you sure about that? Have you checked?", "你確定嗎？你有先核實過嗎？"),
    ("I'm positive! I double checked this morning.", "我非常確定！我今天早上剛仔細核對過。"),
    ("I might be wrong, but that's just my guess.", "我也許說錯，但那只是我個人的猜測。"),
    ("Don't get me wrong, I like the concept.", "別誤會我的意思，我其實蠻喜歡這個概念的。"),
    ("Personally, I prefer the blue one over the red one.", "就個人而言，我比較喜歡藍色的那個而不是紅色的。"),
    ("I think we're on the same page now.", "我想我們現在雙方的共識是一致的了。"),
    ("Let's agree to disagree on this one.", "關於這一點，我們就各自保留意見吧。"),
    ("That's totally beside the point.", "那根本完全離題了／不是重點。"),
    ("Let's get straight to the point.", "我們直接切入核心重點吧。"),
    ("What's the bottom line here?", "這件事最根本的底線／結論是什麼？"),
    ("The bottom line is that we need more sales.", "最根本的結論就是我們需要提高銷售額。"),
    ("I don't think it's worth the risk.", "我認為冒這個風險並不值得。"),
    ("It's definitely worth a shot!", "這絕對值得嘗試一下！"),
    ("What do we have to lose?", "反正我們也沒什麼好失去的，怕什麼？"),
    ("Nothing beats home-cooked meals.", "沒有什麼比家常菜更棒的了。"),
    ("I couldn't have said it better myself.", "說得太好了，換作是我也沒法表達得更精闢。"),
    ("That's easier said than done.", "那真是說得比做得容易。"),
    ("I believe communication is the key to success.", "我相信溝通是成功的關鍵所在。"),
    ("Practice makes perfect, in my view.", "依我看，熟能生巧是不變的道理。"),
    ("I see where you're coming from.", "我能理解你為什麼會這麼想／你的出發點。"),
    ("I don't see any problem with that.", "我看不出那樣做會有什麼問題。"),
    ("Sounds good to me! Let's do it.", "我聽起來覺得很可以！就這麼辦吧。"),
    ("I'm leaning towards the second option.", "我個人目前比較傾向於第二個選項。"),
    ("Which option do you think is better?", "你覺得哪一個選項比較好？"),
    ("The first option is cheaper, but the second is faster.", "第一個選項比較便宜，但第二個比較快。"),
    ("I guess you're right about that.", "我想你在那一點上大概是對的。"),
    ("No doubt about it!", "這毫無疑問！"),
    ("Without a doubt, this is the best cafe in town.", "毫無疑問，這是鎮上最棒的咖啡館。"),
    ("I'm not convinced yet. Show me the data.", "我還沒被說服，拿數據給我看吧。"),
    ("That makes no sense at all.", "那樣講根本完全不合邏輯／說不通。"),
    ("Let's give it some more thought before deciding.", "在做決定之前，我們再多深思一下吧。"),
    ("Sleep on it and decide tomorrow.", "先睡一覺，明天再做決定吧。"),
    ("I changed my mind after reading the review.", "看完那篇評論後，我改變主意了。"),
    ("What made you change your mind?", "是什麼讓你改變了心意？"),
    ("To put it simply, we ran out of time.", "簡單來說，就是我們的時間不夠用了。"),
    ("In other words, we need to redo the whole thing.", "換句話說，我們需要把整件事重做一遍。"),
    ("That's one way to look at it.", "這也是看待這件事的一種角度啦。"),
    ("I wouldn't go that far.", "我倒不至於會說得那麼誇張。"),
    ("That's a bit of an exaggeration, isn't it?", "那樣講稍微有點誇大了吧？"),
    ("Honestly, it doesn't matter to me either way.", "老實說，對我來說哪一種都可以、沒差別。"),
    ("Whatever you decide is fine with me.", "不管你做什麼決定，我都沒意見。"),
    ("I trust your judgment on this.", "在這件事上我相信你的判斷。"),
    ("It's your call, what do you want to do?", "由你決定，你想怎麼做？"),
    ("I leave it entirely up to you.", "這件事我全權交給你決定。"),
    ("That's a tough question to answer.", "這真是個很難回答的問題。"),
    ("There's no right or wrong answer here.", "這件事沒有所謂標準的對與錯。"),
    ("I agree with you up to a point.", "在某種程度上我同意你，但無法全盤接受。"),
    ("I'm totally against that idea.", "我個人完全反對那個提議。"),
    ("Why are you so against it?", "你為什麼會這麼強烈反對呢？"),
    ("Because it's way too expensive for our budget.", "因為那遠遠超出了我們的預算上限。"),
    ("That's true, I hadn't thought of that.", "確實如此，我剛剛還真沒想到這點。"),
    ("Thanks for pointing that out!", "謝謝你指出了這一點！"),
    ("I think you hit the nail on the head.", "我覺得你完全說中要害／一針見血。"),
    ("That's exactly my point.", "這正是我想要表達的重點！"),
    ("I knew you would understand.", "我就知道你一定能懂。"),
    ("Great minds think alike!", "英雄所見略同！"),
    ("I have a feeling this will turn out great.", "我有一種預感，這件事最後一定會很棒。"),
    ("Let's hope for the best!", "讓我們抱持最樂觀的期待吧！"),
    ("Better safe than sorry.", "小心駛得萬年船／謹慎總比後悔好。"),
    ("It's always good to have a backup plan.", "隨時準備個備案總是不會錯的。"),
    ("I think we should stick to the original plan.", "我認為我們應該堅持原本的計畫。"),
    ("If it ain't broke, don't fix it.", "如果運作得好好的，就別去瞎折騰改動它。"),
    ("Times have changed, we need new ideas.", "時代變了，我們需要一些新思維與新點子。"),
    ("I'm open to suggestions if you have any.", "如果你有任何建議，我隨時樂意傾聽。"),
    ("Let's brainstorm some new options together.", "我們一起腦力激盪想些新方案吧。"),
    ("Every little bit helps.", "每一點微小的幫助都很有用。"),
    ("Actions speak louder than words.", "坐而言不如起而行／行動勝於空談。"),
    ("I completely understand where you're coming from.", "我完全能體會並理解你的立場。"),
    ("That sounds like a win-win situation.", "那聽起來是個雙贏的局面。"),
    ("Let's go with that plan then!", "那就照那個方案進行吧！")
])

# ==========================================
# 6. 餐廳用餐與外帶 (100)
# ==========================================
add('餐廳用餐與點餐', [
    ("Hi! A table for two, please.", "嗨！兩位，麻煩幫我們安排座位。"),
    ("Do you have a reservation under the name David?", "請問有訂位嗎？登記的名字是 David。"),
    ("We don't have a reservation. Is there a wait?", "我們沒有訂位，請問現在需要候位等多久？"),
    ("How long is the wait for a table of four?", "四個人的位子大概要等多久？"),
    ("Could we get a table by the window?", "我們可以坐靠窗的位子嗎？"),
    ("Can we sit outside on the patio?", "我們可以坐在戶外露天座位區嗎？"),
    ("Could we get the menu, please?", "能麻煩幫我們送上菜單嗎？"),
    ("Do you have an English menu available?", "請問有英文菜單嗎？"),
    ("Can we have a few more minutes to look at the menu?", "可以再給我們幾分鐘看一下菜單嗎？"),
    ("What's the special of the day?", "請問今天的每日主廚特餐是什麼？"),
    ("What do you recommend here?", "你們店裡有什麼推薦的招牌菜嗎？"),
    ("What is your most popular dish?", "你們這裡最受歡迎的人氣餐點是什麼？"),
    ("I'm ready to order now.", "我準備好可以點餐了。"),
    ("I'll have the cheeseburger and fries, please.", "我要一份起司漢堡配薯條，謝謝。"),
    ("I'd like a medium rare steak, please.", "我想要一份五分熟的牛排，謝謝。"),
    ("How would you like your eggs cooked?", "您的蛋想要怎麼料理？（荷包蛋、炒蛋等）"),
    ("Scrambled eggs, please.", "請幫我做炒蛋，謝謝。"),
    ("Can I get an iced Americano with no sugar?", "我可以要一杯無糖冰美式咖啡嗎？"),
    ("I'll have a hot latte with oat milk, please.", "我要一杯熱燕麥奶拿鐵，謝謝。"),
    ("Can you make that decaf, please?", "可以幫我換成低咖啡因的嗎？"),
    ("Is this dish very spicy?", "這道菜會很辣嗎？"),
    ("Can you make it mild / less spicy?", "可以幫我做微辣／少辣一點嗎？"),
    ("Does this pasta contain any dairy or nuts?", "這道義大利麵有含有任何乳製品或堅果嗎？"),
    ("I'm vegetarian. Do you have vegetarian options?", "我是素食者，請問有素食餐點可以選嗎？"),
    ("I'm allergic to seafood, just so you know.", "我對海鮮過敏，先跟您說一聲。"),
    ("Can I get the salad dressing on the side?", "沙拉醬可以幫我另外裝在小碟子裡嗎？"),
    ("Could I get some tap water, please?", "可以給我一杯常溫水／自來開水嗎？"),
    ("Can we have some extra napkins and ice water?", "可以幫我們多拿幾張餐巾紙和冰水嗎？"),
    ("Could you bring us some extra forks and plates?", "能幫我們多拿幾支叉子和小盤子嗎？"),
    ("Excuse me, could we get some ketchup and black pepper?", "不好意思，能給我們一些番茄醬和黑胡椒嗎？"),
    ("For here or to go?", "內用還是外帶？"),
    ("To go, please.", "麻煩外帶，謝謝。"),
    ("For here, please.", "內用，謝謝。"),
    ("Can I get this wrapped up to go?", "可以幫我把這道菜打包外帶嗎？"),
    ("Could I have a to-go box, please?", "可以給我一個外帶打包盒嗎？"),
    ("We'd like to order some dessert now.", "我們現在想加點一些甜點。"),
    ("Do you have cheesecake or chocolate brownies?", "你們有起司蛋糕或巧克力布朗尼嗎？"),
    ("Excuse me, we haven't received our drinks yet.", "不好意思，我們的飲料好像還沒有送來。"),
    ("Could you check on our order, please?", "能麻煩幫我們確認一下餐點進度嗎？"),
    ("Sorry to bother, but I ordered the soup, not the salad.", "不好意思，我點的是湯品而不是沙拉。"),
    ("This isn't what I ordered, could you check?", "這道好像不是我點的，可以幫忙核對一下嗎？"),
    ("Everything tastes absolutely delicious!", "每道菜吃起來都超級美味！"),
    ("This steak is cooked to perfection.", "這塊牛排煎得恰到好處，太完美了。"),
    ("Could we get the check / bill, please?", "買單，麻煩幫我們結帳。"),
    ("Can we pay separately?", "我們可以分開結帳嗎？"),
    ("Let's split the bill evenly.", "我們大家平分這頓餐費吧。"),
    ("Do you accept credit cards or mobile pay?", "請問你們收信用卡或手機行動支付嗎？"),
    ("Is service charge included in the total?", "請問總金額裡面有包含服務費了嗎？"),
    ("Keep the change, thank you!", "不用找零錢了，謝謝！"),
    ("Thank you for the delicious meal!", "謝謝款待，今天這頓餐點非常美味！"),
    ("Can I get a refill on my iced tea?", "我的冰紅茶可以續杯嗎？"),
    ("Are refills free for soft drinks?", "請問汽水飲料是可以免費續杯的嗎？"),
    ("I'll have what she's having.", "我也要一份跟她一樣的餐點。"),
    ("What dressing would you like with your salad?", "您的沙拉想要搭配什麼醬料？"),
    ("Ranch dressing, please.", "請給我田園沙拉醬，謝謝。"),
    ("Can I substitute fries for a side salad?", "我可以把配菜的薯條換成小沙拉嗎？"),
    ("Is the soup of the day mushroom soup?", "今天的今日例湯是蘑菇濃湯嗎？"),
    ("I'd like a glass of house red wine, please.", "我要一杯店裡的精選紅酒，謝謝。"),
    ("Could you bring us some hot water with lemon?", "能幫我們送上一杯熱檸檬水嗎？"),
    ("We're celebrating my friend's birthday today.", "我們今天特地來幫朋友慶生。"),
    ("Do you have any candles for the cake?", "請問你們有可以插在蛋糕上的蠟燭嗎？"),
    ("Could you take a quick photo for us, please?", "能麻煩幫我們大家拍張合照嗎？"),
    ("Just press this big button right here.", "只要按這裡這個大按鈕就可以了。"),
    ("One more, just in case. Smile!", "再拍一張備用，大家笑一個！"),
    ("Thank you so much for taking the photo!", "太感謝你幫我們拍照了！"),
    ("This soup is a little too salty for my taste.", "這碗湯對我個人口味來說稍微有點太鹹。"),
    ("Could you heat this up in the microwave for me?", "可以麻煩幫我用微波爐稍微加熱一下嗎？"),
    ("I'm so full, I can't eat another bite.", "我吃得好飽，真的連一口都吃不下了。"),
    ("There is always room for dessert!", "吃甜點永遠有第二個胃！"),
    ("Let's order one slice of cake and share it.", "我們點一塊蛋糕一起分著吃吧。"),
    ("Do you have any dairy-free ice cream?", "你們有不含乳製品的無奶冰淇淋嗎？"),
    ("What flavors of ice cream do you have?", "你們有哪些口味的冰淇淋？"),
    ("We have vanilla, chocolate, and strawberry.", "我們有香草、巧克力和草莓口味。"),
    ("I'll take one scoop of chocolate in a cone.", "我要一球巧克力甜筒冰淇淋。"),
    ("Can I get a cup of coffee to go?", "我可以帶一杯外帶熱咖啡嗎？"),
    ("Would you like room for milk?", "需要幫您的咖啡預留加牛奶的空間嗎？"),
    ("Yes, just a little bit of room, please.", "好的，請留一點點空間就可以了。"),
    ("How sweet do you want your bubble tea?", "你的珍珠奶茶甜度要幾分甜？"),
    ("Half sugar and less ice, please.", "半糖去冰／微冰，謝謝。"),
    ("Can I add extra boba pearls?", "我可以額外加珍珠嗎？"),
    ("Where can I grab a straw and some napkins?", "吸管和餐巾紙要在哪裡拿？"),
    ("They're right over at the counter on the left.", "就在左手邊的自助調味吧台上。"),
    ("Can we have the food served as it gets ready?", "餐點做好了就麻煩直接陸續幫我們上菜。"),
    ("Is the fish freshly caught today?", "這條魚是今天產地直送的新鮮漁獲嗎？"),
    ("Yes, it's very fresh and tender.", "是的，非常新鮮而且肉質鮮嫩。"),
    ("I'll try that then!", "那我就點這道試試看！"),
    ("Could you bring the kids' meal first, please?", "可以麻煩先送兒童餐上來嗎？"),
    ("Do you provide baby high chairs?", "請問你們店裡有提供兒童專用高腳椅嗎？"),
    ("Yes, I'll bring one right over for you.", "有的，我馬上為您搬一張過來。"),
    ("Could I get a glass of sparkling water with lime?", "可以給我一杯加檸檬片的氣泡水嗎？"),
    ("Is there a minimum charge per person?", "請問店裡有每人低消的限制嗎？"),
    ("Yes, it's one drink or meal per person.", "有的，每人低消是一份餐點或一杯飲品。"),
    ("We're ready for the bill whenever you have time.", "你有空時麻煩幫我們結帳，我們準備好了。"),
    ("Can I pay with contactless on my phone?", "我可以用手機感應付款嗎？"),
    ("Sure, just tap your phone right here.", "當然可以，直接把手機靠在這裡感應即可。"),
    ("Here's your receipt. Have a wonderful night!", "這是您的發票收據，祝您度過愉快的一晚！"),
    ("Thank you, food was great! We'll be back.", "謝謝，餐點超棒的！我們一定會再來。"),
    ("Let's leave a tip for our server.", "我們留點小費給服務生吧。"),
    ("That was hands down the best meal I've had all week.", "這絕對是我這整週吃過最過癮的一餐。"),
    ("I'm definitely recommending this place to my friends.", "我一定要把這家餐廳推薦給我所有的朋友。")
])

# ==========================================
# 7. 購物消費與超商 (100)
# ==========================================
add('購物消費與結帳', [
    ("Excuse me, how much is this shirt?", "不好意思，請問這件襯衫多少錢？"),
    ("Do you have this jacket in a medium size?", "請問這件夾克有 M 號的尺寸嗎？"),
    ("Can I try this on?", "我可以試穿這個嗎？"),
    ("Where are the fitting rooms / dressing rooms?", "請問試衣間在哪裡？"),
    ("They're right around the corner on the left.", "就在左邊轉角處那裡。"),
    ("How does it fit on you?", "穿起來合身嗎？尺寸如何？"),
    ("It's a little too tight around the shoulders.", "肩膀部位稍微有點太緊了。"),
    ("It fits perfectly! I'll take it.", "非常合身！這件我要了。"),
    ("Do you have this in other colors?", "這款還有其他顏色可以選嗎？"),
    ("We have it in black, navy, and beige.", "我們還有黑色、深藍色和米色。"),
    ("Can I see the black one, please?", "可以讓我看一下黑色的那件嗎？"),
    ("Is this item currently on sale?", "這件商品目前有在打折特價嗎？"),
    ("Buy one, get one fifty percent off today.", "今天第二件享半價優惠喔。"),
    ("That's a really great deal!", "那真的非常划算耶！"),
    ("I'm just browsing / looking around, thanks!", "我只是隨便逛逛看看，謝謝！"),
    ("Let me know if you need help finding anything.", "如果您需要找任何商品，隨時跟我說一聲。"),
    ("Where can I find phone chargers and cables?", "請問手機充電器和傳輸線在哪一區？"),
    ("They're in aisle three, next to electronics.", "在第三走道，電子配件區旁邊。"),
    ("Do you have this in stock in the back?", "庫存倉庫裡還有這件的現貨嗎？"),
    ("Let me check the system for you real quick.", "我馬上在電腦系統裡幫您查詢一下。"),
    ("Sorry, it looks like we're all sold out of that size.", "抱歉，看來那個尺寸目前全部售完了。"),
    ("When do you expect the next restock?", "請問預計什麼時候會再補貨呢？"),
    ("It should be back in stock by next Tuesday.", "預計下週二之前會重新進貨。"),
    ("Can you put this on hold for me until tonight?", "可以幫我把這件保留到今天晚上嗎？"),
    ("Sure, what is your name and phone number?", "好的，請問您的大名和聯絡電話是？"),
    ("Are you ready to check out?", "請問準備好結帳了嗎？"),
    ("Yes, just these two items, please.", "是的，就這兩樣東西，麻煩了。"),
    ("Do you accept Apple Pay or credit cards?", "請問收 Apple Pay 或信用卡嗎？"),
    ("We accept all major credit cards and mobile pay.", "我們接受各大信用卡及手機行動支付。"),
    ("Can I pay in cash?", "我可以用現金結帳嗎？"),
    ("Your total comes to forty-five dollars.", "您的結帳總金額是 45 元。"),
    ("Here's fifty dollars.", "這裡給您 50 元。"),
    ("And here is five dollars change and your receipt.", "找您 5 元零錢，這是您的發票收據。"),
    ("Would you like a paper bag or a plastic bag?", "需要紙袋還是塑膠袋嗎？"),
    ("No bag needed, I brought my own tote.", "不需要袋子，我自己有帶環保提袋。"),
    ("Can I get a small shopping bag, please?", "可以給我一個小購物袋嗎？"),
    ("Do you have a membership with us?", "請問有我們的會員嗎？／報電話號碼嗎？"),
    ("Yes, here is my phone number / barcode.", "有的，這是我的會員電話號碼／條碼。"),
    ("Can I redeem my reward points on this purchase?", "我這次消費可以折抵會員積點嗎？"),
    ("You have five dollars in points available to use.", "您目前有 5 元價值的點數可以折抵使用。"),
    ("Great, please apply that to the total!", "太好了，請幫我直接折抵總金額！"),
    ("Can I get a tax-free / duty-free refund here?", "請問在這裡消費可以辦理退稅嗎？"),
    ("Yes, please show me your passport.", "可以的，請出示您的外國護照。"),
    ("Can I return this if it doesn't fit?", "如果尺寸不合，我可以拿來退貨嗎？"),
    ("Yes, you have thirty days with the original receipt.", "可以的，憑原始發票明細可在 30 天內辦理。"),
    ("Make sure to keep the tags attached.", "請務必確保商品標籤吊牌完整未拆。"),
    ("I'd like to exchange this for a larger size.", "我想把這件換大一號的尺寸。"),
    ("I'd like to return this shirt and get a refund.", "我想把這件衣服退掉並辦理退款。"),
    ("Is there anything wrong with the item?", "請問商品有任何瑕疵或問題嗎？"),
    ("No, it's just the wrong color for my friend.", "沒有，只是顏色不太適合我朋友。"),
    ("No problem, the refund is back on your card.", "沒問題，退款已直接刷退回您的卡片。"),
    ("Where is the checkout counter / cashier?", "請問結帳收銀台在哪裡？"),
    ("The line starts right over there.", "排隊動線是從那邊開始喔。"),
    ("Next customer in line, please!", "下一位排隊的顧客請上前！"),
    ("Do you sell umbrellas here?", "請問你們這裡有賣雨傘嗎？"),
    ("Yes, they're by the entrance door.", "有的，就放在大門口入口處旁邊。"),
    ("How much does a bottle of water cost?", "一瓶礦泉水多少錢？"),
    ("Can you heat up this lunchbox for me, please?", "可以麻煩幫我微波加熱這個便當嗎？"),
    ("Sure, give me about one minute.", "好的，請稍等大約一分鐘。"),
    ("Careful, it's very hot!", "請小心拿，便當非常燙喔！"),
    ("Do you need a pair of chopsticks and a spoon?", "需要附免洗筷子和湯匙給您嗎？"),
    ("Just a fork is fine, thanks!", "只要一支叉子就可以了，謝謝！"),
    ("Can I get a pack of mints at the register?", "我可以順便拿一包收銀台旁邊的薄荷糖嗎？"),
    ("Is this cart free to use?", "這台手推車是可以免費使用的嗎？"),
    ("Yes, just push it out of the rack.", "是的，直接從推車架拉出來用即可。"),
    ("Where can I weigh these fresh apples?", "請問這些新鮮蘋果要在哪裡過磅稱重？"),
    ("The scale is in the center of the produce section.", "電子秤就在生鮮蔬果區的正中央。"),
    ("Is this organic produce?", "這些是產地認證的有機蔬果嗎？"),
    ("Yes, all items on this table are 100% organic.", "是的，這張陳列桌上的蔬果全是百分之百有機的。"),
    ("These avocados are ripe and ready to eat.", "這些酪梨都已經熟成，買回去就可以直接吃了。"),
    ("Do you have fresh milk with a later expiration date?", "有保存期限更久一點的新鮮牛奶嗎？"),
    ("Check the cartons at the very back of the shelf.", "您可以看貨架最裡面的那幾盒。"),
    ("Can I get a discount if I buy in bulk?", "如果我大量批發購買，可以算便宜點打折嗎？"),
    ("If you buy three, you get 20 percent off.", "買滿三件以上可以打八折優惠。"),
    ("Where can I find shampoo and body wash?", "洗髮精和沐浴乳要在哪一排貨架找？"),
    ("Aisle five, on the top shelf.", "在第五走道的最上層貨架。"),
    ("Do you sell travel-sized bottles?", "你們有賣旅行用的小隨身瓶嗎？"),
    ("Yes, right in the travel accessories section.", "有的，就在旅行必備配件專區。"),
    ("Can I get a gift receipt for this item?", "可以幫我開一張禮品收據（不顯示價格）嗎？"),
    ("Do you offer gift wrapping service here?", "請問你們這裡有提供禮物包裝服務嗎？"),
    ("Yes, we have free gift boxes at customer service.", "有的，顧客服務中心有提供免費的禮物盒。"),
    ("I think this item scanned with the wrong price.", "我想這件商品的條碼刷出來價格好像算錯了。"),
    ("Let me double check the shelf tag for you.", "我馬上為您核對一下貨架上的標價標籤。"),
    ("You're right, let me adjust the price for you.", "您說得沒錯，我立刻在收銀機為您修正價格。"),
    ("Thanks for catching that!", "謝謝你發現了這個錯誤！"),
    ("Please enter your PIN on the terminal.", "請在刷卡機螢幕上輸入您的密碼。"),
    ("Please tap or insert your chip card.", "請感應或插入您的晶片信用卡。"),
    ("Your payment has been approved.", "您的付款已授權成功。"),
    ("Would you like your receipt printed or emailed?", "發票要列印紙本還是寄到電子信箱？"),
    ("Printed is fine, thank you.", "印紙本的給我就好，謝謝。"),
    ("Have a great rest of your day shopping!", "祝您今天購物愉快！"),
    ("Thank you, you too!", "謝謝，你也是！"),
    ("Excuse me, what time do you close tonight?", "不好意思，請問你們今晚幾點打烊關門？"),
    ("We're open until 10 PM every day.", "我們每天都營業到晚上 10 點整。"),
    ("Are you open on Sundays and holidays?", "你們週日和國定假日有開門營業嗎？"),
    ("Yes, we're open seven days a week.", "有的，我們全年無休、天天營業。"),
    ("Where is the customer service desk located?", "請問顧客服務諮詢台在哪個位置？"),
    ("It's right near the main entrance on the first floor.", "就在一樓正門大廳入口處旁邊。"),
    ("Thanks so much for your kind help today!", "今天真的很感謝你熱心親切的幫忙！"),
    ("You're very welcome! Have a great day.", "非常不客氣！祝您有個美好的一天。")
])

# ==========================================
# 8. 出門交通與問路 (100)
# ==========================================
add('旅遊觀光與問路', [
    ("Excuse me, could you tell me how to get to Central Station?", "不好意思，請問中央火車站應該要怎麼走？"),
    ("Go straight for two blocks, then turn left.", "直走過兩個街區，然後在路口左轉。"),
    ("Is it within walking distance from here?", "從這裡用走路走得過去嗎？距離近嗎？"),
    ("Yes, it's only about a five-minute walk.", "可以的，走路大概只要五分鐘左右。"),
    ("No, it's quite far. You'd better take the subway.", "不行喔，距離蠻遠的，你最好搭地鐵／捷運。"),
    ("Which subway line should I take to downtown?", "去市中心我應該要搭乘哪一條地鐵線？"),
    ("Take the Blue Line and get off at City Hall.", "搭乘藍線，然後在市政府站下車。"),
    ("Where is the nearest subway entrance?", "請問最近的地鐵站出入口在哪裡？"),
    ("It's just across the street, right next to the bank.", "就在馬路正對面，銀行隔壁就是了。"),
    ("Where can I buy a subway transit pass?", "我在哪裡可以買到地鐵悠遊卡／交通乘車券？"),
    ("You can get one at the ticket vending machine over there.", "您可以在那邊的自動售票機購買。"),
    ("Which bus goes to the international airport?", "請問哪一路公車可以直達國際機場？"),
    ("Bus number 300 goes directly to Terminal 1.", "300 號公車可以直接開到第一航廈。"),
    ("How often does this bus come?", "這班公車大概多久會來一班？"),
    ("It runs every fifteen minutes.", "每十五分鐘就有一班車。"),
    ("Does this bus stop at the National Museum?", "這班公車有停靠國家博物館站嗎？"),
    ("Yes, it's the fourth stop from here.", "有的，從這裡算起第四站就是了。"),
    ("How many stops is it to Times Square?", "到時代廣場總共還要坐幾站？"),
    ("It's three more stops. I'll let you know when to get off.", "還要三站，到了我會提醒你下車。"),
    ("Excuse me, is anyone sitting here?", "不好意思，請問這裡有人坐嗎？"),
    ("Can I get past you, please? This is my stop.", "不好意思借過一下可以嗎？我這站要下車。"),
    ("Where can I catch a taxi / cab around here?", "請問這附近哪裡可以叫到計程車？"),
    ("There's a taxi stand right in front of the hotel.", "飯店正大門口就有一個專用計程車排班處。"),
    ("Could you call a cab for me, please?", "能麻煩幫我叫一輛計程車嗎？"),
    ("I'm going to 120 Main Street, please.", "麻煩請載我到主街 120 號，謝謝。"),
    ("How long will it take to get there in this traffic?", "以現在的交通路況，開到那裡大概要多久？"),
    ("It should take about twenty minutes.", "大概需要二十分鐘左右。"),
    ("Please turn on the meter.", "請幫我按表跳錶計費，謝謝。"),
    ("Can you drop me off right at the corner?", "可以在那個路口轉角處讓我下車嗎？"),
    ("Pull over right by that convenience store, please.", "麻煩請在前面那家便利商店旁邊靠邊停。"),
    ("How much is the fare?", "車資總共是多少錢？"),
    ("Keep the change, thanks for the smooth ride!", "不用找零錢了，謝謝你開得這麼穩！"),
    ("Can I pay the taxi fare with a credit card?", "計程車車資可以刷信用卡付費嗎？"),
    ("Where can I rent a public bicycle?", "請問哪裡可以租借公共自行車？"),
    ("There's a bike rental station right behind you.", "你正後方就有一個自行車租借站點。"),
    ("How do I unlock the bike with the app?", "我要怎麼用手機 App 來解鎖這輛單車？"),
    ("Just scan the QR code on the handlebar.", "直接用手機掃描車把手上的 QR Code 即可。"),
    ("Is there a bike lane along this river?", "沿著這條河岸邊有自行車專用道嗎？"),
    ("Yes, it's a beautiful and safe path.", "有的，是一條風景優美又安全的車道。"),
    ("Excuse me, I'm completely lost. Can you help me?", "不好意思，我完全迷路了，能幫幫我嗎？"),
    ("Where are you trying to go?", "您想要去哪裡呢？"),
    ("I'm looking for the local art museum.", "我正在尋找當地的市立美術館。"),
    ("You're heading in the opposite direction.", "你現在走的方向完全相反了喔。"),
    ("Turn around and walk back three blocks.", "往回轉走過三個街區。"),
    ("You'll see it on your right hand side.", "你就會在右手邊看到它了。"),
    ("You can't miss it!", "目標非常明顯，你絕對不會錯過的！"),
    ("Is it safe to walk around here at night?", "晚上在這附近一個人走路散步安全嗎？"),
    ("Yes, this neighborhood is very lively and safe.", "很安全，這個街區晚上很熱鬧而且治安很好。"),
    ("Where is the nearest public restroom?", "請問最近的公共廁所在哪裡？"),
    ("There's a clean restroom inside the bookstore.", "那家書店裡面就有乾淨的洗手間。"),
    ("Where is the nearest gas station?", "請問最近的加油站要往哪裡開？"),
    ("Drive straight down this road for two miles.", "沿著這條路直開兩英里就到了。"),
    ("Do you know where the tourist info center is?", "請問你知道旅客服務中心在哪裡嗎？"),
    ("Can I get a free city map here?", "我可以在這裡索取一份免費的市區地圖嗎？"),
    ("What are the top must-visit attractions in this city?", "這座城市排名前幾名的必訪景點有哪些？"),
    ("You should definitely visit the historical old town.", "你絕對一定要去歷史悠久的舊城老街逛逛。"),
    ("How much is the admission ticket for adults?", "成人全票一張門票要多少錢？"),
    ("Are there any student or senior discounts?", "請問有學生優惠票或長者敬老優惠嗎？"),
    ("Do I need to book tickets online in advance?", "我需要提前在網路上預約購票嗎？"),
    ("Yes, tickets sell out very quickly on weekends.", "建議要，因為週末現場門票很快就會被搶光。"),
    ("Is taking photos allowed inside the gallery?", "展覽館裡面是可以拍照攝影的嗎？"),
    ("No flash photography, please.", "請勿使用閃光燈拍照。"),
    ("What time does the last tour bus leave?", "最後一班觀光導覽巴士是幾點發車？"),
    ("The last bus departs at 6 PM sharp.", "末班車在下午 6 點整準時發車。"),
    ("Where can I find lockers to store my luggage?", "請問在哪裡可以找到置物櫃寄放行李？"),
    ("There are coin-operated lockers on basement level one.", "地下一樓有投幣式的大型行李寄物櫃。"),
    ("How much does it cost per hour for parking?", "請問這裡停車一小時收費多少錢？"),
    ("Is there an elevator or escalator nearby?", "請問這附近有電梯或電扶梯嗎？"),
    ("Take the elevator over there to the top floor.", "搭那邊的電梯可以直接抵達頂樓。"),
    ("Traffic is so congested during rush hour.", "尖峰上班時間這條路的交通真是有夠塞。"),
    ("Let's take the subway instead of driving.", "我們別開車了，改搭捷運／地鐵吧。"),
    ("Is this road a one-way street?", "這條馬路是單行道嗎？"),
    ("Yes, watch out for the traffic signs.", "是的，請多留意路邊的交通指示牌。"),
    ("Where can I catch the shuttle bus to the hotel?", "我在哪裡可以搭乘前往飯店的接駁巴士？"),
    ("The shuttle stops at platform B outside exit 3.", "接駁車停靠在 3 號出口外的 B 號月台。"),
    ("How long is the ferry ride to the island?", "搭渡輪坐船到那座島嶼需要多久時間？"),
    ("It takes about thirty minutes on the ferry.", "搭渡輪大約需要三十分鐘的時間。"),
    ("Can we bring bicycles on the ferry?", "我們可以把自行車牽上渡輪一起搭乘嗎？"),
    ("Yes, there's a dedicated area for bikes.", "可以的，船上有自行車專用停放區。"),
    ("Could you point me towards the main shopping street?", "能麻煩幫我指一下主要購物街的方向嗎？"),
    ("Follow this pedestrian street all the way down.", "沿著這條行人徒步區一直往前走到底就是了。"),
    ("Are there any good local restaurants around here?", "這附近有什麼道地好吃的在地小吃餐廳嗎？"),
    ("Try the noodle shop behind the post office.", "去試試郵局後面那家麵館，非常有名。"),
    ("Thanks for the directions, you've been so helpful!", "太感謝你的指路了，真的幫了我大忙！"),
    ("Have a wonderful time exploring our city!", "祝你在我們城市探索遊玩得開心！"),
    ("Which platform does the express train leave from?", "請問特快直達列車是在第幾月台發車？"),
    ("Platform four, on the left side.", "在左側的第四月台。"),
    ("Does this train have free onboard Wi-Fi?", "這列火車上有提供免費的車載 Wi-Fi 嗎？"),
    ("Yes, just connect to the guest network.", "有的，直接連線至訪客網路即可。"),
    ("Where is the dining car on this train?", "請問這列火車的餐車車廂在哪一節？"),
    ("It's car number five, in the middle of the train.", "在第五節車廂，就在整列車的中間位置。"),
    ("Can I change my ticket to an earlier departure?", "我可以把車票改簽到更早出發的班次嗎？"),
    ("Yes, please take your ticket to the service counter.", "可以的，請帶著您的車票至票務櫃檯辦理。"),
    ("Mind the gap between the train and the platform.", "列車進站時請注意月台與車廂間的空隙。"),
    ("We have arrived at our destination.", "我們已經順利抵達目的地了。"),
    ("Double check your seats to make sure you didn't leave anything.", "下車前請仔細檢查座位，確認沒有遺漏個人隨身物品。"),
    ("Have a safe onward journey!", "祝您接下來的旅途一路順風平安！"),
    ("Where is the taxi drop-off area?", "請問計程車下客專用區在哪裡？"),
    ("It's right by the terminal departure doors.", "就在出境航廈大門口旁邊。"),
    ("Thanks for the ride, have a great day!", "謝謝你載我一程，祝你今天順心！")
])

# ==========================================
# 9. 旅遊住宿與機場 (100)
# ==========================================
add('住宿搭機與機場', [
    ("Hi! I'd like to check in, please.", "您好！我想辦理入住手續／登機手續。"),
    ("I have a hotel reservation under the name Michael.", "我有預訂房間，登記的名字是 Michael。"),
    ("Here is my passport and booking confirmation.", "這是我的護照與訂房／訂位確認單。"),
    ("What time is check-in and check-out?", "請問入住和退房的時間分別是幾點？"),
    ("Check-in is at 3 PM, and check-out is at 11 AM.", "入住時間是下午 3 點，退房時間是上午 11 點。"),
    ("Is it possible to request an early check-in?", "請問有可能申請提前辦理入住嗎？"),
    ("Can I request a quiet room facing away from the street?", "我可以要求安排一間遠離馬路、安靜一點的客房嗎？"),
    ("Can I get a late check-out tomorrow morning?", "明天早上我可以申請延後退房嗎？"),
    ("Can we store our luggage here until our room is ready?", "在房間準備好前，我們可以先寄放行李嗎？"),
    ("Sure, we'll give you a luggage claim tag.", "當然可以，我們會給您一張行李提領牌。"),
    ("Is breakfast included in our room rate?", "請問我們的房費有包含每日早餐嗎？"),
    ("Where and when is breakfast served?", "請問早餐是在哪裡用餐？供應時間是幾點？"),
    ("Breakfast is served on the second floor from 7 to 10 AM.", "早餐在二樓餐廳供應，時間是早上 7 點到 10 點。"),
    ("What is the Wi-Fi password for the guest rooms?", "請問客房內的 Wi-Fi 無線上網密碼是什麼？"),
    ("It's your room number and your last name.", "帳號密碼是您的房號加上您的姓氏。"),
    ("Could we get an extra blanket and two pillows, please?", "可以幫我們多送一條毯子和兩顆枕頭過來嗎？"),
    ("The air conditioner in our room isn't working.", "我們房間裡的冷氣機好像故障沒有運轉。"),
    ("I'll send a technician up to check it right away.", "我馬上派工程維修人員上去為您檢查。"),
    ("Could you send someone up with fresh towels, please?", "能派人送幾條乾淨的新毛巾上來嗎？"),
    ("There's no hot water in the shower.", "淋浴間的水龍頭完全沒有熱水出來。"),
    ("We're on the tenth floor, room 1008.", "我們住在十樓，房號是 1008。"),
    ("Is there a gym or swimming pool in the hotel?", "請問飯店裡面有健身房或游泳池嗎？"),
    ("Yes, the fitness center is on the third floor.", "有的，健身中心位於三樓。"),
    ("What are the opening hours for the pool?", "請問游泳池的開放時間是幾點到幾點？"),
    ("It's open from 6 AM until 10 PM daily.", "每天從早上 6 點開放至晚上 10 點。"),
    ("Could you arrange a wake-up call for 6:30 AM tomorrow?", "能幫我設定明天早上 6 點半的電話叫醒服務嗎？"),
    ("We're checking out now. Everything was great.", "我們現在要辦理退房結帳了，一切都很棒。"),
    ("Here are our room key cards, thank you.", "這是我們的房間房卡，非常感謝。"),
    ("Can you call a taxi to the airport for us?", "能幫我們叫一輛前往機場的計程車嗎？"),
    ("I'd like to check in for my flight to Tokyo.", "我想辦理搭乘前往東京航班的登機手續。"),
    ("Window seat or aisle seat, which do you prefer?", "靠窗座位還是走道座位，您比較偏好哪一種？"),
    ("A window seat near the front, if available.", "如果有位子的話，希望能選靠前面的靠窗座位。"),
    ("Can my travel companion and I sit together?", "我和同行旅伴的座位可以被安排坐在一起嗎？"),
    ("Do you have any bags to check in today?", "請問您今天有任何需要託運的大件行李嗎？"),
    ("Just this one suitcase, and one carry-on bag.", "就這一件託運行李箱，還有一件隨身手提行李。"),
    ("Please place your luggage on the scale.", "請將您的行李箱平放在電子磅秤上。"),
    ("Your suitcase is slightly overweight.", "您的行李箱稍微有點超重了喔。"),
    ("Can I take some heavy items out and put them in my carry-on?", "我可以把一些重的物品拿出來放進隨身包裡嗎？"),
    ("Yes, go right ahead and repack over there.", "可以的，您可以到旁邊去重新整理打包。"),
    ("Do you have any liquids or electronics in your checked bag?", "您的託運行李裡面有放置任何液體或電子產品嗎？"),
    ("No, all laptops and power banks are in my backpack.", "沒有，所有筆記型電腦和行動電源都在我的後背包裡。"),
    ("Here is your boarding pass and luggage tags.", "這是您的登機證和行李託運收據條。"),
    ("Your flight departs from Gate 24 at 10:15.", "您的班機將於 10 點 15 分在 24 號登機門起飛。"),
    ("Boarding starts forty minutes prior to departure.", "飛機將在起飛前四十分鐘開始登機。"),
    ("Where is security checkpoint and passport control?", "請問安全檢查走道和護照查驗處在哪裡？"),
    ("Follow the signs straight ahead on the right.", "順著正前方右側的指示指標走就到了。"),
    ("Please take off your shoes, belt, and jacket.", "過安檢時請脫下您的鞋子、皮帶與厚外套。"),
    ("Take out your laptop and place it in a separate bin.", "請將筆記型電腦拿出來，單獨放置在專用置物籃中。"),
    ("Empty all your pockets before stepping through the scanner.", "走過安檢門金屬探測器前，請清空身上所有口袋。"),
    ("Where is the duty-free shopping area?", "請問免稅商店購物專區在哪個區域？"),
    ("It's right past the security check area.", "一通過安檢區就可以看到整排免稅店了。"),
    ("Can I buy duty-free perfume and cosmetics here?", "我在這裡可以購買免稅香水和化妝保養品嗎？"),
    ("Where is the airline lounge for business class?", "請問商務艙專屬貴賓室在哪個位置？"),
    ("It's on the upper mezzanine near Gate 15.", "在靠近 15 號登機門上方的夾層樓。"),
    ("Is our flight on time, or is it delayed?", "請問我們的航班有準時嗎？還是有延誤？"),
    ("The flight is delayed by forty-five minutes due to weather.", "因為氣候因素，航班預計將延誤四十五分鐘。"),
    ("Has the boarding gate been changed for flight 205?", "請問 205 號航班的登機門有變更嗎？"),
    ("Yes, it was moved from Gate 12 to Gate 18.", "是的，已經從 12 號門改移至 18 號登機門。"),
    ("Now boarding group one and passengers with small children.", "現在開始邀請第一區乘客以及攜帶幼童的家庭登機。"),
    ("Please have your passport and boarding pass in hand.", "登機時請將您的護照和登機證提前拿在手上。"),
    ("Excuse me, where can I put my small backpack?", "不好意思，請問我的小後背包可以放在哪裡？"),
    ("Under the seat in front of you, please.", "請直接放在您正前方的座椅下方即可。"),
    ("Could you help me put my bag in the overhead bin?", "能請您幫忙把我的手提行李放進頭頂置物櫃嗎？"),
    ("Please fasten your seatbelt and return your seat to the upright position.", "起飛前請繫好安全帶，並將椅背豎直。"),
    ("Can I get a blanket and a pair of headphones, please?", "可以給我一條小毛毯和一副耳機嗎？"),
    ("Chicken or pasta for your dinner tonight?", "您今晚的主餐想選雞肉飯還是義大利麵？"),
    ("Chicken with rice, please. And a cup of hot green tea.", "我要雞肉飯，謝謝。並請給我一杯熱綠茶。"),
    ("Could I get a glass of apple juice, please?", "可以給我一杯蘋果汁嗎？"),
    ("Excuse me, could I get past to use the lavatory?", "不好意思借過一下，我想去使用洗手間。"),
    ("We will be landing in approximately twenty minutes.", "我們預計將在大約二十分鐘後降落。"),
    ("Welcome to Los Angeles! Local time is 8 PM.", "歡迎抵達洛杉磯！當地現在時間是晚上 8 點整。"),
    ("Where is the immigration line for foreign visitors?", "請問外國旅客入境查驗隊伍是在哪一邊排隊？"),
    ("What is the purpose of your visit?", "請問您這次入境旅行的目的是什麼？"),
    ("I'm here for tourism and sightseeing with my family.", "我和家人是來這裡觀光旅遊度假的。"),
    ("How long do you intend to stay in the country?", "您預計要在這個國家停留多長的時間？"),
    ("I'll be staying here for ten days.", "我預計總共會停留十天的時間。"),
    ("Where will you be staying during your trip?", "這趟旅程中您都將住在哪些地方？"),
    ("At the Grand Hotel downtown. Here is my booking.", "住在市中心的大飯店，這是我的訂房憑證。"),
    ("Enjoy your stay and have a wonderful trip!", "祝您居留愉快，旅途平安順心！"),
    ("Where is baggage claim carousel number four?", "請問第四號行李提領轉盤要在哪裡找？"),
    ("It's straight down the escalators on level one.", "順著手扶梯直接搭到一樓就是了。"),
    ("I've been waiting for forty minutes, but my suitcase hasn't arrived.", "我已經等了四十分鐘，但我的行李箱一直沒出來。"),
    ("Where is the lost and found / baggage service desk?", "請問遺失物中心／行李服務諮詢處在哪裡？"),
    ("My luggage seems to be lost or delayed.", "我的行李好像遺失或是被延誤轉運了。"),
    ("Please fill out this property irregularity report.", "請協助填寫這份行李事故申報單。"),
    ("What color and brand is your missing suitcase?", "請問您遺失的行李箱是什麼顏色和廠牌？"),
    ("It's a large black Samsonite hard-shell suitcase.", "是一個黑色大型的新秀麗硬殼行李箱。"),
    ("We will deliver it directly to your hotel once it arrives.", "一旦行李運抵，我們會第一時間直接派送至您的飯店。"),
    ("Thank you so much for your assistance.", "非常感謝您耐心親切的協助。"),
    ("Where is the currency exchange counter?", "請問外幣兌換櫃檯在哪個區域？"),
    ("Where can I buy a local prepaid tourist SIM card / eSIM?", "我在哪裡可以購買當地的預付上網 SIM 卡或 eSIM？"),
    ("There are multiple telecom kiosks right by exit doors.", "出境大廳各出口旁邊就有好幾家通訊業者的攤位。"),
    ("How much for unlimited data for seven days?", "七天吃到飽無限上網方案要多少錢？"),
    ("Can you help me install and activate it on my phone?", "可以幫我在手機上安裝並開通啟用嗎？"),
    ("Where can I catch an Uber or airport taxi?", "請問要在哪裡搭乘 Uber 或機場排班計程車？"),
    ("Follow the rideshare pickup signs on level two.", "跟著二樓的 Rideshare 網約車專用上車指標走即可。"),
    ("I ordered an Uber, it says it will arrive in three minutes.", "我剛剛叫了一輛 Uber，App 顯示三分鐘後會抵達。"),
    ("Look for a white Toyota with license plate 8899.", "請注意找一輛車牌號碼 8899 的白色豐田轎車。"),
    ("Put your bags in the trunk and hop in!", "把行李放進後車廂，趕快上車吧！"),
    ("Thanks, let's head to our hotel and get some rest!", "謝謝，那我們出發前往飯店好好休息吧！")
])

# ==========================================
# 10. 職場溝通與會議 (100)
# ==========================================
add('職場商務與會議', [
    ("Good morning everyone! Let's get started.", "大家早安！我們準備開始開會囉。"),
    ("Can everyone hear me clearly on the call?", "線上通話的各位都能清楚聽到我的聲音嗎？"),
    ("Sorry about that, I was on mute!", "不好意思，我剛剛不小心按到靜音了！"),
    ("Could you please share your screen with us?", "能麻煩你在線上分享一下你的螢幕畫面嗎？"),
    ("Can everyone see my slides now?", "大家現在都能看到我的簡報投影片了嗎？"),
    ("Yes, it's coming through loud and clear.", "看到了，畫面和聲音都非常清晰順暢。"),
    ("Let's quickly go over today's agenda.", "我們快速過一下今天會議要討論的各項議程。"),
    ("Could you send me that link in the Slack chat?", "可以麻煩把那個連結貼在 Slack 聊天室給我嗎？"),
    ("I'll attach the PDF file in the follow-up email.", "我會在會後的追蹤郵件中附上這份 PDF 檔案。"),
    ("Let's touch base on this project tomorrow morning.", "關於這個專案，我們明早再來簡短對焦碰一下。"),
    ("Are you free for a quick five-minute sync?", "你有空進行五分鐘的快速同步確認嗎？"),
    ("Let's jump on a quick call to sort this out.", "我們直接打個簡短通話把這件事搞定吧。"),
    ("What's the deadline for submitting this proposal?", "提交這份提案企劃案的截止日期是何時？"),
    ("The hard deadline is Friday by 5 PM.", "最晚的死線是本週五下午 5 點整。"),
    ("I'm currently working on the final draft.", "我目前正在趕工做最後一份修訂草稿。"),
    ("Could you take a quick look and give me some feedback?", "能請你幫我快速看一下並給我一些回饋建議嗎？"),
    ("Looks great to me, just a few minor typos.", "整體看起來很棒，只發現幾個小小的錯字而已。"),
    ("Thanks for catching those! I'll fix them right away.", "謝謝你抓出來！我馬上把它們修正好。"),
    ("I'm swamped with meetings all afternoon today.", "我今天整個下午都被各種會議塞爆了。"),
    ("Let's push our 1-on-1 meeting to next Monday.", "我們把一對一會談順延改到下週一吧。"),
    ("Does 2 PM work for you, or is 3 PM better?", "下午 2 點對你方便嗎？還是 3 點比較好？"),
    ("Either time works great for me, send an invite!", "兩個時間我都可以，發行事曆邀請給我吧！"),
    ("I'll send over a calendar invite shortly.", "我稍後會發送 Google Calendar 會議邀請過去。"),
    ("I'll be out of the office starting tomorrow afternoon.", "我明天下午開始會請假不在辦公室。"),
    ("If anything urgent comes up, message me on Teams.", "如果有任何緊急突發狀況，可以在 Teams 上私訊我。"),
    ("I'll be covering for Sarah while she is on leave.", "在 Sarah 休假這段期間，我會代理處理她的業務。"),
    ("Who is the main point of contact for this client?", "請問這個客戶窗口的主要負責人是誰？"),
    ("David is leading this account, so check with him.", "David 是負責這個客戶的主管，去跟他確認吧。"),
    ("Let's loop Emily into this email thread.", "我們把 Emily 也加入這個郵件討論串中吧。"),
    ("Keep me in the loop regarding any new updates.", "有任何最新後續進展，請隨時讓我保持知情。"),
    ("I'll keep you posted as soon as I hear back.", "一旦收到對方的回覆，我會立刻跟你通報。"),
    ("Let's wrap up today's meeting and take action items.", "我們今天會議就開到這裡，來整理行動代辦清單。"),
    ("Who wants to take ownership of this task?", "有誰想要主導認領這項工作任務嗎？"),
    ("I can handle that part, no problem!", "那一塊我可以來負責搞定，沒問題！"),
    ("Thanks for stepping up and taking the lead on this.", "謝謝你主動挺身而出挑起這項大樑。"),
    ("Let's schedule a follow-up meeting for next Thursday.", "我們把下次追蹤進度會議定在下週四。"),
    ("I'll send out the meeting minutes by the end of the day.", "我會在今天下班前把會議記錄整理寄給各位。"),
    ("Could you resend that spreadsheet? I can't open it.", "可以麻煩重寄那份試算表嗎？我這邊開不起來。"),
    ("Check your inbox now, I just resent it.", "現在看你的信箱，我剛剛已經重新寄出了。"),
    ("Got it, thanks! It works perfectly now.", "收到了，謝謝！現在可以正常打開了。"),
    ("Let's brainstorm some creative ideas for the campaign.", "我們一起為這次行銷活動腦力激盪想些創意吧。"),
    ("There are no bad ideas in a brainstorm session.", "在腦力激盪討論時，沒有任何點子是不好的。"),
    ("What if we collaborated with local coffee brands?", "如果我們和在地的知名咖啡品牌跨界聯名呢？"),
    ("I love that idea! That could really drive engagement.", "我超愛這個點子！這絕對能大幅提升互動率。"),
    ("Let's run a small pilot test before launching fully.", "在全面正式上線推廣之前，我們先做小規模試跑。"),
    ("That's a very smart and safe approach.", "那是個非常聰明又穩妥的做法。"),
    ("We need to cut down unnecessary expenses this quarter.", "我們這季必須設法縮減不必要的開銷支出。"),
    ("Let's review our software subscriptions.", "我們來逐一盤點審視一下公司訂閱的各項軟體服務。"),
    ("We can cancel the tools that nobody uses.", "我們可以退訂那些根本沒人在用的冷門工具。"),
    ("That will save us a few thousand dollars a month.", "那樣每個月至少能幫公司省下好幾千美元。"),
    ("How are we tracking against our monthly target?", "我們這個月的業績目標目前達成率追蹤得如何？"),
    ("We're currently at 85 percent of our goal.", "我們目前已經達到了既定目標的 85%。"),
    ("With one week left, we can definitely hit 100%.", "還剩下一週時間，我們絕對有機會拚到百分之百。"),
    ("Let's push hard for the finish line!", "大家一起加把勁，全力衝刺達標！"),
    ("Great presentation today! You handled questions very well.", "今天的簡報太精采了！你問題回答得真得體。"),
    ("Thanks! I practiced a lot with my mentor.", "謝謝！我和我的導師私底下演練了很久。"),
    ("Your hard work really paid off.", "你的辛苦努力真的換來了甜美的回報。"),
    ("I appreciate your quick turnaround on this request.", "非常感謝你這麼迅速就處理完這項需求。"),
    ("Happy to help anytime!", "隨時樂意幫忙！"),
    ("Could you grant me edit access to the shared folder?", "可以開給我那個共享資料夾的編輯修改權限嗎？"),
    ("Just sent you full access permissions.", "剛剛已經把完整的編輯權限開通發給你了。"),
    ("Let me know if you run into any access issues.", "如果權限上有遇到任何問題，隨時跟我說。"),
    ("The server is down temporarily for maintenance.", "伺服器目前正因例行維護而暫時離線。"),
    ("It should be back online within thirty minutes.", "預計在三十分鐘之內就會重新恢復連線。"),
    ("Thanks for the update, I'll let the team know.", "謝謝你的最新通知，我這就去轉告團隊同仁。"),
    ("Please review the attached contract before signing.", "在正式簽字之前，請仔細審閱附件中的合約條款。"),
    ("Our legal counsel approved the revised draft.", "我們的法務顧問已經審核通過修改後的最新版本。"),
    ("We're ready to proceed with the signing.", "我們隨時可以進行後續的正式簽約流程。"),
    ("Let's get the digital signature done today.", "我們今天就把電子簽名流程跑完吧。"),
    ("Welcome to our company! We're thrilled to have you.", "熱烈歡迎加入我們公司！非常高興你的到來。"),
    ("Here is your laptop and your security badge.", "這是為你配置的筆記型電腦和員工識別證。"),
    ("Let me show you around the office space.", "我帶你參觀一下整個辦公室環境與各部門。"),
    ("This is the kitchen where we grab coffee and snacks.", "這裡是茶水間，大家都在這裡泡咖啡吃點心。"),
    ("Feel free to ask anyone if you need help settling in.", "剛入職如果有任何不熟悉的地方，儘管開口問大家。"),
    ("Everyone here is super friendly and supportive.", "這裡的每個人都超級友善而且很樂於助人。"),
    ("Thanks so much! I'm really excited to get started.", "非常感謝！我超級期待正式展開工作。"),
    ("Let's do a quick daily stand-up meeting at 9:30.", "我們每天早上 9 點半開個簡短的站立晨會。"),
    ("What did you work on yesterday?", "你昨天主要處理了哪些工作進度？"),
    ("I finished testing the new payment feature.", "我昨天完成了新支付功能的全面測試。"),
    ("Are there any blockers preventing you from moving forward?", "目前手上有遇到任何卡關阻礙前進的問題嗎？"),
    ("No blockers on my end, everything is smooth.", "我這邊完全沒有卡關，一切都很順暢。"),
    ("I'm waiting on approval from the finance department.", "我目前正在等待財務部門的核准簽核。"),
    ("I'll ping the finance manager to expedite it.", "我去敲一下財務經理幫忙催件加速流程。"),
    ("Thanks, that would really speed things up!", "太感謝了，那樣一定能大幅加快進度！"),
    ("Let's make sure we hit our quarterly launch date.", "我們務必確保專案能在本季預定的上線日期發布。"),
    ("Quality comes first, but speed is also crucial.", "品質絕對擺第一，但執行速度同樣至關重要。"),
    ("Let's do a retrospection meeting next week.", "下週我們來開個專案復盤檢討會。"),
    ("What went well, and what could we improve?", "哪些地方做得很好？哪些環節我們還可以改進？"),
    ("I think our cross-team communication was much better.", "我覺得這次跨團隊的溝通效率比以往進步很多。"),
    ("We should automate our testing workflow next time.", "我們下次應該把測試流程進一步自動化。"),
    ("Agreed, let's put that in our next sprint backlog.", "完全贊成，我們把它排進下個衝刺週期的待辦事項。"),
    ("Thank you for your dedication to this launch.", "非常感謝大家為了這次成功上線所付出的辛勞！"),
    ("Let's celebrate with team pizza on Friday!", "本週五我們訂披薩來好好犒賞慶祝一下！"),
    ("Sounds like a great plan, count me in!", "聽起來太棒了，絕對算我一份！"),
    ("I'll place the pizza order for the whole team.", "我來負責幫整個團隊訂披薩外送。"),
    ("Let's keep up the great momentum into next month.", "讓我們把這股絕佳的氣勢與衝勁延續到下個月！"),
    ("Good job everyone, have a great evening!", "大家辛苦了表現超棒，祝各位有個愉快的下班夜晚！"),
    ("See you all bright and early tomorrow morning.", "明天一早見，大家養足精神！"),
    ("Have a restful weekend, don't check your emails!", "週末好好徹底休息放空，千萬別收工作信！"),
    ("I promise I won't open my laptop until Monday!", "我保證週一前絕對不把筆電打開！")
])

# ==========================================
# 11. 電話訊息與約定 (100)
# ==========================================
add('電話通訊與約定', [
    ("Hey! Are you free to talk right now?", "嗨！你現在方便講電話／聊天嗎？"),
    ("Sorry, I'm in a meeting. Can I call you back in twenty minutes?", "抱歉我正在開會，二十分鐘後回電給你方便嗎？"),
    ("Sure, take your time! Call me whenever you're done.", "當然，你先忙！忙完了隨時打給我。"),
    ("Hey, I can barely hear you. The connection is really bad.", "喂，我幾乎聽不太清楚你的聲音，訊號很差。"),
    ("Let me call you right back on regular cell service.", "我掛掉改用手機門號直接打給你。"),
    ("Is this better now? Can you hear me clearly?", "現在這樣有好一點嗎？聽得清楚嗎？"),
    ("Yes, much better! What's up?", "有，清楚多了！怎麼啦，有什麼事嗎？"),
    ("Are we still on for dinner tonight?", "我們今晚約吃晚餐的局還有照常進行嗎？"),
    ("Yes, absolutely! Where do you want to meet?", "當然有啊！你想約在哪裡碰面？"),
    ("Let's meet in front of the bookstore at seven.", "那我們晚上七點在書店大門口見。"),
    ("Sounds perfect! See you there at seven.", "太完美了！那我們七點那裡見。"),
    ("I'm running about ten minutes behind schedule, so sorry!", "我路上耽擱了大概會遲到十分鐘，真是不好意思！"),
    ("No worries at all, take your time! I'm already seated.", "完全沒關係，你慢慢來！我已經先入座了。"),
    ("I just arrived! Where are you sitting?", "我剛走進來了！你坐在哪一桌？"),
    ("I'm by the window in the back corner.", "我在最裡面靠窗的那個角落位子。"),
    ("I see you! Waving at you right now.", "我看到你了！我現在正跟你揮手。"),
    ("Could you send me the address / Google Maps pin?", "可以把詳細地址／Google 地圖定位傳給我嗎？"),
    ("Just sent the location link to your WhatsApp.", "我剛剛已經把定位連結傳到你的通訊軟體了。"),
    ("Got it, on my way now! GPS says fifteen minutes.", "收到了，出發中！導航顯示十五分鐘後會到。"),
    ("My phone battery is at 5 percent, it's about to die.", "我手機電量只剩 5%，快要沒電自動關機了。"),
    ("If I don't reply, I'll charge it in my car.", "如果我等等沒回訊息，是我在車上充電中。"),
    ("Do you have a portable power bank on you?", "你身上有帶行動電源隨身充嗎？"),
    ("Yeah, I have an extra charging cable you can use.", "有啊，我有多帶一條充電線可以借你用。"),
    ("Shoot me a text when you leave your house.", "你一走出家門口就傳個簡訊跟我說一聲。"),
    ("Leaving right now! See you in a bit.", "現在出門囉！待會見。"),
    ("Can we reschedule our coffee date to tomorrow?", "我們可以把喝咖啡的約改約到明天嗎？"),
    ("Something came up at home that I need to take care of.", "家裡臨時有點突發狀況需要我趕回去處理一下。"),
    ("Of course! Hope everything is okay at home.", "當然沒問題！希望家裡一切都好。"),
    ("Thanks for understanding, I really appreciate it.", "謝謝你的體諒，真的太感謝了。"),
    ("Let's check in tomorrow morning and pick a new time.", "我們明早再來聯絡對時間，重新約一個時段。"),
    ("Did you get my voice message from earlier?", "你有收到我剛發給你的那段語音訊息嗎？"),
    ("Sorry, I was driving. Let me listen to it now.", "抱歉我剛剛在開車，我現在馬上聽。"),
    ("I left you a voicemail, give me a ring when free.", "我留了語音信箱給你，有空時回撥通電話給我。"),
    ("Who was calling you just now?", "剛剛是誰打電話找你啊？"),
    ("It was just a spam caller trying to sell insurance.", "只是推銷保險的騷擾垃圾電話而已啦。"),
    ("I get so many spam robocalls every day.", "我每天也接到超級多這種詐騙或推銷機器人電話。"),
    ("You should block that unknown number.", "你應該要把那個陌生號碼直接封鎖掉。"),
    ("I'll text you the recipe later tonight.", "我今晚晚點會把食譜做法傳訊息給你。"),
    ("Please remind me if I forget to send it!", "如果我等等忘記傳了，記得提醒我一下喔！"),
    ("I set a reminder on my phone so I won't forget.", "我在手機裡設了提醒鬧鐘，這樣就不會忘了。"),
    ("Are you in the group chat for the weekend trip?", "你有在我們這趟週末出遊的群組聊天室裡面嗎？"),
    ("Not yet! Could you please add me to the group?", "還沒耶！能麻煩你把我拉進群組裡嗎？"),
    ("Just added you. Check out the pinned announcement.", "剛剛把你加進去了，看一下置頂的公告訊息。"),
    ("I voted on the lunch poll in the chat.", "我剛剛已經在群組裡的午餐投票投好票了。"),
    ("Most people want to go for Korean BBQ.", "大部分的人都想去吃韓式烤肉。"),
    ("Korean BBQ sounds delicious! I'm totally down.", "韓式烤肉聽起來超讚！我完全贊成。"),
    ("What time should we all meet up on Saturday?", "我們週六大家應該幾點集合出發？"),
    ("Let's meet at the train station at 8:30 AM sharp.", "我們早上 8 點半在火車站準時集合。"),
    ("Please don't be late! The train won't wait.", "千萬別遲到喔！火車是不等人開走的。"),
    ("I'll set three alarms just to be sure.", "為了以防萬一，我會設三個鬧鐘。"),
    ("Did you see the photo I posted on Instagram?", "你有看到我剛在 IG 上發的那張照片嗎？"),
    ("Yes! That sunset photo looked absolutely stunning.", "有啊！那張夕陽的照片拍得實在太美了。"),
    ("Where was that taken?", "那是在哪裡拍的呀？"),
    ("At the rooftop bar near the harbor.", "在港口附近那家頂樓景觀酒吧拍的。"),
    ("We should go there together next time.", "我們下次一定要一起去那裡坐坐。"),
    ("Can I FaceTime / video call you for a second?", "我可以撥視訊電話給你一分鐘嗎？"),
    ("Sure, give me two minutes to put on a shirt!", "可以，給我兩分鐘穿件衣服！"),
    ("I'm calling you on video right now.", "我現在視訊撥過去囉。"),
    ("Can you see my screen while I show you this app?", "我操作給你看這個 App 時，你能看清畫面嗎？"),
    ("Yes, it's very clear! That looks super useful.", "看得到，很清楚！那個工具看起來真方便。"),
    ("I'll send you the download link.", "我等等把下載連結傳給你。"),
    ("Thanks for sharing that with me.", "謝謝你跟我分享這個好東西。"),
    ("Call me when you get off work.", "你下班後記得打電話給我。"),
    ("I'll be off in about an hour.", "我大概再一個小時左右就下班了。"),
    ("Take your time, no rush.", "慢慢來，不用著急。"),
    ("I sent you an email with the flight tickets.", "我已經把電子機票用 Email 寄到你信箱了。"),
    ("I'll save them to my phone wallet right now.", "我現在馬上把它們存進我的手機錢包裡。"),
    ("Are you free for lunch tomorrow?", "你明天中午有空一起吃午餐嗎？"),
    ("Tomorrow works great! Where do you want to go?", "明天很可以！你想去哪裡吃？"),
    ("How about that sushi place near your office?", "你辦公室附近那家壽司店如何？"),
    ("Sounds like a plan! Let's meet at noon.", "好提議！那我們明天中午十二點見。"),
    ("I'll book a table under my name.", "我會先用我的名字預訂一張桌子。"),
    ("Thanks for making the reservation!", "謝謝你幫忙訂位！"),
    ("See you tomorrow at twelve!", "明天十二點見囉！"),
    ("My phone is lagging, let me restart it.", "我手機現在有點卡頓，我重新開機一下。"),
    ("Message me on my laptop if you need me.", "如果你急著找我，可以用電腦傳訊息給我。"),
    ("I'll be offline for the next two hours on a flight.", "我接下來兩個小時在飛機上會處於離線狀態。"),
    ("Safe travels! Text me when you land.", "旅途平安！落地後記得傳個訊息報平安。"),
    ("Just landed and got my bags!", "我剛順利降落，也拿到行李了！"),
    ("Awesome, welcome home!", "太棒了，歡迎回到家！"),
    ("Call me as soon as you have a free minute.", "只要你有空檔，第一時間打通電話給我。"),
    ("Is everything alright? Sounds urgent.", "一切都還好嗎？聽起來好像蠻緊急的。"),
    ("Everything is fine, just wanted to share some good news!", "沒事沒事一切都很好，只是想跟你分享一個大好消息！"),
    ("You scared me for a second! Tell me all about it.", "你剛剛嚇了我一跳！快說，是什麼好消息？"),
    ("I got the job offer!", "我拿到那份工作的錄取通知了！"),
    ("OMG, congratulations! That is huge news!", "天啊，太恭喜你了！這真是天大的好消息！"),
    ("We definitely have to celebrate this weekend.", "我們這週末一定要出門好好慶祝一番！"),
    ("Dinner is on me to celebrate!", "這頓慶祝晚餐全由我來買單！"),
    ("I can't wait! Let's talk more tonight.", "太期待了！我們今晚再詳聊。"),
    ("Talk to you tonight, bye for now!", "今晚聊，先拜拜囉！"),
    ("Can you give me his phone number?", "你能把他個人的手機電話號碼給我嗎？"),
    ("I'll send his contact card over right away.", "我馬上把他的電子聯絡人名片分享傳給你。"),
    ("Did you save my new phone number?", "你有存我換的這支新手機號碼了嗎？"),
    ("Yes, I updated your contact in my address book.", "有，我已經在通訊錄裡更新你的聯絡資訊了。"),
    ("Let me know if this number works for texting.", "跟我說一聲這個號碼能不能正常收發簡訊。"),
    ("Yep, loud and clear! Message received.", "可以，訊息完全正常收到了！"),
    ("I'm driving right now, so I'll text you when I park.", "我現在正在開車，停好車後我再傳訊息給你。"),
    ("Drive safely and take your time.", "開車注意安全，慢慢開不急。"),
    ("All parked! heading inside the mall now.", "停好車了！我現在正走進購物中心裡。"),
    ("See you by the fountain on the ground floor!", "一樓噴水池旁邊見囉！")
])

# ==========================================
# 12. 居家生活與健康 (100)
# ==========================================
add('生活健康與日常', [
    ("I need to do my laundry and fold my clothes tonight.", "我今晚得洗衣服並把衣服摺好。"),
    ("Could you take out the trash on your way out?", "出門時能順便幫忙把垃圾拿出去丟嗎？"),
    ("Don't forget to lock the front door when you leave.", "出門離開時別忘了把大門鎖好。"),
    ("Can you turn on the air conditioner? It's burning hot in here.", "可以開冷氣嗎？這裡面真的熱翻了。"),
    ("Could you turn down the heater a little bit?", "可以把暖氣稍微調小一點點嗎？"),
    ("I'm making dinner tonight, do you want to join?", "我今晚要自己下廚煮晚餐，你要一起吃嗎？"),
    ("What are you making? It smells amazing!", "你在煮什麼好料的？聞起來好香喔！"),
    ("I'm cooking garlic butter shrimp pasta.", "我正在煮蒜香奶油鮮蝦義大利麵。"),
    ("Can I help you chop the vegetables or set the table?", "我能幫你切切蔬菜或是擺放餐具嗎？"),
    ("Could you please wash the dishes after dinner?", "吃完晚餐後能麻煩你幫忙洗碗嗎？"),
    ("Sure, I'll take care of the kitchen cleanup.", "沒問題，廚房的清理收拾就交給我負責。"),
    ("We're out of eggs and milk. I need to run to the grocery store.", "家裡的雞蛋和牛奶吃完了，我得跑一趟超市採買。"),
    ("Can you pick up some bananas while you're there?", "你去超市時可以順便幫我買幾根香蕉嗎？"),
    ("I'm going to vacuum the living room and mop the floor.", "我打算把客廳吸一吸地，然後拖一下地板。"),
    ("I didn't sleep well last night, I kept tossing and turning.", "我昨晚睡得很不好，整夜翻來覆去睡不著。"),
    ("You should try going to bed earlier tonight.", "你今晚應該試著早點上床睡覺。"),
    ("I have a terrible headache and feel dizzy today.", "我今天頭痛得很厲害，而且感到有些頭暈。"),
    ("Have you taken any pain relievers yet?", "你吃過止痛藥了嗎？"),
    ("I took some aspirin with water an hour ago.", "我一個小時前有配溫水吃了一顆阿斯匹靈。"),
    ("You look pale; you should probably lie down and rest.", "你的臉色看起來很蒼白，你應該去躺著好好休息。"),
    ("I have a sore throat and a runny nose.", "我喉嚨很痛，而且一直在流鼻水。"),
    ("Drink plenty of warm water with honey and lemon.", "多喝加了蜂蜜和檸檬的溫開水。"),
    ("I think I have a slight fever. Let me check my temperature.", "我覺得我好像有點發燒，我來量一下體溫。"),
    ("The thermometer says 38 degrees Celsius.", "體溫計顯示是攝氏 38 度。"),
    ("You should definitely see a doctor this afternoon.", "你今天下午絕對應該去看一下醫生。"),
    ("I'd like to make an appointment with Dr. Smith today.", "我想預約今天看 Smith 醫師的門診。"),
    ("Do you have any openings available around 4 PM?", "請問下午 4 點左右有任何可預約的看診時段嗎？"),
    ("What symptoms are you experiencing right now?", "請問您目前出現了哪些不適的症狀？"),
    ("I've had a bad cough and fever for two days.", "我已經嚴重咳嗽和發燒連續兩天了。"),
    ("Are you allergic to any medications?", "請問您對任何藥物有過敏史嗎？"),
    ("No known drug allergies, as far as I know.", "就我所知，我沒有對任何藥物過敏。"),
    ("Please take this medication three times a day after meals.", "請照這份處方三餐飯後服用此藥物，一日三次。"),
    ("Will this medicine make me drowsy?", "吃了這種藥會讓我感到昏昏欲睡想睡覺嗎？"),
    ("Yes, so please avoid driving after taking it.", "會的，所以服藥後請避免親自開車駕駛。"),
    ("I need to pick up my prescription at the pharmacy.", "我需要去藥局領取我的處方藥品。"),
    ("Where is the nearest 24-hour pharmacy?", "請問最近的 24 小時營業藥局在哪裡？"),
    ("I have a dentist appointment for a teeth cleaning tomorrow.", "我明天有預約牙醫要做例行洗牙檢查。"),
    ("Remember to brush your teeth and floss every night.", "記得每天晚上睡前都要刷牙並使用牙線清潔。"),
    ("My lower back really hurts from sitting all day.", "在辦公桌前久坐了一整天，我的下背部好痠痛。"),
    ("You should do some gentle stretches and walk around.", "你應該做一些溫和的伸展拉筋，起身走動走動。"),
    ("I love going for a morning jog in the neighborhood park.", "我很喜歡早上去社區公園慢跑晨練。"),
    ("How many miles do you usually run?", "你平時慢跑通常都跑幾英里／幾公里？"),
    ("I usually run about three miles every other day.", "我通常隔天跑一次，每次大概跑三英里。"),
    ("Working out regularly gives me so much energy.", "規律運動鍛鍊給了我充沛滿滿的活力。"),
    ("I'm trying to cut back on sugary drinks and soda.", "我目前正在努力減少喝含糖飲料和汽水。"),
    ("Drinking more water makes your skin look so much healthier.", "多喝水會讓你的皮膚看起來健康光澤許多。"),
    ("I always keep a reusable water bottle by my desk.", "我總是在辦公桌旁放一個環保隨身水壺。"),
    ("Don't forget to apply sunscreen before going outside.", "出門前千萬別忘了全身塗抹防曬乳液。"),
    ("The UV index is really high today.", "今天的紫外線指數真的非常高。"),
    ("I wear sunglasses to protect my eyes from the bright glare.", "我戴太陽眼鏡是為了保護眼睛免受強烈刺眼光線傷害。"),
    ("I'm going to take a twenty-minute power nap.", "我準備來小睡補眠二十分鐘充電一下。"),
    ("Set an alarm so you don't oversleep!", "設個鬧鐘，這樣才不會不小心睡過頭！"),
    ("Waking up from a short nap makes me feel brand new.", "小睡醒來後，整個人感覺脫胎換骨、神清氣爽。"),
    ("I like listening to relaxing music while reading in bed.", "我喜歡躺在床上看書時聽些讓人放鬆的輕音樂。"),
    ("A hot chamomile tea helps me fall asleep faster.", "喝一杯溫熱的洋甘菊茶能幫助我更快入睡。"),
    ("Turn off all the lights and close the curtains.", "把所有的燈都關掉，並把窗簾拉好。"),
    ("Good night! Sleep tight and have sweet dreams.", "晚安！睡個好覺，祝你好夢。"),
    ("My alarm went off at 6:30 this morning.", "今天早上我的鬧鐘在 6 點半響起。"),
    ("I hit the snooze button twice before getting up.", "起床前我按了兩次貪睡延遲鬧鐘。"),
    ("I make my bed as soon as I get out of it.", "我一起床的第一件事就是把被子床鋪整理好。"),
    ("Opening the window lets fresh morning air in.", "把窗戶打開能讓早晨新鮮的空氣流通進來。"),
    ("I brew a fresh pot of coffee every single morning.", "我每天清晨都會親自現煮一整壺熱咖啡。"),
    ("The kitchen smells amazing when coffee is brewing.", "煮咖啡時，整個廚房都瀰漫著濃郁迷人的香氣。"),
    ("What do you want for breakfast? Toast or oatmeal?", "你早餐想吃什麼？烤土司還是燕麥粥？"),
    ("I'll have some toast with butter and jam, please.", "我要烤土司抹奶油和果醬，謝謝。"),
    ("Eating a healthy breakfast gives you fuel for the day.", "吃一頓健康的早餐能為你整天提供充足的動力。"),
    ("I need to water the house plants on the balcony.", "我得去陽台幫那些室內盆栽澆澆水了。"),
    ("Look at that orchid, it's finally blooming!", "你看那盆蘭花，它終於開花了！"),
    ("Gardening is such a peaceful and relaxing hobby.", "蒔花弄草做園藝真是一項寧靜又舒壓的嗜好。"),
    ("I'm sorting through my closet to donate old clothes.", "我正在整理衣櫃，打算把舊衣服整理出來捐贈。"),
    ("Decluttering your room really clears your mind.", "把房間斷捨離收拾乾淨，心靈真的會跟著清爽起來。"),
    ("Put the recycling bins out on the curb tonight.", "今晚記得把資源回收桶推到路邊放好。"),
    ("Tomorrow morning is recycling pickup day.", "明天早上是回收車來清運的日子。"),
    ("I always bring reusable shopping bags to the store.", "我去超市買東西時總是會自備環保購物袋。"),
    ("Saving electricity and turning off lights helps the planet.", "隨手隨處關燈節約用電有助於保護我們的地球。"),
    ("I like spending time outdoors in nature on weekends.", "我喜歡在週末假日多花點時間身處大自然戶外。"),
    ("A walk in the forest reduces stress and anxiety.", "在森林步道裡散步能有效減輕生活壓力和焦慮感。"),
    ("I feel so grounded when I go hiking in the mountains.", "去山裡健行爬山時，我感到內心無比踏實平靜。"),
    ("Make sure to wear comfortable hiking boots.", "出發前務必確認穿上舒適好走的登山鞋。"),
    ("Pack plenty of water and energy snacks in your backpack.", "在後背包裡準備充足的水和高能量小點心。"),
    ("Safety always comes first when you're exploring outdoors.", "在戶外探索大自然時，安全永遠是第一考量。"),
    ("I twisted my ankle while jogging on the uneven trail.", "在不平坦的小徑上慢跑時，我不小心扭到了腳踝。"),
    ("Apply an ice pack to reduce the swelling.", "趕快冰敷一下來幫助消腫退腫。"),
    ("Elevate your foot on a pillow and rest it.", "把腳墊在高枕頭上抬高，並且好好靜養。"),
    ("If the pain doesn't improve by tomorrow, see a doctor.", "如果到了明天疼痛沒有改善，一定要去看醫生。"),
    ("I'm feeling much better today, the swelling went down.", "我今天感覺好多了，腫脹已經明顯消退了。"),
    ("Take it easy and don't rush back to heavy exercise.", "放慢步調休養，先別急著恢復高強度的激烈運動。"),
    ("Listen to your body and give it time to heal.", "多傾聽身體發出的聲音，給自己充足的自癒時間。"),
    ("A balanced diet and good sleep work wonders.", "均衡的飲食加上優質充足的睡眠，效果非常神奇。"),
    ("I'm cooking a warm pot of chicken noodle soup.", "我正在燉煮一鍋溫熱暖胃的雞湯麵。"),
    ("Nothing soothes a cold better than hot chicken soup.", "沒有什麼比一碗熱騰騰的雞湯更能舒緩感冒的不適了。"),
    ("Have a big bowl and get some rest in bed.", "多喝一大碗，然後回床上好好躺著休息。"),
    ("Thank you so much for taking care of me today.", "今天真的太感謝你無微不至地照顧我了。"),
    ("That's what family and friends are here for!", "家人和朋友本來就是要在這時候互相照應的！"),
    ("I'm ready to turn off the lights and fall asleep.", "我準備把燈關掉，要進入夢鄉了。"),
    ("Have a restful night and sleep tight.", "祝你有個安穩香甜的夜晚，睡個好覺。"),
    ("See you tomorrow morning, bright and early!", "明天一早見，神采飛揚！"),
    ("Good night!", "晚安！"),
    ("Sweet dreams!", "祝好夢！"),
    ("Take good care of yourself always.", "平時隨時都要好好照顧愛惜自己的身體喔。")
])

# Save and verify
total = len(data)
print(f'Total sentences generated: {total}')

# Ensure uniqueness of English sentences
seen = set()
duplicates = []
for item in data:
    if item['en'] in seen:
        duplicates.append(item['en'])
    seen.add(item['en'])

if duplicates:
    print(f'WARNING: Found {len(duplicates)} duplicates: {duplicates[:5]}')
else:
    print('All sentences are completely unique!')

# Ensure continuous sequential IDs
for idx, item in enumerate(data):
    item['id'] = idx + 1

# Write output files to all relevant paths
output_paths = [
    'web/data/sentences_1000.json',
    'web/sentences_1000.json',
    'data/sentences_1000.json',
    'sentences_1000.json',
    'bin/Debug/sentences_1000.json',
    'bin/Release/sentences_1000.json'
]

for p in output_paths:
    dir_name = os.path.dirname(p)
    if dir_name:
        os.makedirs(dir_name, exist_ok=True)
    with open(p, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f'Successfully exported: {p}')
